### ISSUE TITLE
URLs signed with "-u" can expire before specified duration

### ISSUE THREAD

**Issue by mhandugan** [GoogleCloudPlatform/gsutil#1007]
The "-u" option to gsutil signs URLs using a service-account key with an expiration date. There is no means of controlling which key is used and no way of verifying the service-account key will out-live the signed-url expiration date.

**Comment by dilipped** [comment]
We have restricted the signurl duration to 12 hours if -u flag is used. Fixed in https://github.com/GoogleCloudPlatform/gsutil/pull/1014
