### ISSUE TITLE
Issue when creating buckets with special characters

### ISSUE THREAD

**Issue by tvvignesh** [GoogleCloudPlatform/gsutil#1012]
Hi. When we run a command like this:

```
GCP_PROJECT=my-project
BUCKET=my-bucket
CLUSTER_REGION=asia-south1

gsutil mb -p ${GCP_PROJECT} -l ${CLUSTER_REGION} gs://$BUCKET/
```

It throws the error `ServiceException: 409 Bucket my-bucket already exists.` but doing `gsutil ls` does not show any bucket nor does the UI online. Then I noticed that this did not happen for buckets without a hyphen `mybucket` works instead of `my-bucket`.

The error is kind of misleading even if hyphens are not allowed (not sure if they are).

Thanks.

**Comment by dilipped** [comment]
That bucket name is probably in use by another user. Checkout https://cloud.google.com/storage/docs/gsutil/commands/mb?hl=en#description
As suggested there, `gsutil help naming` will provide more information on bucket naming.
