### ISSUE TITLE
gcloud - Custom roles update

### ISSUE THREAD

**Issue by tvvignesh** [GoogleCloudPlatform/gsutil#1013]
Hi. This is related to the `gcloud` tool but not able to find a repo for that, so filing it here.
The page https://cloud.google.com/sdk/gcloud/reference/iam/roles/update suggests that roles can be updated by using `gcloud iam roles update roles/ProjectUpdater --organization=123 --file=role_file_path` but when I tried like this: 
`gcloud iam roles update roles/${ROLE_NAME} --organization "${ORGID}" --title "${ROLE_TITLE}" --permissions "$(IFS=","; echo "${ROLE_PERMISSIONS[*]}")"` it said:

`ERROR: (gcloud.iam.roles.update) Invalid value for [ROLE_ID]: The role id that starts with 'roles/' only stands for curated role. Should not specify the project or organization for curated roles`

So, it then worked without the prefix `roles/`

``gcloud iam roles update roles/${ROLE_NAME} --organization "${ORGID}" --title "${ROLE_TITLE}" --permissions "$(IFS=","; echo "${ROLE_PERMISSIONS[*]}")"``

Kind of misleading. Thought I would let you guys know.

**Comment by dilipped** [comment]
gcloud sdk is not open-source, hence you were not able to find the repo. You can file your issues here https://cloud.google.com/support/docs/issue-trackers
