### ISSUE TITLE
gsutil rsync exclude behavior

### ISSUE THREAD

**Issue by btsherid** [GoogleCloudPlatform/gsutil#1015]
Hi,

I'm wondering if the behavior I'm seeing is expected.

I'm running a gsutil rsync command like this: <code>gsutil -m rsync -r -e -C -x .*labs|.*.snapshot|.*snapshot|.*.bam|.*.bai|.*stdoe|.*status|.*working dir gs://bucket/dir</code>

I have tested with a test directory, and confirmed that all the excludes are working. With the test directory, the command takes a few seconds to finish. 

With the actual directory I want to copy, it looks like this:
$ ls dir
labs

I would expect the above command to take a few seconds for the actual directory as well, because I'm excluding labs and there's nothing else there, but in the Building synchronization state... step, it loops over every file in labs (because I see lots of messages for skipping symlinks in the labs directory), then finally errors out on one of the files. The rsync ran for 3 hours and 45 minutes before it finally errored out.

I also confirmed that it is looking through excluded directories in my test dir by creating a symlink in an excluded directory in and I see it skipped in the output.

I'm wondering why it looped over those files and errored out at all. I would expect it to see that I'm excluding the labs directory, not have to loop over those files, and take a few seconds to finish.

For reference, this command to a fuse mounted bucket took < 1s: <code>rsync -avz --exclude status --exclude stdoe --exclude working --exclude ~snapshot --exclude .snapshot --exclude *.bam --exclude *.bai --exclude labs dir GCP bucket mnt/dir</code>

Thank You,
Brendan Sheridan

**Comment by dilipped** [comment]
Looks like you have .labs instead of labs in your command. Also, make sure to put the value of -x in double quotes https://cloud.google.com/storage/docs/gsutil/commands/rsync

**Comment by btsherid** [comment]
Coming back to this to see if want I'd like to do is possible.

The last comment said I may have had a typo in my command. My question is, for the commands below, why does gsutil rsync step through the excluded directories? The reason I want to exclude these directories is to speed up the command completion time and to avoid files that will cause the gsutil rsync to fail.

# gsutil -m rsync -r -e -C -x "snapshot" /NS/lbg-netapp4_lbgnetapp4_root/ gs://lccc-gcp-archive/NS/lbg-netapp4_lbgnetapp4_root/
Building synchronization state...
Caught non-retryable exception while listing file:///NS/lbg-netapp4_lbgnetapp4_root/: [Errno 2] No such file or directory: '/NS/lbg-netapp4_lbgnetapp4_root/.snapshot/hourly.2020-08-24_1005/.vsadmin'
CommandException: Caught non-retryable exception - aborting rsync

For the above command I have tried all of the following with the same output: ".*.snapshot", "snapshot", ".*snapshot", ".*\.snapshot$", "\.snapshot"

# gsutil -m rsync -r -e -C -x "bioinformatics" /datastore/nextgenout5/share/labs/ gs://lccc-gcp-archive/datastore/nextgenout5/share/labs/
Building synchronization state...
Skipping symlink directory "/datastore/nextgenout5/share/labs/bioinformatics/<redacted>"
Skipping symlink directory "/datastore/nextgenout5/share/labs/bioinformatics/<redacted>"
Skipping symlink directory "/datastore/nextgenout5/share/labs/bioinformatics/<redacted>"
Skipping symlink directory "/datastore/nextgenout5/share/labs/bioinformatics/<redacted>"

-Brendan
