### ISSUE TITLE
Migrating from deprecated oauth2client to google-auth-library-python

### ISSUE THREAD

**Issue by LevonAr** [GoogleCloudPlatform/gsutil#1022]
The oauth2client client that gsutil depends on was deprecated years ago, and is currently unmaintained. Even though a version was pulled into [gsutil/gslib/vendored/oauth2client](https://github.com/gsutil-mirrors/oauth2client) and patched to fix https://github.com/GoogleCloudPlatform/gsutil/issues/994, migrating to a maintained library would probably be a good idea to avoid future problems.

I'd love to do the work of migrating gsutil over to the [google-auth-library-python](https://github.com/googleapis/google-auth-library-python) as recommended in the oauth2client readme page, would there be any objections to me taking that on and eventually sending in a PR?

**Comment by dilipped** [comment]
@LevonAr  Thank you for your interest in working on the migration efforts. However, we're awaiting on a broader solution and this migration is not on our roadmap for now. We will keep you posted if anything changes.

**Comment by LevonAr** [comment]
Aww dang it haha. I was really looking forward to this so I went ahead and started familiarizing myself with the directory already. Oh well, at least I learned how gsutil works better. I'll just try to work on other open issues here. Thanks for your response!

**Comment by dilipped** [comment]
You're welcome. I will close this one.
