### ISSUE TITLE
Add a silent or quiet mode for gsutil

### ISSUE THREAD

**Issue by jterrace** [GoogleCloudPlatform/gsutil#106]
_Original author: sethladd@google.com (August 02, 2012 17:40:03)_

We use gsutil in our scripts which run on linux, mac, and windows. We'd like gsutil to run in silent or quiet mode to avoid cluttering up our logs with lots and lots of upload statements.

Thanks!

_Original issue: http://code.google.com/p/gsutil/issues/detail?id=108_

**Comment by twistedpair** [comment]
> The cp -q option does what you're asking for.

Correction, the proper flag location, since `gsutil` is flag position sensitive, is:

```bash
gsutil -q cp gs://foo/bar .
```

**Comment by zymotik** [comment]
An environment variable would be ace!
