### ISSUE TITLE
trickle + gsutil + cp, uploads mp4 file at full speed even though "-u 100" is set.

### ISSUE THREAD

**Issue by ChristianBachla** [GoogleCloudPlatform/gsutil#1089]
I have tried the trickle command from [the documentation](https://cloud.google.com/storage/docs/gsutil/addlhelp/Throttlinggsutil), where i replaced `rsync -r` with `cp`:

```shell
trickle -s -u 100 -d 100 gsutil -o "GSUtil:parallel_process_count=1" \
 -o "GSUtil:parallel_process_count=1" cp my_video.mp4 gs://my_bucket
```
It uploads a 256 MB file with 25 MB/s instead of 100 KB/s. 

I have tested this on Ubuntu 18.04, amd-64 and arm-64. 

Should gsutil work out of the box, when i install and set it up, or are there some parameters i need to set within the .boto file? 
I have tested trickle and it worked as expected, when i ran the command: `trickle -d 100 -u 100 firefox`, and measured my upload and download speed.

**Comment by starsandskies** [comment]
Out of curiosity, were you able to figure out what was going on? Did it have to do with having:

-o "GSUtil:parallel_process_count=1" -o "GSUtil:parallel_process_count=1"

in the command instead of:

-o "GSUtil:parallel_process_count=1" -o "GSUtil:parallel_thread_count=1"?
