### ISSUE TITLE
Single-threaded commands (setacls at least) die on first error

### ISSUE THREAD

**Issue by jterrace** [GoogleCloudPlatform/gsutil#109]
_Original author: c...@google.com (September 18, 2012 18:29:24)_

<b>What steps will reproduce the problem?</b>
1. Create 30 million objects in a bucket  :)
2. Have co-worker upload one randomly in the middle with a different owner.
3. gsutil setacl -R my.acl gs://my-bucket/blah

<b>What is the expected output? What do you see instead?</b>

Expected: Give an error for any objects that fail, but continue on.
Actual: gsutil exits on the first error.

<b>What version of the product are you using? On what operating system?</b>

gsutil version 3.17
checksum 8bcad8cd00af0580518a3b2ffa57f524 (OK)
boto version 2.5.2
python version 2.6.5 (r265:79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3]

<b>Please provide any additional information below.</b>

This patch to command.py does what I want, although I'm sure it's not production quality:

$ diff -u /ita/gsutil/gslib/command.py~ /ita/gsutil/gslib/command.py
--- /ita/gsutil/gslib/command.py~   2012-08-05 08:37:41.000000000 -0400
+++ /ita/gsutil/gslib/command.py    2012-09-18 14:16:02.141532214 -0400
@@ -665,7 +665,11 @@
         elif num_threads &gt; 1:
           thread_pool.AddTask(func, name_expansion_result)
         else:
-          func(name_expansion_result)
-          try:
-            func(name_expansion_result)
-          except Exception, ex:
-            if thr_exc_handler:
-              thr_exc_handler(ex)
     # If any Python threads created, wait here for them to finish.
     if num_threads &gt; 1:
       thread_pool.WaitCompletion()

Note that using -m would probably be a work-around for me, but since I have so many objects that ends up killing my machine and I'd rather just run it single-threaded.  (I could play games with doing it in smaller chunks but I'd rather not.)

_Original issue: http://code.google.com/p/gsutil/issues/detail?id=111_

**Comment by benmarten** [comment]
I am running into the same issue with:

`gsutil setmeta -h "Cache-Control: public, max-age=604800" "gs://leanplum-wordpress/*" `

Any -f or -F doesn't work... Any ideas?

**Comment by thobrla** [comment]
`setmeta` doesn't support a `-f` option, but you could use the global `-m` option which will not only be faster (due to send requests on multiple threads) but also give the continue-on-failure behavior you want.

`gsutil -m setmeta -h "Cache-Control: public, max-age=604800" "gs://bucket/*"`
