### ISSUE TITLE
rsync error "invalid literal for int" when parsing content-length

### ISSUE THREAD

**Issue by mattyb** [GoogleCloudPlatform/gsutil#1110]
Finding this error when running `gsutil -m rsync -r gcs://somepath s3://somepath`

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/daisy_chain_wrapper.py", line 200, in PerformDownload
    decryption_tuple=self.decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 353, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1205, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1337, in _PerformDownload
    use_chunks=False)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 486, in GetRange
    response = self.__ProcessResponse(response)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 433, in __ProcessResponse
    self.__progress += response.length
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 195, in length
    return int(self.info.get('content-length'))
ValueError: invalid literal for int() with base 10: '104857600, 42676706'
invalid literal for int() with base 10: '104857600, 42676706'
```

```
gsutil version: 4.37
```

**Comment by dgilman** [comment]
Also seen with `gsutil version: 4.53` when doing `gsutil cat`. My `CLOUDSDK_PYTHON` is set to `python3.7`

**Comment by mgmarino** [comment]
We have seen this as well, but when calling `cp` (also to an s3 bucket), e.g.:

```
gsutil -m cp \
   "gs://ourbucket.appspot.com/subdir/*.avro"
    s3://our-bucket/subdir/
```

.  The difficult thing is that it seems to go away, i.e. running the same transfer again can succeed and we haven't been able to get a fully reproducible failure.  

We are using the google-sdk docker:

`google/cloud-sdk:312.0.0-slim`

**Comment by mgmarino** [comment]
My suspicion here is there is that there is some issue with threading: i.e. using `-m` runs the commands in separate threads.  Also, I am not sure if the underlying library (httplib2) is actually threadsafe.  This would certainly explain it not being always reproducible.

**Comment by dgilman** [comment]
I've been consistently seeing these errors in non-threaded modes like gsutil cat, I don't know if threading is at fault here.

If I can put on my speculative hat for a moment: it seems like these "two content-lengths in one" messages are valid HTTP, but nobody really supports them, and with most implementations failing the request if the numbers don't match. My hunch is that Google is intentionally sprinkling them into the occasional request to observe failure rates and seek out libraries that need to be patched, possibly as a way of closing opportunities for future security holes around HTTP proxying. The traceback here is coming from down in the apitools library which is Google-maintained and mostly abandoned so it looks like they caught a live one.

**Comment by idsvandermolen** [comment]
We're seeing the same issues now and then when using `gsutil -q -m cp -c -L object.log gs://<some GCS bucket and object>`. We've also noticed that the exception is triggered in `apitools` library which looks unmaintained (404 on homepage https://github.com/hamstah/apitools) and has last release in 2014 (https://pypi.org/project/apitools/#history)

**Comment by knyttl** [comment]
When will this get to production?

**Comment by dilipped** [comment]
This should be out by June 15, 2021.
