### ISSUE TITLE
`cp` command deletes destination local file before download starts

### ISSUE THREAD

**Issue by kosteev** [GoogleCloudPlatform/gsutil#1126]
I am running application that is using configuration file stored in GCS.

I have the following workflow:
- on start up of the container, configuration file is downloaded from GCS bucket
- application starts and reads configuration file
- every minute configuration file is re-downloaded with `gsutil cp` command
- every minute application restarts and re-reads configuration file

The way `gsutil cp` command works: if it downloads file to local file system and the destination file already exists, first it deletes it and then starts to download new file https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/utils/copy_helper.py#L2336.
As a side-effect in my workflow sometimes there is a situation when application restarts and there is no file on disk to read.
The same happens with `gsutil rsync` command which syncs other data needed for an application.

What is suggestion to overcome such a situation? Can we have a flag that will prevent from deleting file in this case and user can take responsibility of the fact that there should be enough space to store two copies of the same file for this short
period of time.

**Comment by kosteev** [comment]
Added PR that can address this issue https://github.com/GoogleCloudPlatform/gsutil/pull/1124

**Comment by kosteev** [comment]
@NickGoog  @thomasmaclean 
Hey guys! Can I bring your attention to this.
We have a hard time experiencing this issue.

**Comment by NickGoog** [comment]
Not sure this is a scenario enough users will encounter to merit code changes.
Can you adjust your workflow slightly? Example:

- On startup, container downloads config file and copies `config.txt` to `config_persistent.txt`
-Application starts and reads `config_persistent.txt`
-Every minute, `config.txt` is re-downloaded with gsutil cp command and copied to `config_persistent.txt`
-Every minute, application restarts and re-reads `config_persistent.txt`

**Comment by thomasmaclean** [comment]
@kosteev Thank you for the contribution but unfortunately we're pretty picky about what functionality constitutes adding a new flag, particularly for `cp`. Hopefully this workaround will suffice.

**Comment by kosteev** [comment]
Hi guys!
Thanks for the response. This is actually a workaround that we have came up with for this scenario.

However, we also use `gsutil rsync` command to sync local directory with assets stored in GCS, and this directory is also read during start up of the application. The workflow is pretty much the same as described for `gsutil cp` above except it uses `rsync`.
What can you recommend in this case?

**Comment by NickGoog** [comment]
Three ideas:

1) If the directory of assets is small, basically use the same workaround. Save a directory `assets_persistent`, download the `assets` directory, locally rsync `assets` to `assets_persistent` if the download completes, and have the application use `assets_persistent`.

2) This one is hacky. Rename every asset with some prefix or suffix like "persistent".
Dry-run rsync with the `-n` flag to output all the operations it would perform (and not actually perform them): https://cloud.google.com/storage/docs/gsutil/commands/rsync#options

Pipe the dry-run output into a script that identifies what files need to change. Re-download those files individually with `gsutil cp`. If the downloads are successful, rename them to the "persistent" version of the file.

3) Use `gsutil cat` to read text files directly in the cloud. You can pipe the output wherever you like, and it probably doesn't have the side-effect of deleting what's there:
https://cloud.google.com/storage/docs/gsutil/commands/cat

Side note:
If your application can run shell commands, it might solve some of the timing issues if it managed its own assets.

**Comment by kosteev** [comment]
@NickGoog Thanks for this!
I like first idea, as a workaround we could implement for us.
Though still under impression that it could be done as a built-in feature to `gsutil` and I respect you answer to not implement this changes in this library.

Thank you, I think we will go with first workaround for now.
