### ISSUE TITLE
content-type: binary/octet-stream - The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

### ISSUE THREAD

**Issue by ORESoftware** [GoogleCloudPlatform/gsutil#1165]
I am on go version:
```
go version go1.15.5 darwin/amd64

```

and the library version:

```
cloud.google.com/go/storage v1.12.0
```

I have this code:

```golang
			url, err := storage.SignedURL(bucket, filename, &storage.SignedURLOptions{
				GoogleAccessID: cfg.Email,
				PrivateKey:     cfg.PrivateKey,
				Method:         method,
				Expires:        expires,
				ContentType:    "binary/octet-stream",
			})

			if err != nil {
				return ctr.WriteJSONErrorResponse(500, cm2t.ErrorResponseData{
					ErrId:          "62604d5e-c767-45b5-890a-687f442fd217",
					Err:            err,
				})
			}

			response, err := http.Post(url, "binary/octet-stream", req.Body)
```

the response says:

> The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

this seems incorrect since the content-type of binary/octet-stream is given. 
what repo can I file this under? this gsutil repo is probably the wrong place

**Comment by dilipped** [comment]
Yes, this is not the right repo for your issue.

You can find the appropriate platform to file your issues here https://cloud.google.com/storage/docs/reference/libraries#additional_resources

Under the go tab, you can see this link https://github.com/googleapis/google-cloud-go/issues

**Comment by ORESoftware** [comment]
I solved this - in my case it wasn't the Content-Type header that was mismatched, it was the HTTP verb that was mismatched - PUT instead of POST
