### ISSUE TITLE
:bug: Object is not visible in console and could not be removed.

### ISSUE THREAD

**Issue by santaonchair** [GoogleCloudPlatform/gsutil#1175]
Hi :)

The file is not visible in the google cloud console. I'm trying to empty my directory but it seems impossible without removing this file. (`gs://my_bucket/path/#1589802545087413`)

I tried to remove:
```shell
$ gsutil rm -rf gs://my_bucket/path/#1589802545087413
Removing gs://my_bucket/path/#1589802545087413...
CommandException: 1 files/objects could not be removed.
```

also tried to move it:

```shell
$ gsutil mv gs://my_bucket/path/#1589802545087413 gs://my_bucket/path/to_remove
Copying gs://my_bucket/path/#15898025450874133...
Removing gs://my_bucket/path/#1589802545087413...
AccessDeniedException: 403 Object 'my_bucket/path/#1589802545087413' is under active Event-Based hold and cannot be deleted, overwritten or archived until hold is removed.
```

and there is no hold in my bucket..

```shell
$ gsutil retention get gs://my_bucket
gs://my_bucket/ has no Retention Policy.
```

It seems that `Event-Based Hold` is enabled only for `gs://my_bucket/path/#1589802545087413`

```shell
$ gsutil ls -L gs://my_bucket/path/#1589802545087413
    Creation time:          Mon, 18 May 2020 11:49:05 GMT
    Update time:            Tue, 05 Jan 2021 05:34:11 GMT
    Storage class:          STANDARD
    Event-Based Hold:       Enabled
    ....
```

If anyone might have an answer to my problem, it would be nice :)

**Comment by starsandskies** [comment]
Also, if you're curious, my guess for why the object does not appear in the Console is because its name starts with a "#". Normally in Cloud Storage, the # character denotes the beginning of an [object generation number](https://cloud.google.com/storage/docs/generations-preconditions#_Generations), so the Console may be thinking this object is an "archived" version and, as a result, should be hidden.

**Comment by santaonchair** [comment]
> Also, if you're curious, my guess for why the object does not appear in the Console is because its name contains a "#". Normally in Cloud Storage, the # character denotes the beginning of an [object generation number](https://cloud.google.com/storage/docs/generations-preconditions#_Generations), so the Console may be thinking this object is an "archived" version and, as a result, should be hidden.

Hi, starsandskies.

Thank you so much! Solved it :)

```shell
$ gsutil retention event release gs://my_bucket/path/#1589802545087413
Operation completed over 1 objects.

$ gsuitl rm -rf gs://my_bucket/path/#1589802545087413
Operation completed over 1 objects.
```

I was using the command wrong

```
$ gsutil retention event-default release gs://my_bucket/path/#1589802545087413
CommandException: "retention" command must specify a bucket
```
