### ISSUE TITLE
gsutil ls problems with ETag #1192

### ISSUE THREAD

**Issue by audouts** [GoogleCloudPlatform/gsutil#1194]
I opened an issue (#1192) that was closed by @dilipped . They did not read what I wrote, where I described that `gsutil` is reporting the wrong ETag for a **non-composite** file.

My description of the problem explained that the file was originally composite and so I knew what to look for, if a file was uploaded as composite. However, I explained that I had replaced the files with non-composite versions and verified by download and by CloudBerry that the ETag was a proper MD5 and that the `x-goog-component-count` field as no longer present.

I don't see a way for me to re-open the issue, so I am opening this as notification.

**Comment by dilipped** [comment]
Hey, sorry, I think I misunderstood your original issue. I will close this one and reopen the original one since that one has more information related to the issue.

**Comment by audouts** [comment]
No problem. Thanks!
