### ISSUE TITLE
No provision to add HMAC aws credentials for "s3://" URIs in .boto file using gsutil cli

### ISSUE THREAD

**Issue by Grandolf49** [GoogleCloudPlatform/gsutil#1196]
## Summary

I am trying to copy files from **AWS S3** to **Google Cloud Storage** using `gsutil cp s3://... gs://...` in a docker container. I have configured `gcloud` and `gsutil` using a service account json file successfully.

`gsutil cp s3://... gs://...` command works perfectly on my local machine as I have manually edited the `~/.boto` file and added the `aws_access_key_id` and `aws_secret_access_key`
```
# To add HMAC aws credentials for "s3://" URIs, edit and uncomment the
# following two lines:
aws_access_key_id = ****
aws_secret_access_key = ****
```

But since I cannot edit that file manually inside the container, how do I configure `aws_access_key_id` and `aws_secret_access_key` using `gsutil` cli? 

I have tried running `gsutil config -a` but this asks for `google access key id` and not `aws acckess key id`. The options provided [here](https://cloud.google.com/storage/docs/gsutil/commands/config) do not mention how can we set specific properties in the `~/.boto` file

**Comment by starsandskies** [comment]
One of the engineers should weigh in for other/better options, but I think one way you can get where you want to go is by using the [-o top-level flag](https://cloud.google.com/storage/docs/gsutil/addlhelp/TopLevelCommandLineOptions) in each command, which bypasses the need to edit the .boto file.

**Comment by dilipped** [comment]
^ That's correct.
You can also use the env variable 
AWS_ACCESS_KEY_ID=<your key> AWS_SECRET_ACCESS_KEY=<your val> gsutil .....

**Comment by Grandolf49** [comment]
> One of the engineers should weigh in for other/better options, but I think one way you can get where you want to go is by using the [-o top-level flag](https://cloud.google.com/storage/docs/gsutil/addlhelp/TopLevelCommandLineOptions) in each command, which bypasses the need to edit the .boto file.

Thanks a lot! @starsandskies. This approach works great! I was too much focused on trying to do it using `gsutil config` that I overlooked the **[TopLevelCommandLineOptions](https://cloud.google.com/storage/docs/gsutil/addlhelp/TopLevelCommandLineOptions)**

Full command:
```bash
gsutil -o "Credentials:aws_access_key_id=<aws_access_key_id>" \
       -o "Credentials:aws_secret_access_key=<aws_secret_access_key>" \
       cp s3://<bucket>/<key> gs://<bucket>/<key>
```

Although, I found a different workaround and I used that. I came across [this](https://github.com/GoogleCloudPlatform/gsutil/blob/ee2cf7aefef96dcf1d0afd473723cff9fa823418/gslib/utils/boto_util.py#L331), [this](https://github.com/boto/boto/blob/91ba037e54ef521c379263b0ac769c66182527d7/boto/pyami/config.py#L105) and [this](https://github.com/boto/boto/blob/91ba037e54ef521c379263b0ac769c66182527d7/boto/pyami/config.py#L36) and wondered if I could programmatically write those credentials to the `~/.boto` file. So I installed `gsutil~=4.59` in my project and did it this way:

```python
from gslib.vendored.boto.boto.pyami.config import Config

ACCESS_KEY_ID=abcd
SECRET_ACCESS_KEY=efgh

# Configure ~/.boto file
config = Config()
if not config.has_option('Credentials', 'aws_access_key_id'):
    config.save_user_option('Credentials', 'aws_access_key_id', ACCESS_KEY_ID)
    config.save_user_option('Credentials', 'aws_secret_access_key', SECRET_ACCESS_KEY)
```
This creates the `~/.boto` file if it doesn't exist and writes those credentials in the appropriate section.

I know it's not the best way to do it. Instead, I'll use your approach which looks like the correct way to do it.
