### ISSUE TITLE
Latest release broke -m setmeta

### ISSUE THREAD

**Issue by Sytten** [GoogleCloudPlatform/gsutil#1276]
From version 4.61, the command: `gsutil -m setmeta -h 'Cache-Control: public, max-age=3600' gs://$BUCKET/**/*.html` is broken. It used to work on 4.60.
I get a consistent `CommandException: No URLs matched: gs://$BUCKET/**/*.html` but there is an html file at the root of the bucket and it used to work fine:
```
Setting metadata on gs://$BUCKET/index.html...
/ [1/1 objects] 100% Done
Operation completed over 1 objects.
```
I reverted to gcloud 335.0.0 in the meantime.

**Comment by dilipped** [comment]
The fix will be part of the next gsutil release.
