### ISSUE TITLE
Support of Parallel Upload/Download Files to/from GCS with Encryption/Decryption Key Enabled

### ISSUE THREAD

**Issue by hambster** [GoogleCloudPlatform/gsutil#1290]
When enable encryption/description key in .boto config, and upload files to GCS with "-m" CLI switch,
following warning message will be showed:

```
WARNING: Not using parallel composite upload for KMS-encryption. This combination is not currently supported by GCS.
```

do you have plan to support parallel upload/download with encryption/decryption key enabled?
this will help users to leverage GCS as a secure archive storage without relying on external software (for example, CommVault).

**Comment by dilipped** [comment]
Which gsutil version are you using. This has been fixed in v4.62

**Comment by hambster** [comment]
@dilipped thank you for your suggestions.
This works on v4.62.
Thank you.

**Comment by dilipped** [comment]
Thanks for confirming. Closing this.
