### ISSUE TITLE
Add `web open` command to open static pages locally

### ISSUE THREAD

**Issue by ndajr** [GoogleCloudPlatform/gsutil#1306]
Currently the only way to expose static websites is by making the bucket public and creating a load balancer with bucket backend. For my use case my bucket contains an internal page that can't be exposed publicly, I would need something like   security_policy limiting the IPs that can access the bucket or IAP on LB for bucket_service which it's not currently supported.

#### Use case:
Access a static page with a private bucket, relying on IAM authentication.

#### Proposal:
Add `web open` command (example: `gsutil web open gs://<bucket_name>`) which downloads bucket content locally and opens the static content as localhost on the browser.

This would be great because it will allow the team to access the internal page easily while keeping the bucket private, relying on gcloud's IAM authentication. An alternative right now is to deploy an authentication service on Cloud Run as a proxy which is IMO complicating something that should be quite simple.

**Comment by neemiasjnr** [comment]
I am also ok for other places where to implement this logic, like a flag `- - open` to `rsync - R` command

**Comment by neemiasjnr** [comment]
I am also ok for other places where to implement this logic, like a flag `--open` to `rsync - R` command

**Comment by neemiasjnr** [comment]
I am also ok for other places where to implement this logic, like a flag `--open` to `rsync -R` command
