### ISSUE TITLE
Inconsistent Directory Copying Behavior Into Empty Folder on GCP

### ISSUE THREAD

**Issue by minerharry** [GoogleCloudPlatform/gsutil#1486]
When I use gsutil cp with -r with a destination URL that is empty, the behavior is different the first time I run the command versus the second. When the folder has items in it, a new subfolder is created with the same name as the source folder ("test3" in the below example). However, if the output folder is empty, the contents of the source folder are copied into the innermost folder of the destination URL.

Source folder:
![image](https://user-images.githubusercontent.com/35383543/160218912-df8eafb4-085f-48d1-a6a2-d1791a0b71fb.png)

Command: gsutil cp -r "C:\Users\Harrison Truscott\Downloads\test3" gs://optotaxisbucket/test1/test2

When no files in test2 (folders do not exist on the bucket)
![image](https://user-images.githubusercontent.com/35383543/160218985-aa4f83d8-48c4-48c7-9f72-7c910a3353d1.png)

After running the command once (files do exist on the bucket)
![image](https://user-images.githubusercontent.com/35383543/160219023-f2e7d16c-4e97-4b9d-9c9c-44121f3e2e37.png)
![image](https://user-images.githubusercontent.com/35383543/160219026-9b24d3d4-2f69-45b9-90ea-7d9693dff9c2.png)

It doesn't seem to be the command itself, any file in test2 will do it:
before command
![image](https://user-images.githubusercontent.com/35383543/160219059-6d3c3296-a394-418b-b6a2-00660fd58663.png)

after command
![image](https://user-images.githubusercontent.com/35383543/160219068-18b39d7c-bcc3-4444-b500-7fec3e916013.png)

The behavior is identical with/without the -n and -m tags

Is this intended behavior? I couldn't find it in the documentation and it's a real pain if you aren't always sure whether the output directory has files in it

**Comment by dilipped** [comment]
This is intended behavior. It is documented here: https://cloud.google.com/storage/docs/gsutil/commands/cp#how-names-are-constructed

> In addition, the resulting names depend on whether the destination subdirectory exists. For example, if gs://my-bucket/subdir exists as a subdirectory, the following command creates the object gs://my-bucket/subdir/dir2/a/b/c:
> gsutil cp -r dir1/dir2 gs://my-bucket/subdir

**Comment by az-oolloow** [comment]
@dilipped @minerharry While you may consider this an 'intended behaviour' it is incredibly frustrating as there doesn't seem to be a documented way to achieve a CONSISTENT outcome.
