### ISSUE TITLE
gsutil rsync fails to copy nested directories

### ISSUE THREAD

**Issue by AndyMender** [GoogleCloudPlatform/gsutil#1487]
```shell
gsutil -m rsync -d -r gs://my-bucket/top_directory/nested_directory /opt/data/sequences/top_directory/nested_directory
Building synchronization state...
Starting synchronization...
Copying gs://my-bucket/top_directory/nested_directory/...
Skipping attempt to download to filename ending with slash
(/opt/data/sequences/top_directory/nested_directory/). This
typically happens when using gsutil to download from a subdirectory
created by the Cloud Console (https://cloud.google.com/console)
InvalidUrlError: Invalid destination path: /opt/data/sequences/top_directory/nested_directory/
CommandException: 1 files/objects could not be copied/removed.
```

1. Why do directories visible through the Google Cloud Console contain slashes in their names?
2. Why is this common use case not supported?

Oddly enough, this used to work in version 319, but does not in version 378 and possibly versions in-between.

To add more context, in past versions of the Google Cloud SDK, `gsutil` was able to skip the direct reference to the nested_directory and walk down the directory hierarchy to resolve the lowest level directory and copy all of the files from within. Currently, the above error is thrown on the first nested directory with no way to continue.

**Comment by dilipped** [comment]
1. Filenames ending with slash are placeholders for folders created via the UI (https://console.cloud.google.com/)
2. Copying nested dir is supported. The warning is just for the placeholder filename (the one that ends with a slash). See the NOTE here https://cloud.google.com/storage/docs/gsutil/commands/cp#how-names-are-constructed.

Can you try again with a new empty destination directory? My guess is that you didn't see anything else being copied because rsync probably did not have anything else to be copied based on the diff, in other words, `/opt/data/sequences/top_directory/nested_directory/` already had up-to-date files from the source. gsutil skips a file that ends with a slash because there is no way to create such files on a unix-like machine. This should not have any effect on other files in the directory.

**Comment by dilipped** [comment]
`mkdir` should not have any effect. Are you sure the source had files to be copied over? 

I am not able to reproduce this on my end.

```
$ gsutil ls -r gs://my-bucket/slash_test/
gs://my-bucket/slash_test/:
gs://my-bucket/slash_test/f.txt

gs://my-bucket/slash_test/dir/:
gs://my-bucket/slash_test/dir/foo.txt

gs://my-bucket/slash_test/ends_with_slash/:
gs://my-bucket/slash_test/ends_with_slash/
gs://my-bucket/slash_test/ends_with_slash/g.txt


$ gsutil -m rsync -r gs://my-bucket/slash_test ~/temp/junk/slash_test_2/
Building synchronization state...
Starting synchronization...
Copying gs://my-bucket/slash_test/dir/foo.txt...
Copying gs://my-bucket/slash_test/ends_with_slash/...
Skipping attempt to download to filename ending with slash (/redacted/temp/junk/slash_test_2/ends_with_slash/). This
typically happens when using gsutil to download from a subdirectory
created by the Cloud Console (https://cloud.google.com/console)
InvalidUrlError: Invalid destination path: /redacted/temp/junk/slash_test_2/ends_with_slash/
Copying gs://my-bucket/slash_test/ends_with_slash/g.txt...
Copying gs://my-bucket/slash_test/f.txt...
CommandException: 1 files/objects could not be copied/removed.


$ tree ~/temp/junk/slash_test_2/
/redacted/temp/junk/slash_test_2/
├── dir
│   └── foo.txt
├── ends_with_slash
│   └── g.txt
└── f.txt
```

As you can see, even after the error was logged for the filename ending with slash, the copying was continued for other files.

**Comment by dilipped** [comment]
Yes, the behavior was changed to throw an error because it is not possible for gsutil to know if this was a mistake from the user or if this was because of a placeholder object (object ending with slash added by the UI to represent folders).

**Comment by AndyMender** [comment]
Okay, that explains it and works as intended, as you described. I'm closing the issue as there is nothing further to do.

Big thanks for the clear explanation and for help! :)

**Comment by MatthieuStigler** [comment]
Sorry, being very confused, especially with the error message `InvalidUrlError: Invalid destination path: /redacted/temp/junk/slash_test_2/ends_with_slash/` 

Can you comment on this? The destination path is valid, yet declared unvalid by `gsutil` ?
