### ISSUE TITLE
gsutil regex - behaviour change (v5.17)

### ISSUE THREAD

**Issue by b-becker-k** [GoogleCloudPlatform/gsutil#1637]
Hi,
We use gsutil with the -x argument and a regex to upload code to a gcloud storage bucket. This was working fine all the way to 5.16, and broke with the 5.17 release.

The full command, note regex after -x argument:
`gsutil -m -q rsync -c -dr -x '(?!src/|tests/|remote_debug|project_root_folder_marker.txt$)|(src/project/node_modules/)|(.*__pycache__.*)|(.*pyc$)|(.*gstmp$)' /home/circleci/project gs://<bucket>/`

In the past this would have uploaded these example files
```
remote_debug/
tests/
project_root_folder_marker.txt
src/project/test.py
```
but left out these
```
src/project/node_modules/test.json
src/project/__pycache__/test.py
```
It currently only uploads `remote_debug` and `project_root_folder_marker.txt`

I guess this is likely to be linked to the regex fix applied to 5.17

**Comment by b-becker-k** [comment]
I guess we will have to rewrite that regex to avoid that behaviour then, thanks for taking the time to look at the issue.

**Comment by thomasmaclean** [comment]
The change introduced in 5.17 is effectively a breaking change for anyone using `-x` with negative lookahead, as that flow presupposes you're "including" from a list of objects to be excluded, only now that list of objects is shorter because entire directories are being skipped rather than processing being completed object-by-object.

**Comment by gh2k** [comment]
> breaking change

Yeah, fwiw this broke our CI and caused us to ship a build without javascript assets on our CDN. (Lesson learned: Don't use [gcr.io/cloud-builders/](http://gcr.io/cloud-builders/gsutil)-related tools in production workflows without pinning the version in `couldbuild.yml`) :-)

Thanks for the fix.

**Comment by thomasmaclean** [comment]
Very sorry for that! We usually take great pains not to introduce breaking changes like this. We've added additional test coverage to ensure these behaviors are well-documented and don't cause regression for people in the future.
