### ISSUE TITLE
`gsutil -m` breaks "Reauthentication required"

### ISSUE THREAD

**Issue by thirdpwais3** [GoogleCloudPlatform/gsutil#1639]
Let's suppose you want to copy a bunch of files to gcloud.  So you `gsutil cp -r my_local_dir gs://my-bucket/my_path`.  If you have  a lot of files, `gsutil` will print a big message telling you that you should actually be doing `gsutil -m cp` because of some such faster transfers etc.  (Note that `aws` will just use multi-upload mode automatically without nagging you).  Anyways, so then you get into a habit of using `gsutil -m cp` all the time because otherwise `gsutil` will nag you.  

Ok so one day log in and now do a `gsutil -m cp -r my_local_dir gs://my-bucket/my_path`.  Since it's been a day and your authorization needs to be refreshed, gsutil will print `"Reauthentication required"` and ask you for a password.  But since you did `gsutil -m cp`, the `gsutil` command clobbers itself and doesn't let you enter a password, instead filling your terminal with errors for each file, and leaving you wondering what went wrong.  

So it turns out if you just `gsutil cp -r my_local_dir gs://my-bucket/my_path`  (no `-m`) then you'll get single-threaded experience and `"Reauthentication required"` re-auth flow will work as expected.

But there are two issues here:
1) (this issue) `gsutil -m` will break the "Reauthentication required" flow, and it's really confusing what the user should do to fix.
2) (some future issue) `gsutil -m` should probably be the default, and not nag w/out it; `aws` just does the right thing and does not nag.

**Comment by NickGoog** [comment]
What type of credentials are you using that require reauth? Trying to reproduce.

Did this start the day you posted 12/15/22?

In that case, this change was part of the last update (based on change log dates): https://github.com/GoogleCloudPlatform/gsutil/pull/1617

The reauth flow takes place mostly inside the dependency package so not sure how much we can do here.

**Comment by thirdpwais3** [comment]
@NickGoog this issue has been happening forever

@thomasmaclean is gsutil just deprecated then?  i guess i should move to `gcloud storage` ?

**Comment by NickGoog** [comment]
Hi, can you provide a stack trace by using the `-d` flag? `gsutil -d ...`? Be sure to remove any personal information before posting.

Migration to `gcloud storage` is encouraged by we're still missing some things in the new CLI like `rsync` and XML support.

**Comment by thirdpwais3** [comment]
`This command is available in one or more alternate release tracks.  Try:
  gcloud alpha storage`

please see above, gcloud storage is a non-starter

@NickGoog do `gsutil -m cp -r xxx yyy` with a logged-out session it's really not hard to reproduce

**Comment by NickGoog** [comment]
That's interesting. The `cp` command is out of alpha. Maybe you're running an old gcloud version?
http://cloud/sdk/gcloud/reference/storage/cp

I think you might need an organization policy or two-factor auth to get the reauth prompts. When I logout, I just get `AccessDeniedException: 403 Access denied.`

A debug log would be helpful, but I'll investigate. Most of this logic takes place in our dependencies, so it might take while.

**Comment by NickGoog** [comment]
Reproduced after navigating some internal auth infra

**Comment by thomasmaclean** [comment]
This (and #1663) have been fixed as of gsutil v5.19.
