### ISSUE TITLE
Checksum validation with cloud-to-cloud (GCS-GCS) rsync/copy

### ISSUE THREAD

**Issue by benbuckman** [GoogleCloudPlatform/gsutil#1697]
Hello. We are using `gsutil -m rsync -r` to copy hundreds of files comprising hundreds of GBs from one GCS location to another GCS location. We are trying to understand the guarantees GCS and `gsutil` provide about file transfer integrity, i.e. are the destination files guaranteed to be identical to the source files, and will `gsutil` fail in a clear way if there is a mismatch.

The documentation indicates that this should be reliable: https://cloud.google.com/storage/docs/hashes-etags#cli
However, reading that closely, "data copied to or from a Cloud Storage bucket is validated," suggests it's only for _local to cloud_ transfers and not cloud to cloud.

I ran `gsutil` from source and stepped through it in a debugger, with `rsync` and `cp`. I could not find any code path that does checksum validation on cloud-to-cloud transfers. If I modified the code to make the `src_obj_metadata` checksums clearly wrong, so they'd have to mismatch, I saw no errors.
I see in the code 2 places with `raise HashMismatchException`: in [`_CheckCloudHashes`](https://github.com/GoogleCloudPlatform/gsutil/blob/203a1a2442dec59c6e69756e2011a4df6dd9ec4d/gslib/utils/copy_helper.py#L864) for _daisy-chain_ mode (which first downloads files to local disk), and in [`_CheckHashes`](https://github.com/GoogleCloudPlatform/gsutil/blob/203a1a2442dec59c6e69756e2011a4df6dd9ec4d/gslib/utils/copy_helper.py/#L926) which "compares cloud digest to _local_ digest.” Neither of these is for the default cloud-to-cloud mode.

It's entirely possible that this behavior is implemented in GCS's backend API, and not in the `gsutil` client code at all. But I cannot find any documentation about this. I also don't know how to test this.

Can you clarify the behavior and guarantees of file integrity with cloud-to-cloud transfers?
Thank you!

**Comment by starsandskies** [comment]
One of the gsutil engineers should confirm, but I believe that wording is accurate and applies to GCS-to-GCS copies: as long as at least one of the source or destination is a GCS bucket, I believe validation occurs. The statement is there to make it clear that validation *does not necessarily occur* when using gsutil rsync outside of GCS. For example, using it to transfer from one local directory to another.

This interpretation also aligns with the first bullet point in the "Validation" section above (https://cloud.google.com/storage/docs/hashes-etags#validation)

**Comment by benbuckman** [comment]
Thank you!!
