### ISSUE TITLE
Removal of e-Tugra root certificate

### ISSUE THREAD

**Issue by nagaripratap** [GoogleCloudPlatform/gsutil#1736]
Description
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).

Informations

Manifest Path : [gslib/data/cacerts.txt](https://github.com/GoogleCloudPlatform/gsutil/blob/3656d7ef1564d99e173246a6ebebab0af09e4d5b/gslib/data/cacerts.txt#L2040)

**Comment by NickGoog** [comment]
Updated gsutil and dependencies
