### ISSUE TITLE
New User setup issue - hundreds of spawned python.exe

### ISSUE THREAD

**Issue by ochawkeye** [GoogleCloudPlatform/gsutil#175]
Windows 7, Python 2.7 (32-bit) environment

After unsuccessfully trying to `pip install gsutil` (error reported as `Could not find 'openssl.exe'`) I completed the following steps to install:

- Downloaded and unzipped gsutil
- Ran `python setup.py install` from `gsutil/gsutil` folder
- Tried running `gsutil` from command line
- System grinds to a halt.  Opening task manager shows that hundreds (currently 250+) of `python.exe` processes have spawned
![image](https://f.cloud.github.com/assets/2996205/1716649/f410caa8-61c3-11e3-9f98-7e2637ab1103.png)

Had this issue immediately after install, so tried rebooting.  Same results with fresh reboot.  

Is this an unsupported method for installation or should I be turning rocks somewhere else to get this working?

**Comment by thobrla** [comment]
Please reopen if jterrace's suggestion did not work for you.
