### ISSUE TITLE
gsutil 5.31 doesn't work with Python 3.12.7 in alpine 

### ISSUE THREAD

**Issue by cHiv0rz** [GoogleCloudPlatform/gsutil#1808]
# Context

`Python 3.12.7` is the default python version in `alpine 3:20`, and it breaks `gsutil` on its version `5.31`. Looking into the code, it seems 3 weeks ago [this check](https://github.com/GoogleCloudPlatform/gsutil/commit/c8e270933ad925ab30bba63b23e9bf7410ed6b25) was added.

Why is the incompatibility issue on this version? Because `gsutil 5.30` works fine with `Python 3.12.6`

Thanks

**Comment by NachE** [comment]
It looks like gsutil is incompatible with Python 3.12 due to the removal of the imp module, as described here: https://issuetracker.google.com/issues/303737178. Python 3.12.6 shouldn't work either, since the imp module was removed starting with Python 3.12.0.

**Comment by cHiv0rz** [comment]
"Shouldn't" but it works, because I actually using it in version 5.30 with `Python 3.12.6`, at least for "normal" usage like list files, copy, move, etc. What specific function is failing? maybe we can throw the error only on that part, and not break the whole utility?

**Comment by cHiv0rz** [comment]
In addition, I found [this meta issue](https://github.com/python/cpython/issues/97850#issuecomment-1533209627)  which says the problem with Python 3.12 on `gsutil` is fixed here: https://github.com/GoogleCloudPlatform/gsutil/issues/1695

So sorry If i'm missing something, but still don't understand the check

**Comment by ElijahLynn** [comment]
Just ran `gcloud components update` at the request of the prompt today and now getting:

```
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
	1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
```

Debugging now. But just wanted to pass on feedback this is frustrating, as I'm doing a time sensitive task and now `gsutil` doesn't work for my task.

**Comment by NachE** [comment]
My fault while testing 😅

**Comment by joshheinrichs-shopify** [comment]
the gsutil wrapper that `google-cloud-sdk` packages thinks that 3.12 works, so if `python` or `python3` points to 3.12, it'll use 3.12 and then explode. it won't go digging for `python3.11` even if it's installed. it seems to treat 3.12 as a last resort, but doesn't consider `python3` / `python` may be pointing at 3.12:
```
CLOUDSDK_PYTHON=$(order_python python3 python python3.11 python3.10 python3.9 python3.8 python3.12)
```

**Comment by bennett39** [comment]
For anyone who reached this page looking for a quick fix, reverting the version of my `gcloud components` got me running again on python 3.12:

```shell
gcloud components update --version 494.0.0
```

**Comment by diwu-sf** [comment]
`export CLOUDSDK_PYTHON=python3.11` seems like a better workaround until they officially fix it to support 3.12, and can still run on latest gcloud components

**Comment by dmitshur** [comment]
The comment at https://github.com/GoogleCloudPlatform/gsutil/issues/1776#issuecomment-2538018415 says that gsutil version 5.32 and above supports Python 3.12.

**Comment by cHiv0rz** [comment]
Thanks! I confirmed that `gsutil` 5.32 is working fine with Python 3.12

**Comment by briffle** [comment]
I see this issue is closed, but we are still geting the same message when deploying Google Cloud SDK 5.0.4 to Alpine 3.21.0 .  This should have gstuil 5.33 according to the release notes.  Should we just ignore this error?
