### ISSUE TITLE
woff mime type

### ISSUE THREAD

**Issue by pkra** [GoogleCloudPlatform/gsutil#183]
By default, WOFF files are stored with `application/x-font-woff`. This works but throws warnings in some browsers.  

The [WOFF spec](http://www.w3.org/TR/WOFF/#appendix-b) specifies `application/font-woff`.

For reference, http://stackoverflow.com/questions/3594823/mime-type-for-woff-fonts

**Comment by rayfoss** [comment]
@mfschwartz There is an API for setting global default ACL's... why isn't there one for setting global default mime for specified extensions... Like VTT or Woff

Seems like basic important functionality for static file hosting
