### ISSUE TITLE
OpenSSL not fixed 

### ISSUE THREAD

**Issue by sam-harrison-1** [GoogleCloudPlatform/gsutil#1831]
$ gsutil version -l
gsutil version: 5.32

$ gsutil -m rsync -R static/ gs://project
Building synchronization state...
Caught non-retryable exception while listing gs:/project/: module 'OpenSSL.crypto' has no attribute 'sign'
CommandException: Caught non-retryable exception - aborting rsync
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1

Using gsutil as a part of google/cloud-sdk:alpine

**Comment by sameer-google** [comment]
Alpine images is rolled back to version `3.19` in `504.0.0-alpine`. So the issue with `OpenSSL.crypto` should be resolved now.

Reference: [cloud-sdk-docker/issues/497](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/497)
