### ISSUE TITLE
hard coded single boto version in setup.py

### ISSUE THREAD

**Issue by schwehr** [GoogleCloudPlatform/gsutil#187]
This line in setup.py:
```
'boto==2.22.1',
```
hard codes a single version of boto that must be installed.  This doesn't play nice with others.  Can it be changed to boto>=2.22.1 and let the end user run "python setup.py test" to verify things?

**Comment by thobrla** [comment]
Sorry to cause the extra work for you, but this isn't something we can safely fix without risking breaks elsewhere.  Closing.
