### ISSUE TITLE
gsutil fails with "global name 'SignedJwtAssertionCredentials' is not defined."

### ISSUE THREAD

**Issue by vishalagawane** [GoogleCloudPlatform/gsutil#195]
# ./gsutil update
Checking for software update...
Failure: global name 'SignedJwtAssertionCredentials' is not defined.

# ./gsutil ls gs://
Failure: global name 'SignedJwtAssertionCredentials' is not defined.

# /usr/bin/env python --version
Python 2.7.6

Is this an issue with my particular installation?

**Comment by rlambrechts** [comment]
Exact the same issue here after gcloud auth activate-service-account as described by ccampbell.

I was trying to add a service account to use gcloud compute.
