### ISSUE TITLE
Unable to upload large file

### ISSUE THREAD

**Issue by gertvs** [GoogleCloudPlatform/gsutil#196]
I am having serious problems uploading a file using gsutil 3.42, which is the latest version I can get. I created a new bucket before giving it a try with a fresh file. Despite of it being a new file it seems that the upload is being interrupted indefinitely.

Here's my command line and subsequent output:
 ~/dev/java/globespot> gsutil cp ./globespot_storage_2014-04-18_17-24UTC.sql.gz gs://globespot-02
Copying file://./globespot_storage_2014-04-18_17-24UTC.sql.gz [Content-Type=application/x-sql]...
Catching up hash digest(s) for resumed upload
Catching up hash digest(s) for resumed upload
Catching up hash digest(s) for resumed upload
Unable to find the server at accounts.google.com
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload                                                                                                                                                                        
Catching up hash digest(s) for resumed upload
Catching up hash digest(s) for resumed upload
Catching up hash digest(s) for resumed upload
Uploading: 218.9 MB/218.9 MB     
Uploading: 218.9 MB/218.9 MB     
Catching up hash digest(s) for resumed upload
Uploading: 218.9 MB/218.9 MB    
Uploading: 218.9 MB/218.9 MB    
... Eternal repetition of the same output.

The upload itself started many times all over again, and it keeps producing temp folders and files as you can see here (I marked the file public):
http://storage.googleapis.com/globespot-02/2903529300/gsutil/tmp/parallel_composite_uploads/for_details_see/gsutil_help_cp/a599dbe1a34ea68ef3ba017db65bf1ea_10

I am using Ubuntu linux: uname -a: Linux MyBox 3.2.0-58-generic-pae #88-Ubuntu SMP Tue Dec 3 18:00:02 UTC 2013 i686 athlon i386 GNU/Linux

Gert

**Comment by thobrla** [comment]
Please reopen if you still see this issue using gsutil 4.x
