### ISSUE TITLE
rsync fails on large files

### ISSUE THREAD

**Issue by neilkatin** [GoogleCloudPlatform/gsutil#205]
I've been trying to get rsync to run, from a directory to google cloud.

It works fine on small files.

On large files I get this error:

```
 gsutil rsync /mnt/db-backup/gsutil-backup/2014-06-05/ gs://backup00/2014-06-05/
Building synchronization state...
Starting synchronization
Copying file:///mnt/db-backup/gsutil-backup/2014-06-05/backup-20140604_210001_mysql.tar.gz [Content-Type=application/x-tar]...
'RsyncCommand' object has no attribute 'copy_failure_count'
```

I did some investigation; the problem is in copy_helper.py _DoParallelCompositeUpload.

There is this statement:

```
  cp_results = command_obj.Apply(
      _PerformParallelUploadFileToObject, components_to_upload,
      copy_exception_handler, ('copy_failure_count', 'total_bytes_transferred'),
      arg_checker=gslib.command.DummyArgChecker,
      parallel_operations_override=True, should_return_results=True)
```

This code appears to be shared between cp and rsync.

The problem is: the cp code defines copy_failure_count; rsync does not (hence the failure).

It looks like the same problem exists for total_bytes_transferred, which also only is defined in cp.py.

**Comment by tispratik** [comment]
Is 4.3 coming out soon?

**Comment by thobrla** [comment]
4.3 was released in June of 2014.

**Comment by tispratik** [comment]
Seems like it was not released to pip https://pypi.python.org/pypi/gsutil

**Comment by thobrla** [comment]
In gsutil's versioning scheme, you compare the version number after the decimal in its entirety.  So 4.3 is major version 4 minor version 3, 4.26 is major version 4 minor version 26, and 4.3 < 4.26 < 4.30.

**Comment by tispratik** [comment]
Thanks for the versioning clarification. I think i am facing the same "hanging" issue while uploading to s3 on a cp command.

**Comment by tispratik** [comment]
```
/usr/local/bin/gsutil -o GSUtil:parallel_composite_upload_threshold=10M -D cp gs://google-bucket/myfile.gz s3://s3-bucket/mydir
```

**Comment by thobrla** [comment]
That's probably a different issue than this one - could you open a new issue and include the output of `gsutil version -l`?

**Comment by tispratik** [comment]
Sure, thanks! Its here https://github.com/GoogleCloudPlatform/gsutil/issues/434
