### ISSUE TITLE
invalid header specified

### ISSUE THREAD

**Issue by dmitrijn** [GoogleCloudPlatform/gsutil#208]
branch 4+ doesn't support header: x-amz-server-side-encryption
there is no information in the release notes about deprecated headers https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md

executed command for upload:
`````
gsutil -h 'x-amz-server-side-encryption:AES256' -h 'Cache-Control:no-cache' cp filename s3://bucketname
`````

exception:
`````
ArgumentException: Invalid header specifed: x-amz-server-side-encryption:AES256
`````

in version 3.42 this header is supported and all is fine with upload.

**Comment by thobrla** [comment]
Closing this as the key commands now support it.  If there are still scenarios that are not working, please comment and I'll reopen.
