### ISSUE TITLE
Import 

### ISSUE THREAD

**Issue by natestockham** [GoogleCloudPlatform/gsutil#232]
I installed gsutil tools as described here in the Google docs : 

https://cloud.google.com/storage/docs/gsutil_install#install_pypi

and when I tried to run this in python (copied directed from the google website):

from boto import storage_uri
from gslib.third_party.oauth2_plugin import oauth2_plugin

I got this error

ImportIssue : gslib.third_party.oauth2_plugin import oauth2_plugin is not a module

I looked inside the file structure and indeed "oauth2_plugin" is missing from the gslib.third_party file structure. Has there been an intentional change to the gsutil and the Google website has not been updated? Or, is there something else going on?

Thanks!

**Comment by thobrla** [comment]
This is fixed in the documentation now.
