### ISSUE TITLE
Cannot execute a sequential gsutil in windows batch file

### ISSUE THREAD

**Issue by zelon** [GoogleCloudPlatform/gsutil#233]
I'm using gsutil to backup my datas in windows. And my batch file is like below:

gsutil cp -R a gs://zelon-test/
gsutil cp -R b gs://zelon-test/

But only the first command "gsutil cp -R a gs://zelon-test/" is executed. Second command is not executed at all.

**Comment by paracha3** [comment]
Thanks. This has helped me too.

**Comment by MartyMacGyver** [comment]
I just stumbled upon this problem myself (I run several gcloud commands to transfer data periodically). In your batch file be sure to preface `gcloud` or `gsutil` or such with `call`, thus:

    call gcloud compute copy-files foobarhost:/home/foobar/blah /my/local/folder --zone my-compute-zone
    call gcloud compute copy-files foobarhost:/home/foobar/blah /my/local/folder --zone my-compute-zone
    ...etc...

Using `call` prevents the batch from exiting as soon as its child batch exits. You can use %ERRORLEVEL% to check the result of the called command (the GCP scripts set this appropriately). See also http://ss64.com/nt/call.html

**Comment by jackRoark** [comment]
THAT is the answer!  Thank you Marty! 

"There always seems to be a way to fix things." - MacGyver

**Comment by juanda2222** [comment]
i have the same exact problem but when i use the full paths, i am using the paths: "C:\Python27\python.exe" "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py" cp %myfile.txt% gs://%myBucket%/%folder%/ getting the exception:

ServiceException: 401 Anonymous caller does not have storage.objects.create access to %myBucket%/%folder%/%myfile.txt%

this does not happen when i use the gsutil comand, Any recomendation?

**Comment by juanda2222** [comment]
> i have the same exact problem but when i use the full paths, i am using the paths: "C:\Python27\python.exe" "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py" cp %myfile.txt% gs://%myBucket%/%folder%/ getting the exception:
> 
> ServiceException: 401 Anonymous caller does not have storage.objects.create access to %myBucket%/%folder%/%myfile.txt%
> 
> this does not happen when i use the gsutil comand, Any recomendation?

UPDATE:

i manage to work around the problem creating a new process for every operation as child's of the   original batch file process using the call comand. therefore the comands inside the batch files now look something like this:

** call cmd /c gsutil cp %file_1% gs://%bucket%/%folder%/ **
** call cmd /c gsutil cp %file_2% gs://%bucket%/%folder%/ **

note that the /c allows the original batch process to wait for the other sub-process so all the operation looks just as it should be
