### ISSUE TITLE
"Could not find Python executable"

### ISSUE THREAD

**Issue by carlhoerberg** [GoogleCloudPlatform/gsutil#236]
When running gsutil without a pty/tty (ubuntu 14.04 on gce) we get "Could not find Python executable." 

Solved by exporting `CLOUDSDK_PYTHON`, which can be done by changing 
line 71 in  `/usr/lib/google-cloud-sdk/bin/gsutil` to

```
export CLOUDSDK_ROOT_DIR CLOUDSDK_PYTHON CLOUDSDK_PYTHON_ARGS
```

**Comment by thobrla** [comment]
Moving to GoogleCloudPlatform/gcloud#26 as this fix needs to happen in gcloud.

**Comment by thobrla** [comment]
carlhoerberg, if you could take a look at the gcloud issue (and respond to the gcloud maintainer's question) that would be appreciated.

**Comment by carlhoerberg** [comment]
seems to be working now.. upgraded to the latest gsutil

**Comment by scottkof** [comment]
I'm having this exact problem today, also when PostgreSQL executes `gsutil` as part of a WAL archive command. __carlhoeberg__'s solution to modify `/usr/lib/google-cloud-sdk/bin/gsutil` (now line 111) so it also exports CLOUDSDK_PYTHON solves the problem.

Is this fix something that can get into the master branch?

**Comment by houglum** [comment]
That isn't anything that can be changed in gsutil's code; that's an issue with the Cloud SDK wrapper script (`<gcloud-sdk-root>/bin/gsutil` is a wrapper that eventually invokes the "real" gsutil, with some additional arguments and environment setup steps beforehand).  Looking at `<gcloud-sdk-root>/bin/bootstrapping/bootstrapping.py`, in the method `_GetToolEnv()`, it does indeed set CLOUDSDK_PYTHON in the environment variables it uses to launch the specified tool (via `_ExecuteTool()`).  As mentioned in #402, is it possible you don't have a "python2" executable in your PATH, or that "python" resolves to a python3 binary?

**Comment by scottkof** [comment]
PostgreSQL runs its archive command with a stripped-down environment so no, python isn't in the PATH.

As I mentioned, __carlhoeberg__'s solution to modify the wrapper script so it exports CLOUDSDK_PYTHON solves this problem. It would be nice if this change gets into the code to allow gsutil to work out-of-the-box in environments like this one.

**Comment by houglum** [comment]
What would it export for the value of CLOUDSDK_PYTHON?  You're essentially invoking a shell script in an environment without any "python" executable that can be found via standard discoverability methods, e.g. the PATH variable.

gcloud bundles its own version of Python on Windows, where it makes more sense to do so (this is where gcloud explicitly setting CLOUDSDK_PYTHON would make sense). But on other environments, it uses the available system installation of Python.  You'll have to make your Python executable discoverable to gcloud (either via setting CLOUDSDK_PYTHON or adding it to your PATH before running the gsutil wrapper script) for that script to work.
