### ISSUE TITLE
gsutil doesn't work, when executed from drive D, on Windows

### ISSUE THREAD

**Issue by marcdp** [GoogleCloudPlatform/gsutil#238]
I install "gcloud" + "Phyton" + "gsutil" in drive C, but if i execute "gsutil" from drive D, a 401 error appears. Example:

**C:\gsutil ls**       <----- this works OK (using ls or any other command)
_gs://myexisintbucket1/_
_gs://myexisintbucket2/_
_gs://myexisintbucket3/_
_..._
_gs://myexisintbucketN/_

**D:\gsutil ls**      <--- if i execute the command from D, an ERROR appears (using ls or any other command)
_ERROR 1122 23:32:26.232000 http_wrapper.py] Response returned status 401, retrying_
_ERROR 1122 23:32:26.247000 http_wrapper.py] Retrying request to url ..._
_..._

The same problem appears on Windows 7 and Windosw 8.1

**The SDK version is:**
Google Cloud SDK 0.9.37
bq 2.0.18
bq-win 2.0.18
compute 2014.11.18
core 2014.11.18
core-win 2014.10.14
dns 2014.11.06
gcutil 1.16.5
gcutil-win 1.16.5
gsutil 4.6
gsutil-win 4.6
preview 2014.11.18
sql 2014.11.18
windows-ssh-tools 2014.07.15

Thank you!!

**Comment by thobrla** [comment]
Pull request https://github.com/boto/boto/pull/2823 is out to fix this, awaiting acceptance.

**Comment by thobrla** [comment]
This was fixed + merged into gsutil 4.13.
