### ISSUE TITLE
rb usage command string incorrect

### ISSUE THREAD

**Issue by tshauck** [GoogleCloudPlatform/gsutil#239]
Current help string is: `gsutil [-f] rb url...`, but should be `gsutil rb [-f] url...`.  Pretty minor, but wanted to file a ticket in to hopefully reduce duplication.  Code review here: https://codereview.appspot.com/187550043/.

**Comment by thobrla** [comment]
Fixed with https://github.com/GoogleCloudPlatform/gsutil/commit/59b8679d204ad7fcc585b014bec40b03bcec2881, will be included in 4.8
