### ISSUE TITLE
Permissions are wrong when installed via pip on Linux

### ISSUE THREAD

**Issue by rjogrady** [GoogleCloudPlatform/gsutil#243]
The files in /usr/local/lib/python2.7/dist-packages/gsutil-4.7-py2.7.egg/EGG-INFO/ are all mode 640. So if you installed gsutil via
$ sudo pip install gsutil

gsutil will fail to load with:

$gsutil
<...>
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/gsutil-4.7-py2.7.egg/EGG-INFO/requires.txt'

I think the contents of EGG-INFO/* should be 644.

**Comment by jterrace** [comment]
This is not part of our configuration. It is controlled by your umask.

Your umask is probably set to 0027. Set it to something like 0022 before you run the install command and the script will be installed appropriately.
