### ISSUE TITLE
gsutil can't use IAM instance credentials when accsessing S3.

### ISSUE THREAD

**Issue by tomprince** [GoogleCloudPlatform/gsutil#247]
Boto supports using IAM credentials. It appears that gsutil somehow disables this.

**Comment by thobrla** [comment]
Thanks for the issue report. gsutil was implemented by Google primarily in support of Google Cloud Storage. We're open to accepting code submissions in support of S3-specific features (as long as those changes don't make gsutil work worse in some way for GCS users), but we are not going to author such changes ourselves.

gsutil doesn't go out of its way to disable IAM features in boto, but without more information about the failure mode it's hard to say how much work it would be to fix this.
