### ISSUE TITLE
gsutil setmeta can't set x-amz-website-redirect-location

### ISSUE THREAD

**Issue by tomprince** [GoogleCloudPlatform/gsutil#248]
Or other `x-amz` headers that aren't `x-amz-meta-`.

**Comment by thobrla** [comment]
Thanks for the issue report.  gsutil was implemented by Google primarily in support of Google Cloud Storage.  We're open to accepting code submissions in support of S3-specific features (as long as those changes don't make gsutil work worse in some way for GCS users), but we are not going to author such changes ourselves.

In this case, authoring a change to allow gsutil setmeta to accept x-amz headers would be fairly straightforward, but other commands like gsutil ls -L wouldn't be able to display these headers without more legwork.
