### ISSUE TITLE
Are gsutil updates backward-compatible?

### ISSUE THREAD

**Issue by roshniphilip** [GoogleCloudPlatform/gsutil#254]
Hi,

I am using gsutil to download files from google cloud storage.This is being called through a unix script.To be more specific,I am using 'gsutil cp' to copy the files from cloud into my unix box. I am aware that gsutil,when called through scripts, does not get automatically updated to the latest version.But if I update gsutil manually,is there a chance of my script failing? In other words,is gsutil backward compatible?

Thanks,
Roshni

**Comment by mfschwartz** [comment]
Hi Roshni,

We make backwards incompatible changes in major version releases (e.g., from gsutil 3.x to gsutil 4). Minor version updates are backwards compatible.

Mike

**Comment by roshniphilip** [comment]
Thanks Mike.Could you tell me what kind of impact it would have on a simple gsutil cp/ls command? Would we be able to copy files in the same manner as the older version if there is a major version change?

**Comment by mfschwartz** [comment]
Roshni,

The impact is documented in the release notes: https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md

Mike
