### ISSUE TITLE
Feature request: exclude sockets

### ISSUE THREAD

**Issue by j33433** [GoogleCloudPlatform/gsutil#262]
It would be nice to be able to exclude sockets in the way that symbolic links can be excluded. Currently, there appears to be no way to handle sockets. The rsync command aborts.

**Comment by thobrla** [comment]
Thanks for the report.  It would be nice to handle the exception.  Can you post an exception stack trace (captured with gsutil -D rsync)?

**Comment by thobrla** [comment]
Another question: are you trying to rsync your root directory?  It's unlikely we'll add skip logic for all possible copy errors, as what should be skipped is OS-specific.

**Comment by j33433** [comment]
I'm not syncing root. I happen to have a set of rdiff-backup outputs that I want to push offsite. I'm willing to drop all special files, but I don't want to do it by modifying the rdiff-backup sets.

Will post a trace soon.

**Comment by j33433** [comment]
gsutil/4.11

DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/home/boomerang/gs/gsutil/gslib/__main__.py", line 524, in _RunNamedCommandAndHandleExceptions
        debug_level, parallel_operations)
      File "/home/boomerang/gs/gsutil/gslib/command_runner.py", line 272, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/home/boomerang/gs/gsutil/gslib/commands/rsync.py", line 967, in RunCommand
        fail_on_error=True)
      File "/home/boomerang/gs/gsutil/gslib/command.py", line 1148, in Apply
        arg_checker, should_return_results, fail_on_error)
      File "/home/boomerang/gs/gsutil/gslib/command.py", line 1219, in _SequentialApply
        worker_thread.PerformTask(task, self)
      File "/home/boomerang/gs/gsutil/gslib/command.py", line 1654, in PerformTask
        results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
      File "/home/boomerang/gs/gsutil/gslib/commands/rsync.py", line 866, in _RsyncFunc
        headers=cls.headers)
      File "/home/boomerang/gs/gsutil/gslib/copy_helper.py", line 2301, in PerformCopy
        e.message))
    CommandException: CommandException: Error opening file "file://test/socket": .
    
Caught ^C - exiting
Caught ^C - exiting

**Comment by mfschwartz** [comment]
Hi - I'm wondering if this is happening because you have a program that creates sockets in a data directory. Would it be possible to change your program instead to create sockets in /tmp? That's pretty common practice, and if you do that there's no issue with needing special handling to skip sockets.

In general we don't like to add features to gsutil that are only of use to a small fraction of users, which I think is the case here. Would writing sockets to /tmp work for you?

**Comment by j33433** [comment]
I don't have control over the systems that the backups come from. I think an ignore-special-file option would solve the problem, where special file is device node, socket, fifo or anything the platform has that doesn't translate to cloud storage.

I could try building up something to pass to the -x option that contains a list of all of the special files in python regex form...

**Comment by mfschwartz** [comment]
Have you seen the gsutil rsync -x option?
https://cloud.google.com/storage/docs/gsutil/commands/rsync#options

**Comment by mfschwartz** [comment]
How hard would it be to use gsutil rsync -x to build an exclusion list for these files?
Are there a large number of them (like hundreds or thousands)?

**Comment by j33433** [comment]
I used the following to generate the -x argument and it appears to work:

import os
import stat
import re
import sys

def find_special(path):
    results = []

    for root, dirs, files in os.walk(path):
        for name in files:
            full = os.path.join(root, name)
            short = full[len(path):]
            
            if not os.path.islink(full):
                mode = os.stat(full).st_mode
                 
                if not (stat.S_ISDIR(mode) or stat.S_ISREG(mode)):  
                    results.append('^' + re.escape(short) + '$')

    return results
                
results = find_special(sys.argv[1]) 
expr = "|".join(results)
print ('\'' + expr + '\'')

**Comment by mfschwartz** [comment]
I'm glad to hear that works for you. I'm closing this issue.
