### ISSUE TITLE
Recursive upload is inconsistent

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/gsutil#274]
With `gsutil cp -R ./bar gs://<bucket>/foo` I can see that
 1. it creates `foo` with files from `bar` on the first run
 2. on the second run it creates `bar` under `foo` with files there

**Comment by jterrace** [comment]
This is consistent with unix behavior.

````
$ mkdir bar
$ touch bar/1 bar/2
$ tree bar
bar
├── 1
└── 2
$ cp -R ./bar foo
$ tree foo
foo
├── 1
└── 2
$ cp -R ./bar foo
$ tree foo
foo
├── 1
├── 2
└── bar
    ├── 1
    └── 2
````

The cp command has different behavior depending on whether the destination directory exists or not.

**Comment by errordeveloper** [comment]
Yes, but on `cp` respects leading slash in the source path (at least the BSD version), while `gsutil cp` doesn't.
```
> rm -rf foo
> cp -R ./bar/ foo
> cp -R ./bar/ foo
> ls foo/
1 2
```
Try for yourself...

**Comment by jterrace** [comment]
Not on my machine:

````
$ rm -rf foo
$ cp -R ./bar/ foo
$ tree foo
foo
├── 1
└── 2
$ cp -R ./bar/ foo
$ tree foo
foo
├── 1
├── 2
└── bar
    ├── 1
    └── 2
````

````
$ cp --version
cp (GNU coreutils) 8.21
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjörn Granlund, David MacKenzie, and Jim Meyering.
````

**Comment by errordeveloper** [comment]
I suppose this should be documented that it mimics cp from GNU coreutils.

> ... consistent with unix behavior

So it's not after all, as GNU stands for "GNU is Not UNIX" :smiley_cat:

**Comment by jterrace** [comment]
We do have it documented here:
https://cloud.google.com/storage/docs/gsutil/commands/cp#how-names-are-constructed

> The gsutil cp command strives to name objects in a way consistent with how Linux cp works, which causes names to be constructed in varying ways depending on whether you’re performing a recursive directory copy or copying individually named objects; and whether you’re copying to an existing or non-existent directory.
