### ISSUE TITLE
Support symlinking artifacts stored in gs buckets

### ISSUE THREAD

**Issue by fdegir** [GoogleCloudPlatform/gsutil#276]
We use Google Storage for storing artifacts produced by our build system and use gsutil for uploading/downloading artifacts.

During the development phase, we frequently need to locate the latest artifact in given bucket. We currently upload a text file that keeps link to latest artifact.

It would really be useful if this is supported by gsutil - creating symlinks. For example:

gsutil ln gs://my_bucket/latest gs://my_bucket/my_latest_artifact
gsutil cp gs://my_bucket/latest my_latest_artifact

**Comment by thobrla** [comment]
It's unlikely we'll implement this feature as it would rely on custom metadata and produce substantially behavior when using gsutil vs. using the API.

In your specific scenario, you should be able to achieve what you want simply by setting the contents of gs://my_bucket/latest to the URL link to gs://my_bucket/my_latest artifact.

# Update latest to gs://my_bucket/my_latest_artifact
echo "gs://my_bucket/my_latest_artifact" | gsutil cp - gs://my_bucket/latest"

# Copy the latest artifact to file "my_latest_artifact"
(gsutil cat gs://my_bucket/latest; echo my_latest_artifact) | xargs gsutil cp
