### ISSUE TITLE
wildcard matching does not work with zsh (ohmyzsh specifically)

### ISSUE THREAD

**Issue by inteist** [GoogleCloudPlatform/gsutil#278]
specifically `../prefix*` and `.../folder/**` are not working
neither other wildcards seem to work. 

same commands on the same machine working fine after switching to `bash`

**Comment by inteist** [comment]
While suspecting this is a zsh quirk I could not find a solution/cause. 

Of course right after filing the issue I found the culprit.

This is a zsh issue. zsh wants to expand * so have to escape *s... 

e.g.

`.../folder/\*\*`

**Comment by mfschwartz** [comment]
I'm curious - why does it matter that gsutil expand the wildcard instead of zsh? I would expect an identical expansion in either case for .../folder/** (since the gsutil ** syntax was actually based on the zsh ** syntax).

**Comment by inteist** [comment]
Using unescaped version just produces an error that nothing matching found.

**Comment by mfschwartz** [comment]
Would it be possible for you to post the file names that should match in that directory? If you'd prefer not to have them show up in the public forum you can email them to gs-team@google.com (and say Mike asked for them). I'd like to understand why zsh and gsutil are working differently here. Thanks.

**Comment by inteist** [comment]
Mike, the file names are irrelevant here. To reproduce the issue:

1. Install ohmyzsh (or probably just use any flavor of zsh)
2. try to list any non empty bucket or folder with the `gsutil ls ...../*` or `dsutil ls ..../**` syntax and see how zsh says:

`zsh: no matches found: gs://....`

If you still need more concrete information please let me know and I will try to provide it.

**Comment by mfschwartz** [comment]
I'm running zsh on Ubuntu and it works fine for me:

gsutil ls gs://mfsbucket/tests/**                                                                        ~
gs://mfsbucket/tests/__init__.py
gs://mfsbucket/tests/__init__.pyc
gs://mfsbucket/tests/mock_cloud_api.py
gs://mfsbucket/tests/mock_logging_handler.py
gs://mfsbucket/tests/test_Doption.py
gs://mfsbucket/tests/test_acl.py
gs://mfsbucket/tests/test_bucketconfig.py
gs://mfsbucket/tests/test_cat.py
gs://mfsbucket/tests/test_command_runner.py
gs://mfsbucket/tests/test_compose.py
gs://mfsbucket/tests/test_copy_helper_funcs.py
gs://mfsbucket/tests/test_cors.py
gs://mfsbucket/tests/test_cp.py
gs://mfsbucket/tests/test_creds_config.py
gs://mfsbucket/tests/test_daisy_chain_wrapper.py
gs://mfsbucket/tests/test_data/test.gif
gs://mfsbucket/tests/test_data/test.mp3
gs://mfsbucket/tests/test_data/test.p12
gs://mfsbucket/tests/test_data/test.txt
gs://mfsbucket/tests/test_defacl.py
gs://mfsbucket/tests/test_du.py
gs://mfsbucket/tests/test_file_part.py
gs://mfsbucket/tests/test_gsutil.py
gs://mfsbucket/tests/test_hash.py
gs://mfsbucket/tests/test_hashing_helper.py
gs://mfsbucket/tests/test_help.py
gs://mfsbucket/tests/test_lifecycle.py
gs://mfsbucket/tests/test_logging.py
gs://mfsbucket/tests/test_ls.py
gs://mfsbucket/tests/test_mb.py
gs://mfsbucket/tests/test_mv.py
gs://mfsbucket/tests/test_naming.py
gs://mfsbucket/tests/test_notification.py
gs://mfsbucket/tests/test_parallel_cp.py
gs://mfsbucket/tests/test_parallelism_framework.py
gs://mfsbucket/tests/test_perfdiag.py
gs://mfsbucket/tests/test_plurality_checkable_iterator.py
gs://mfsbucket/tests/test_rb.py
gs://mfsbucket/tests/test_resumable_streaming.py
gs://mfsbucket/tests/test_rm.py
gs://mfsbucket/tests/test_rsync.py
gs://mfsbucket/tests/test_rsync_funcs.py
gs://mfsbucket/tests/test_setmeta.py
gs://mfsbucket/tests/test_signurl.py
gs://mfsbucket/tests/test_stat.py
gs://mfsbucket/tests/test_storage_url.py
gs://mfsbucket/tests/test_tabcomplete.py
gs://mfsbucket/tests/test_tracker_file.py
gs://mfsbucket/tests/test_update.py
gs://mfsbucket/tests/test_util.py
gs://mfsbucket/tests/test_versioning.py
gs://mfsbucket/tests/test_web.py
gs://mfsbucket/tests/test_wildcard_iterator.py
gs://mfsbucket/tests/testcase/__init__.py
gs://mfsbucket/tests/testcase/base.py
gs://mfsbucket/tests/testcase/integration_testcase.py
gs://mfsbucket/tests/testcase/unit_testcase.py
gs://mfsbucket/tests/util.py
gs://mfsbucket/tests/util.pyc

Is this problem specific to ohmyzsh? Can you try installing a different zsh implementation?

**Comment by inteist** [comment]
Might be specific problem to ohmyzsh. I am running ohmyzsh on OS X. I would rather not install anything else just for this. 

I tried removing (renaming) .zshrc file so it does not load all the ohmyzsh plugins and what not hoping that it will give me a clean zsh (not sure about that since I don't know much about how this actually works). I got a bare bones zsh prompt (no PATH settings etc... )

producing this:
```
zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

and it still not working for me. 

I don't know if this experiment had any value. I hope it did and it's helpful.

**Comment by mfschwartz** [comment]
I have the same zsh version on my Mac and it works too.

Here's the thing: I'm 90% certain this problem is happening in the zsh before gsutil ever runs (with zsh attempting to expand the widlcarding). And since we're running the same zsh version on the same OS I'm now wondering if you have some zsh option enabled that's causing this. Do you have any options from `man zshoptions` set?

**Comment by inteist** [comment]
>I'm 90% certain this problem is happening in the zsh before gsutil ever runs

this is what I meant in my "solution" comment. 

I don't remember ever fiddling with ohmyzsh config. I don't even think I have any extra plugins installed.

**Comment by mfschwartz** [comment]
Do you have any zsh environment variables set?
