### ISSUE TITLE
cp command should output file names that failed to copy

### ISSUE THREAD

**Issue by daisy1754** [GoogleCloudPlatform/gsutil#279]
I recently copied more than 100K files from Amazon S3 with gsutil.

```
gsutil cp -m -R -a public-read "s3://from_bucket/*" gs://to_bucket
```

I could successfully copy most of files, but I finally received following message.

> ResumableUploadException: Transfer failed after 6 retries. Final exception: The read operation timed out CommandException: 35 files/objects could not be transferred.

I think gsutil cp command should output file names that it failed to copy so I can resolve issue...

**Comment by mfschwartz** [comment]
gsutil outputs a failure message when it is unable to copy a file. If you run a large copy operation (over many files) and want to keep track of which attempts failed you could use the cp -L option and then examine the manifest after the failure to see which files failed to copy. Does that address the problem for you?

**Comment by rayfoss** [comment]
... I ran a job for 6 hours. 30 unknown files had issues. gsutil should seriously report those files at the end of the job. I'll have to re run the job with -L at the expense of the company because of this. I would go as far as to block large jobs that don't have `-L` until this is addressed
