### ISSUE TITLE
Unable to update submodule third_party/apitools from Github

### ISSUE THREAD

**Issue by jpatokal** [GoogleCloudPlatform/gsutil#280]
I've cloned the repo successfully, but updating submodules fails halfway through:

    $ git submodule update --init --recursive
    ...
    Submodule path 'third_party/socksipy-branch': checked out '5e341b5589e855d39cfa4b654208c98547d870b5'
    fatal: reference is not a tree: 7d703769cf4c555971cda94735ab8828c013f98e
    Unable to checkout '7d703769cf4c555971cda94735ab8828c013f98e' in submodule path 'third_party/apitools'

The reference to `7d703769cf4c555971cda94735ab8828c013f98e` was added in this recent commit:

https://github.com/GoogleCloudPlatform/gsutil/commit/a5482a7640182d585dc5fc38f1320d75c3fc6f00

**Comment by thobrla** [comment]
Fixed with https://github.com/GoogleCloudPlatform/gsutil/commit/dd35d029a08764c5b638c25ebdeb8239b9bc988f
