### ISSUE TITLE
gsutil fails when given a read-only stderr

### ISSUE THREAD

**Issue by pcc** [GoogleCloudPlatform/gsutil#289]
Actual:

```
$ ./gsutil cp gs://chromium-browser-clang/Linux_x64/llvmgold-241602-3.tgz llvmgold-241602-3.tgz < /dev/null 2>&0
$ echo $?
1
$ ls -l llvmgold-241602-3.tgz 
-rw-r----- 1 pcc [...] 0 Jul 20 12:39 llvmgold-241602-3.tgz
```

Expected: llvmgold-241602-3.tgz downloaded completely, exit code 0 (or file not created at all, exit code 1).

This might not be something gsutil can reasonably support, but it has happened in practice in certain buildbot configurations.

**Comment by thobrla** [comment]
You may be able to work around this with the -q flag, which will suppress output:
gsutil -q cp ...

**Comment by houglum** [comment]
Closing this, as it's been a couple years. Also, I'm not sure why you'd provide a read-only destination for writing; if you want to route stderr to /dev/null, you could alternatively use 2>/dev/null.  Feel free to reopen if you have any additional comments.
