### ISSUE TITLE
-m no longer works for mv, but still works for cp

### ISSUE THREAD

**Issue by wmacgyver** [GoogleCloudPlatform/gsutil#297]
after upgrading to gsutil 4.15, if I run gsutil -m mv, instead of multithread behavior like before, it only mv one file at a file and gives me a warning about "use -m to speed this up", but gsuilt -m cp still works.

is this an intended behavior change?

**Comment by thobrla** [comment]
Thanks for the report.  This is not an intended change.  I believe this issue was introduced in 4.14 with [this commit](https://github.com/GoogleCloudPlatform/gsutil/commit/d03fdd7d7353e913d7f678984334aa6983df4c03) that changed the ordering of RunNamedCommand parameters.
