### ISSUE TITLE
gsutil cp reports OK but file does not exist in bucket

### ISSUE THREAD

**Issue by peda** [GoogleCloudPlatform/gsutil#300]
Hello,

I'm trying to recursively copy data from a local storage to a Google Storage bucket using gsutil cp

The command issued is 
``gsutil -m cp -R -L gsutil.log /root/backup/ gs://MY_BUCKET_NAME/``

Even the log file shows OK for all files - here is a line of a missing file from the log

```
file:///root/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb,gs://MY_BUCKET_NAME/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb,2015-10-06T18:21:07.929552Z,2015-10-06T18:21:09.923508Z,+cKX5JW5ddtJgzK34S9A7g==,,38612992,38612992,OK,
```

even though everything reports the file transfer as OK some of the files (i.e. the one in the log above) do not exist in the Google Storage bucket. 

I've tried gsutil ls and the Google Developers Console to ensure it's not a display issue, it's not visible in either of them - it just shows an empty folder ...

**Comment by thobrla** [comment]
If you run:
`gsutil stat gs://MY_BUCKET_NAME/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb` 

does it show up?  Listing in Google Cloud Storage is eventually consistent so it's possible the file won't appear immediately after the upload completes.

**Comment by peda** [comment]
first of all thanks fro your quick reply

the command
``./gsutil/gsutil stat gs://MY_BUCKET_NAME/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb``

does result in

```
No URLs matched gs://MY_BUCKET_NAME/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb
```

and here the gsutil.log entry for this gsutil cp command for this file
```
file:///root/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb,gs://MY_BUCKET_NAME/backup/2015-10-06T181356Z/2015-10-06T181356Z-full/bucket-simplehms/node-167.114.225.106%3A8091/data-0000.cbb,2015-10-06T18:21:07.929552Z,2015-10-06T18:21:09.923508Z,+cKX5JW5ddtJgzK34S9A7g==,,38612992,38612992,OK,
```

unfortunately I've deleted the old folders (from 1 hour ago) because I did try it again and again to see  if I could find any reason myself - if it does make any difference I can run ``gsutil stat`` again in an hour or so ... 

the result is perfectly reproducible for me ... it's the same every time I try it with a similar data - I'm using ``gsutil version: 4.15``

**Comment by thobrla** [comment]
Since this is reproducible, could you send the output of:
`gsutil -D -m cp -R -L gsutil.log /root/backup/ gs://MY_BUCKET_NAME/`
to gs-team@google.com?  I can take a deeper look at it there.  Thanks.

**Comment by peda** [comment]
yes, will do so :-) thanks in advance

**Comment by thobrla** [comment]
It turns out this was an issue in the Google Cloud Platform UI where %3A on the URL was improperly being translated into a colon in the URL.  Until that's fixed, the workaround in the UI is to manually percent-encode the percent sign in the URL, i.e., replace %3A with %253A

**Comment by behnam-lum** [comment]
I still have a similar problem. If I copy something to a bucket form within my compute engine and then check the status of the file or the parent folder, the `gsutil stat` returns no matching URL. However, if I create that file or parent folder from GCP console, then `gsutil stat` correctly returns the data.
This has been frustrating as my compute engine needs to rely on this!

**Comment by gadget** [comment]
similar happens for me, steps:
-I create a file with my own user (gsutil cp) | OK
-I delete the file from the bucket with my own user (gsutil rm) | OK
-a service user tries to create another file with the very same name | gsutil reports all good, but the file never appears in the bucket

**Comment by suyx** [comment]
> I still have a similar problem. If I copy something to a bucket form within my compute engine and then check the status of the file or the parent folder, the `gsutil stat` returns no matching URL. However, if I create that file or parent folder from GCP console, then `gsutil stat` correctly returns the data.
> This has been frustrating as my compute engine needs to rely on this!
I have a similar issue. My Django app writes files to bucket. The function completes without any error. But the file doesn't appear in the bucket until i restart the server.
