### ISSUE TITLE
using -m causes the file to not fully upload

### ISSUE THREAD

**Issue by wdewind** [GoogleCloudPlatform/gsutil#306]
We are using gsutil to store encrypted backups of our database.  When we send the file using the -m option the file is either corrupted or not fully uploaded.  When we retrieve it we are not able to decrypt it because the end of the file is missing (or corrupted - impossible to tell with encrypted data).  If we drop the -m then everything works as expected.

**Comment by thobrla** [comment]
Does this reproduce consistently?  If so, can you send debug logs of the commands you are running:
`gsutil -D <your upload command> ...`
`gsutil -D <your download command> ...`
to gs-team@google.com?

**Comment by wdewind** [comment]
Thanks for the prompt response.  Sorry for incorrect info, it turns out the flag doesn't matter.  The difference is running the gsutil commands directly on the command line vs. from a ruby or sh script.  If we run it on the command line we have no problems, if we run it via a ruby or sh script we do.  I'll send -D output to the address.

**Comment by wdewind** [comment]
Issue was on our end, thanks for the extremely fast replies, they were appreciated :)
