### ISSUE TITLE
cp command: Need a version of -z option that applies to all extensions

### ISSUE THREAD

**Issue by dimfeld** [GoogleCloudPlatform/gsutil#308]
The `-z` option takes a list of extensions to compress as they are uploaded. Can we get an option to just compress all files? Specifically in my case (Postgres database backup), most of the files have no extension at all, and there are a few hundred files, each about 1GB, that compress well with gzip. Given the total data size I'd prefer not to put the whole thing into a giant archive before uploading.

I could put together a wrapper around gsutil to zip and upload the files a few at a time without too much trouble but it seems cleaner to just integrate it into gsutil. I'll be glad to submit a PR for this if you're amenable to it.

**Comment by thobrla** [comment]
We'd be happy to accept a PR for this.  I think the preferred approach would be to add a (capital) -Z flag that compresses all files.

Before you submit, please sign the appropriate CLA (per `gsutil help dev`) so we can accept the PR.

**Comment by dimfeld** [comment]
Sounds great. I'll sign the CLA and should have something ready soon.

**Comment by dimfeld** [comment]
Submitted code review to https://codereview.appspot.com/273010043/. Thanks!
