### ISSUE TITLE
signurl generates bad url?

### ISSUE THREAD

**Issue by gbitzes** [GoogleCloudPlatform/gsutil#314]
Running signurl generates a URL which does not work for me, it results in a `The User Id you provided does not exist in our records.` error.

The command I'm running is:

`gsutil signurl ~/key.p12 gs://mybucket/file`

And the URL generated looks like this:
```
https://storage.googleapis.com/mybucket/file?GoogleAccessId=...a bunch of digits...&Expires=1448052373&Signature=...removed...
```

I made sure that the service account whose private key I'm using to generate the URL does have access to the object.

Since I saw on the [documentation](https://cloud.google.com/storage/docs/access-control?hl=en#Signed-URLs) that `GoogleAccessId` is supposed to be an email, I manually changed the URL parameter to be the email of my service account:

```
https://storage.googleapis.com/mybucket/file?GoogleAccessId=account-1@...removed...iam.gserviceaccount.com&Expires=1448052373&Signature=...removed...
```

And now it works! Is this a bug, or am I doing something wrong? Why does the URL generated by gsutil contain an invalid `GoogleAccessId`?

**Comment by thobrla** [comment]
This is an issue with signed URLs not properly accepting GoogleAccessIds for IAM service accounts.  Hopefully it will be fixed on the service side within the next few weeks (no guarantees, of course).  Until then, manually changing the parameter will work.

**Comment by thobrla** [comment]
This is now fixed and you should be able to create signed URLs with IAM service accounts using gsutil 4.16.
