### ISSUE TITLE
gsutil -q stat isn't quiet

### ISSUE THREAD

**Issue by lbergelson** [GoogleCloudPlatform/gsutil#316]
My understanding of `gsutil -q stat <file>` is that it should silently return as 0 or 1 if file exists or doesn't.

However, it outputs an error message to stderr if the file doesn't exist.
```
$ gsutil -q stat gs://bucket/nonexistantfile
No URLs matched gs://bucket/nonexistantfile%
```

I believe this was likely introduced by the resolution to this: https://github.com/GoogleCloudPlatform/gsutil/issues/288

**Comment by thobrla** [comment]
Thanks for the report, this is a bug in the fix to #288 as you suggested.  I'll get a fix out soon but it won't be in the gsutil 4.16 release.  If this is affecting you critically, let me know and I'll publish a prerelease 4.17 version with this fix.

**Comment by lbergelson** [comment]
Thanks for the response @thobrla!  It's not critical, just slightly annoying.  Don't worry about a pre-release

**Comment by lbergelson** [comment]
:+1: Thanks for the quick turnaround on this.
