### ISSUE TITLE
Log files HH:MM:SS naming prevents storing in Windows

### ISSUE THREAD

**Issue by OriolAndres** [GoogleCloudPlatform/gsutil#320]
Hey,
I was trying to download AppEngine log files from Storage using gsutil when I found that the name of the files prevents them being saved in Windows.
This is the command:
gsutil cp -r gs://my_bucket/* my_local_folder

This is stdout:
Copying gs://my_bucket/appengine.googleapis.com/request_log/2015/11/26/22:00:
00_22:59:59_S0.json...
Downloading ...request_log\2015\11\26\22:00:00_22:59:59_S0.json: 0 B/2.6 KiB
Downloading ...request_log\2015\11\26\22:00:00_22:59:59_S0.json: 2.6 KiB/2.6 KiB
OSError: The filename, directory name or volume label syntax is incorrect.

Cheers.

**Comment by thobrla** [comment]
Thanks for the report.

It looks like your object name contains characters that are [reserved](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) on Windows.  gsutil doesn't modify the name of source objects, so if your object has a Windows-incompatible name, you'll need to copy it without a wildcard and choose a name that's valid on Windows, for example:

`gsutil cp gs://my_bucket/appengine.googleapis.com/request_log/2015/11/26/22:00 my_local_folder/request_log-2015-11-26_22-00`

**Comment by gsusI** [comment]
Other option is to run the gsutil command from WSL.

Windows reserved characters will be correctly visualised from WSL, whilst when accessing them from cmd/powershell they will show up like <kbd></kbd>.
