### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by tianzhipeng-git** [GoogleCloudPlatform/gsutil#323]
when doing files pull by 
`trickle -d ${throttle_rate} -u ${throttle_rate} gsutil -m cp -rcn $file_pattern $local_dir$yes`
the program stall and generate a core dump file 
`core.16417: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'python /root/DMP/platform/gsutil/gsutil -m cp -rcn gs://dfa_-1c95aa897fd6246781'`
the gdb out is: 

Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/3b/382f03a1b5ff541e146d5e596c15503d74ac79
[New Thread 16476]
[New Thread 16477]
[New Thread 16480]
[New Thread 16482]
[New Thread 16481]
[New Thread 16486]
[New Thread 16484]
[New Thread 16417]
[New Thread 16489]
[New Thread 16479]
[New Thread 16474]
Core was generated by `python /root/DMP/platform/gsutil/gsutil -m cp -rcn gs://dfa_-1c95aa897fd6246781'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f8d61169ae6 in ?? ()
(gdb) 

and the program has NOT quit , just choking there. there is still 6 pid runing `ps aux|grep gsutil`

in addition, it shows `79.83 MiB/373.48 MiB`  but the file size is 1.46 GB actually.

**Comment by thobrla** [comment]
1. Does this reproduce consistently?
2. This is for a single file copy?
3. What value are you using for $throttle_rate?

The 79.83 MiB/373.48 MiB is a misleading, the file is likely being downloaded in slices and the reporting is per-slice.

**Comment by tianzhipeng-git** [comment]
1. Not always,but it occurs servaral times. 
2. A single file.
3 The rate is set to 10240, KB/s.

and the background gsutil process is not `running` , its stat is `Sl` .

**Comment by thobrla** [comment]
Does this occur if you disable sliced downloads and multiprocessing?  I'm wondering if trickle is not working well when multiple processes are spawned underneath it.  Can you reproduce with this command:

`trickle -d ${throttle_rate} gsutil -o 'GSUtil:sliced_object_download_threshold=0' gsutil cp -rcn $file_pattern $local_dir$yes`

**Comment by tianzhipeng-git** [comment]
Follow your advice, this problem doesnt reproduce again these days . Thanks!
