### ISSUE TITLE
Gsutil upload slower than Web UI 

### ISSUE THREAD

**Issue by pr8werk** [GoogleCloudPlatform/gsutil#329]
Hi, 

I have an issue with gsutil cp command when uploading a single file (60mb) to my bucket - the speed is too slow. I have a 40 mbit upstream connection, and I have run perfdiag with the result showing only 4,35 Mbits/s upload (!) speed.
If I drag and drop the same file in WebUI GCS bucket - full speed upload.

I asume this is having to do with "resumable" otion being on for large files - but I don't know how to st it off. Please help me with that issue.

Thanks in advance,
Theo K.

**Comment by pstemari** [comment]
In your .boto file, you can specify the resumable upload threshold. For example, this sets it to 100MB:

```
[GSUtil]

# 'resumable_threshold' specifies the smallest file size [bytes] for which
# resumable Google Cloud Storage transfers are attempted. The default is 8388608
# (8 MiB).
resumable_threshold = 100000000
```

**Comment by thobrla** [comment]
I discussed this over email with [pr8werk](https://github.com/pr8werk). Changing the resumable threshold didn't have an impact on performance.  Enabling parallel composite uploads allowed speeds matching the UI, but it was inconclusive why gsutil was slower than the UI for a single stream.
