### ISSUE TITLE
gsutil failing on worker_thread.start()

### ISSUE THREAD

**Issue by andyadamides** [GoogleCloudPlatform/gsutil#336]
This occurs randomly from time to time, e.g. sometimes once a week, sometimes once every two weeks and so on. Our schedule involves executing around 30 gsutil commands per day and the version we have is 4.15.

Please see for more information and log output:

http://stackoverflow.com/questions/35655622/gsutil-failing-on-worker-thread-start?noredirect=1#comment58994702_35655622

Any info on this issue would be extremely valuable.

**Comment by thobrla** [comment]
As asked in the comments in the SO question, could you post the full stack trace?  It looks like it was cut off in the SO question.

Generally speaking, if Python can't successfully start a thread, that's an OS-level issue that is going to cause problems for gsutil.  
as a workaround, you can try reducing the number of threads/processes in your .boto configuration file by setting parallel_thread_count or parallel_process_count to smaller values.
