### ISSUE TITLE
gsutil responds with AccessDeniedException: 403 This service is not available from your country

### ISSUE THREAD

**Issue by OriginalPenguin** [GoogleCloudPlatform/gsutil#340]
gsutil used to work great but now responds with "AccessDeniedException: 403 This service is not available from your country"

I am using it on a co-located server in the United States. (I am also in the United States).

Just to make sure I grabbed the latest zip of gsutil, and I redid gsutil config.  I'm still getting the same error, even just with gsutil ls.

Any ideas?

**Comment by pstemari** [comment]
This is an issue on our side with the geolocation that your IP has been
mapped to. Please respond privately with specifics of your IP address and
provider location and we'll investigate and correct if necessary.

—Paul

**Comment by OriginalPenguin** [comment]
Hi Paul....

I grabbed your email address from the repo, and just sent you an email with the details.

Thanks again for looking into this for me.

**Comment by pstemari** [comment]
Working this with our geolocation team.

**Comment by pstemari** [comment]
Our geolocation team has resolved the error. I apologize for the inconvenience.
