### ISSUE TITLE
GSUtil Update Locking Up System

### ISSUE THREAD

**Issue by camclay** [GoogleCloudPlatform/gsutil#345]
Hello,

Trying to update gsutil on a FreeBSD (FreeNas 9.3/Jailed Install) System from 4.16 to 4.18.

Attempted update first time, ended up crashing NFSD and using up 100% of processor, after a half hour, I attempted to term but could not do so reliably. No other scripts were running on the system at that time, and I forced a hard restart of the system.

Currently attempting a second time but it has locked up again at the Downloading stage, 

Attached are images of the shell instance that is locked, current processor usage, and base system information,

Thanks in advance,
Cam
![screen shot 2016-03-23 at 2 28 34 pm](https://cloud.githubusercontent.com/assets/8294484/13996351/adb013bc-f103-11e5-8bab-45fe017a1a57.png)
![screen shot 2016-03-23 at 2 28 09 pm](https://cloud.githubusercontent.com/assets/8294484/13996350/adac7838-f103-11e5-933d-6bf55b74f25e.png)
![screen shot 2016-03-23 at 2 20 10 pm](https://cloud.githubusercontent.com/assets/8294484/13996352/adb18c42-f103-11e5-95d1-8030417327c7.png)

**Comment by thobrla** [comment]
It's generally not advisable to run gsutil update from within the directory that's being updated.  Does this happen if you run it from outside of that directory?

**Comment by camclay** [comment]
Hello,

I attempted running it from the home/root directory using command /gsutil/gsutil update and the same occurred,

Should I try it a third way?

**Comment by thobrla** [comment]
Could you send mail to gs-team@google.com so I can debug this issue with you over mail?

As a last resort, it should be sufficient to just download the current gsutil tarball (`gsutil cp gs://pub/gsutil.tar.gz`), manually delete the existing install, and untar the new one.

**Comment by camclay** [comment]
Hello,

I upgraded my OS from FreeBSD 9.x to 10.x and the issue was resolved.

Sorry about leaving this out there, as I thought I had updated it last week.

Thank you for the replies, as it lead me to resolving another issue with getting the bin path working as well,

Cam
