### ISSUE TITLE
Gsutil update prompt breaks automation

### ISSUE THREAD

**Issue by Aricg** [GoogleCloudPlatform/gsutil#347]
Hi, we use gsutil extensively to upload builds to GSE.
The most recent update broke uploads with its "press y to update" prompt.
I would like a less expensive solution than adding 
gsutil update -n  each time I need to run gsutil non interactively

**Comment by jterrace** [comment]
How are you invoking the gsutil command? If stdin/stdout/stderr are not a TTY, then the prompt should be skipped.

If for some reason you can't get the prompts to go away, a workaround would be to set the software_update_check_period config option in your boto config to the value 0, which disables the update check.

**Comment by Aricg** [comment]
Hmm. Something else must have been causing this issue, I can't confirm without writing some better logging. Thank you for your time.
