### ISSUE TITLE
Slow cp for large backup file to Nearline

### ISSUE THREAD

**Issue by dombarnes** [GoogleCloudPlatform/gsutil#354]
I am using gsutil to copy a large MS SQL database to a Nearline bucket for backup reasons. Its uploading via a Powershell script calling:
````gsutil -m cp filename.bak gs://bucket-name````
The backup is ~150GB in size and on last upload, took 23hrs to upload from our server that has a 100Mbps link speed. The server is under very low load, maybe 10-20 clients connecting at most.
I can upload the same file via FTP to another server in ~5hrs. And I can upload the same file from that server (which has 1000Mbps link speed) in ~5hrs too (currently going at 90Mbps). Same file, same command.

I'm trying to understand why its going so slowly from one server. Looking in Task Manager, its using about 25% network utilisation, whereas FTP will happily use ~98%.

Operating System: Windows Server 2008 R2
gsutil version: 4.18

**Comment by thobrla** [comment]
Is link speed the only difference between the two servers?  Does it consistently take this long on this server, or just occasionally?

Is it feasible for you to turn on parallel composite uploads (`gsutil help cp`)?  It requires you and clients that will download this file via gsutil to install a compiled crcmod (see `gsutil help crcmod`), but it should substantially increase throughput and decrease the variance in throughput.

**Comment by thobrla** [comment]
One other question: if you run `gsutil perfdiag -t wthru_file -s 100M gs://your-bucket` from the slow server, do you see similar results for throughput?  Can you share the results (scrubbing your IP address if necessary)?

**Comment by dombarnes** [comment]
The faster server is a Windows 2012 server, and a VPS, but the slower one is dedicated hardware (both should be in the same datacenter though)

**Comment by dombarnes** [comment]
Thanks for the replies. The slow server consistently takes much longer. Last few uploads have been 16hrs, 17hrs, 23hrs.
Is the crcmod stuff supported on Windows machines? Or is it just the parallel threading thats not suitable?
This is the result from the slow W2K8 server
````
==============================================================================
                              DIAGNOSTIC RESULTS
==============================================================================
------------------------------------------------------------------------------
                        Write Throughput With File I/O
------------------------------------------------------------------------------
Copied 5 100 MiB file(s) for a total transfer size of 500 MiB.
Write throughput: 17.83 Mibit/s.
Parallelism strategy: None
------------------------------------------------------------------------------
                              System Information
------------------------------------------------------------------------------
IP Address:
  88.xx.xx.xx.xx
Temporary Directory:
  c:\users\admini~1\appdata\local\temp\2
Bucket URI:
  gs://bucket-name/
gsutil Version:
  4.18
boto Version:
  2.38.0
Measurement time:
 2016-04-13 10:03:28 PM
Google Server:
  storage
Google Server IP Addresses:
  74.125.133.128
Google Server Hostnames:
  wo-in-f128.1e100.net
Google DNS thinks your IP is:
  213.171.193.134
CPU Count:
  4
CPU Load Average:
  None
TCP segments sent during test:
  389016
TCP segments received during test:
  194691
TCP segments retransmit during test:
  11
TCP /proc values:
Boto HTTPS Enabled:
  True
Requests routed through proxy:
  False
Latency of the DNS lookup for Google Storage server (ms):
  16.0
Latencies connecting to Google Storage server IPs (ms):
  74.125.133.128 = 16.0
------------------------------------------------------------------------------
                          In-Process HTTP Statistics
------------------------------------------------------------------------------
Total HTTP requests made: 6
HTTP 5xx errors: 0
HTTP connections broken: 0
Availability: 100%
````
I also ran this on the "faster" server
````
==============================================================================
                              DIAGNOSTIC RESULTS
==============================================================================

------------------------------------------------------------------------------
                        Write Throughput With File I/O
------------------------------------------------------------------------------
Copied 5 100 MiB file(s) for a total transfer size of 500 MiB.
Write throughput: 81.22 Mibit/s.
Parallelism strategy: None

------------------------------------------------------------------------------
                              System Information
------------------------------------------------------------------------------
IP Address:
  109.xx.xx.xx
Temporary Directory:
  c:\users\admini~1\appdata\local\temp\2
Bucket URI:
  gs://actuariesonline/
gsutil Version:
  4.18
boto Version:
  2.38.0
Measurement time:
 2016-04-13 10:06:23 PM
Google Server:
  storage
Google Server IP Addresses:
  74.125.133.128
Google Server Hostnames:
  wo-in-f128.1e100.net
Google DNS thinks your IP is:
  213.171.193.134
CPU Count:
  2
CPU Load Average:
  None
TCP segments sent during test:
  388358
TCP segments received during test:
  173802
TCP segments retransmit during test:
  1
TCP /proc values:
Boto HTTPS Enabled:
  True
Requests routed through proxy:
  False
Latency of the DNS lookup for Google Storage server (ms):
  0.0
Latencies connecting to Google Storage server IPs (ms):
  74.125.133.128 = 16.0

------------------------------------------------------------------------------
                          In-Process HTTP Statistics
------------------------------------------------------------------------------
Total HTTP requests made: 6
HTTP 5xx errors: 0
HTTP connections broken: 0
Availability: 100%
````

**Comment by thobrla** [comment]
Thanks for posting the perfdiag results - nothing about them explains the difference in speed, unfortunately.  Do you get a similar upload speed for files on the slow server via the Cloud Storage UI?

crcmod is supported on Windows machines (using 32-bit Python) - see `gsutil help crcmod`.  gsutil doesn't support multiple processes on Windows machines, but does support multiple threads, and that should improve your performance if you're limited by single-stream TCP.  If for some reason it doesn't improve your performance, that's a good data point for this discussion.
