### ISSUE TITLE
Upgrade oauth2client dependency to >2 to be compatible with google-api-python-client

### ISSUE THREAD

**Issue by maxgrenderjones** [GoogleCloudPlatform/gsutil#355]
In `setup.py` `gsutil` requires `oauth2client==1.5.2`. The latest version of [google-api-python-client](https://github.com/google/google-api-python-client) on pypi (version 1.5.0 at the time of reporting) requires [oauth2client](https://github.com/google/oauth2client) > 2.

While it does look like this restriction has been removed in the latest version of [setup.py](https://github.com/google/google-api-python-client/blob/master/setup.py) - relevant [commit](https://github.com/google/google-api-python-client/commit/bb324623419a22fb14da1e22a847b6b09a178aad) it feels like it would be better to allow `gsutil` to work with later versions of oauth2client rather than force google-api-client to work with earlier ones.

**Comment by thobrla** [comment]
oauth2client >= 2 introduced some backwards-incompatible changes, which is why gsutil didn't migrate immediately.  The eventual plan is to migrate to oauthclient >= 2, but we don't have a timeline for that yet.

**Comment by maxgrenderjones** [comment]
Is it not possible to support both at the same time?

for example, replace:
```python
from oauth2client.client import SignedJwtAssertionCredentials
```
with
```python
from oauth2client.service_account import ServiceAccountCredentials
```
(and change the credential creation calls to match the slightly different API)

and elsewhere (the change required to enable version agnosticism from google-api-python-client):
```python
try:
    from oauth2client.contrib.locked_file import LockedFile
except ImportError:
    # oauth2client < 2.0.0
    from oauth2client.locked_file import LockedFile
```

I guess I should really be railing at the oauth2client folks for:
 a) breaking the API (ok, has to be done sometimes) and 
 b) not providing comprehensive migration docs (although there is some help, seemingly incomplete, in their [release notes](https://github.com/google/oauth2client/releases) )

**Comment by thobrla** [comment]
We can try this approach, but there's no guarantee that the changes needed to support both versions in google-api-python-client are sufficient to cover all of gsutil's use cases.  So it requires development and testing effort.

**Comment by maxgrenderjones** [comment]
Fair enough (super impressive reply speed btw) - you may find some useful pointers (amidst the grumbling at breakage) at https://github.com/google/oauth2client/issues/401

**Comment by dymov** [comment]
Is there any workaround for this? As for now, it seems to be impossible to use both libraries in the same project?

**Comment by houglum** [comment]
I'll be looking into the work required to bump the oauth2client version dependency to 4.X.X at some point in the near future, but I don't have any solid ETA to give at the moment.  Just letting you know that it's on my radar :)

**Comment by vapier** [comment]
can we close this now since 114fc88c47657ab9b1669be7a82dfa847f2a856f updated things to 4.1.2 ?
