### ISSUE TITLE
allow access token to be passed in to `gsutil cp`

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/gsutil#357]
The current access token can be obtained by doing a `gcloud auth print-access-token`. That works for service accounts too. It would be useful if the access token can be passed in for commands, especially `gsutil cp`.

As a workaround, I wrote this script to download files:
``` python
#!/usr/bin/env python
# derived from https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/api/crud_object.py

import argparse
import json
import io

from googleapiclient import discovery
from googleapiclient import http

from oauth2client.client import GoogleCredentials
from oauth2client.client import AccessTokenCredentials

def main(bucket, filename, accesstoken):
    service = create_service(accesstoken)
    with io.FileIO(filename, mode='wb') as outfile:
        get_object(service, bucket, filename, outfile)

def create_service(accesstoken):
    # print("accesstoken: %s" % accesstoken)
    if not accesstoken:
        credentials = GoogleCredentials.get_application_default()
    else:
        credentials = AccessTokenCredentials(accesstoken, 'my-user-agent/1.0')
    return discovery.build('storage', 'v1', credentials=credentials)

def get_object(service, bucket, filename, outfile):
    print("gsutil cp gs://%s/%s %s" % (bucket, filename, filename))
    req = service.objects().get_media(bucket=bucket, object=filename)
    downloader = http.MediaIoBaseDownload(outfile, req)
    done = False
    while done is False:
        status, done = downloader.next_chunk()
        # print("Download {}%.".format(int(status.progress() * 100)))
    print("gsutil cp done")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('bucket', help='storage bucket')
    parser.add_argument('filename', help='the file to download')
    parser.add_argument('accesstoken', help='access token')
    args = parser.parse_args()
    main(args.bucket, args.filename, args.accesstoken)
```

**Comment by thobrla** [comment]
Can you explain your use case in more detail?  gsutil can already download files with the credentials that are active in gcloud, which in turn uses the associated access token or service account credentials.  What new functionality does your script enable that isn't already covered by `gsutil cp`?

**Comment by ctaggart** [comment]
It is useful when you want to hand off an access token to another machine, such as docker, so that it can download and install stuff from storage.
`docker build --build-arg StorageAccessToken=$(gcloud auth print-access-token) `

**Comment by thobrla** [comment]
If you're trying to have another machine act as the same user, it seems like a [service account](https://cloud.google.com/storage/docs/authentication#service_accounts) would be a much better solution.  You can pass your private key file to that machine and then run
`gcloud activate-service-account --key-file /path/to/your/key/file`

This has multiple advantages over trying to plumb an access token:
1. An access token typically expires after 1 hour, making your delegation unreliable after a period of time.
2. This would enable all gcloud/gsutil commands to work, not just ones that accepted your proposed new argument

Will this work for your scenario?

**Comment by ctaggart** [comment]
I'm using a service account on the CI server. I create an access token from the logged in service account. I didn't want to put the private key for the service account on the docker image. I'm not sure if I can pass it in via `--build-arg` and write it to a temporary file or not. It would be nice if I could pass in the access token to `gcloud auth` and have it give access to everything until it expires. May be: `gcloud auth login --access-token $ACCESSTOKEN`?

**Comment by thobrla** [comment]
There are a couple issues here.  First, sharing access tokens in this way isn't very robust.  While it might work for your specific scenario, it won't work for many others.  Also, down the road if your scenario changes and the token expires (for example because the commands you're running on the machine run for longer), it will no longer work.

Second, given that there is a supported way to do this in the form of service accounts, it doesn't make sense to plumb this feature through all of our tooling.  You might only need support for `gsutil cp`, but later find you need to run other commands as well.

Certainly there must be some way that you can copy a service account key file to your machine, perhaps http://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container ?

**Comment by ctaggart** [comment]
For the scenario, where you want to download stuff to put on a docker container it works great. The other methods of copying files to the container would leak the key to anyone with access to the  docker image. I don't want that.

**Comment by thobrla** [comment]
I'm not a docker expert, so please pardon my slowness in understanding you and correct me as needed.  According to your comment at https://github.com/GoogleCloudPlatform/gsutil/issues/357#issuecomment-213116680 it looks like you're proposing building a docker image with an access token as a build argument.

Is the intent that the files are downloaded to a container only when it is run?  Or that they are included in the image itself during build time?  If it's the former, it seems like that would only work for containers run within one hour of the image build time.  If it's the latter, why not download the required files on the host that's building the image and then include them in the image directly?

**Comment by ctaggart** [comment]
Correct, I'm building a docker image using a `Dockerfile` that has something like this:

```
FROM ubuntu:14.04

COPY install-python.sh /root/
COPY install-download.py /root/

ARG StorageAccessToken

RUN cd root \
  && ./install-python.sh \
  && StorageAccessToken=$StorageAccessToken ./install-download.py \
  && apt-get clean
```

When the image is being built, it downloads and uses installer files from Google Storage. The reason you wouldn't download them to the host and `COPY` the files in is because the installer files are big and it would bloat your image by the size of the installer files. A `COPY` creates a layer.

A typical example is to curl the installer file (a .zip or .tgz. or .deb), install it, and then remove the installer file.
https://github.com/docker-library/golang/blob/d7e2a8d90a9b8f5dfd5bcd428e0c33b68c40cc19/1.5/Dockerfile#L15

Aside, I wasn't able to figure out how to download the media file using curl yet. Any ideas? This gets me info about the file:
```
curl -H "Authorization: Bearer $StorageAccessKey" https://www.googleapis.com/storage/v1/b/$StorageBucket/o/$StorageFile
```
but when I try to download it from the media link or by adding `download`, I get an error:
```
curl -H "Authorization: Bearer $StorageAccessKey" https://www.googleapis.com/download/storage/v1/b/$StorageBucket/o/$StorageFile
```
```
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notDownload",
    "message": "Only media downloads requests can be sent to /download/*. Re-send request to the same path, but without the /download prefix."
   }
  ],
  "code": 400,
  "message": "Only media downloads requests can be sent to /download/*. Re-send request to the same path, but without the /download prefix."
 }
}
```
Any ideas how to download it with curl. That is a better workaround if I could get it to work.

**Comment by thobrla** [comment]
If you're deleting files after you run the installer, what's the problem with sending the contents of a private key file and then deleting that afterwards?

Anyway, to fix the problem with curl, I recommend adding quotes around the media link, which typically contains a ? and and & that can represent special characters in shells.

**Comment by ctaggart** [comment]
I used [mitmproxy](https://mitmproxy.org/) to troubleshoot the request and found out I was just missing the `alt=media` query param. I'm closing this and will just use `curl` for docker builds.
```
curl -o $StorageFile -H "Authorization: Bearer $StorageAccessToken" https://www.googleapis.com/storage/v1/b/$StorageBucket/o/$StorageFile?alt=media
```

**Comment by melissachang** [comment]
I also am trying to use gsutil without Service Account key. (My employer prohibits use of SA keys. Ironically, my employer is Google.) Documenting what worked.

There are 3 versions of `gsutil`:
1. Standalone `gsutil`. This is the oldest, and predates `gcloud`.
1. `gsutil` as part of gcloud
1. `gcloud alpha storage`. This is the newest. Faster than 2.

For 2: Write the `~/.config/gcloud/legacy_credentials/default/.boto` that `google-cloud-sdk/bin/bootstrapping/gsutil.py` expects:

```
[OAuth2]
client_id = <CLIENT_ID>
client_secret = <CLIENT_SECRET>

[Credentials]
gs_oauth2_refresh_token = <REFRESH_TOKEN>
```

For 3: Do what rest of `gcloud does`: set [`CLOUDSDK_AUTH_ACCESS_TOKEN`](https://cloud.google.com/sdk/docs/release-notes#cloud_sdk_2). Note that you'll need Python 3 installed. If you don't have Python 3, you'll get `TypeError: 'instance has no next() method'`.
