### ISSUE TITLE
rsync -n should report problems like bad unicode chars

### ISSUE THREAD

**Issue by mfschwartz** [GoogleCloudPlatform/gsutil#358]
http://stackoverflow.com/questions/36922372/google-cloud-storage-rsync-or-cp-for-initial-upload/36922612#36922612 made me think: gsutil rsync -n should report problems (bad unicode chars, broken symlinks etc.) so the user knows what needs to be fixed before they start the real job.

**Comment by thobrla** [comment]
gsutil 4.20 included https://github.com/GoogleCloudPlatform/gsutil/commit/04ac8286263f44a95ba491678d5be3724bf90458 which attempts to open the local file.  Without actually reading the file and performing the copy we can't guarantee it will succeed (additionally, a user could introduce an invalid file after the dryrun completes), but this provides an additional layer of protection.
