### ISSUE TITLE
gsutil signurl dependency pyopenssl library is missing on windows

### ISSUE THREAD

**Issue by iamianmiller** [GoogleCloudPlatform/gsutil#362]
I installed the google cloud sdk on windows 10 using bundled python (since my local installation is python 3).  When I attempt to use the signurl command it errors saying: 

> > gsutil signurl -d 1000s keyfile.json gs://test
> CommandException: The signurl command requires the pyopenssl library (try pip install pyopenssl or easy_install pyopenssl)

This may be intentional behavior but the suggested fix does not work when using bundled python because pip is neither on the path or installed with bundled python at all.

**Comment by thobrla** [comment]
gsutil doesn't (yet) support python 3, so I think this is working as intended for now.

**Comment by iamianmiller** [comment]
I realize that, I'm using with bundled python so that's the problem.  Regardless of what version of python you do or do not have installed running `pip install pyopenssl ` doesn't fix it because 1) it will run it in your installed python, not bundled python so the dependency will still be missing even if it completes successfully and 2) pip isn't included with bundled python.

**Comment by houglum** [comment]
If I'm not mistaken, you should be able to run pip using the Python installation of your choice.  The bundled version of Python includes version 2.7.10, which comes with the ensurepip package.  _Assuming you're in the bundledpython directory_, you could run this command to install pip:

`python.exe -m ensurepip`

Note that you may need to run your shell as an administrator, depending on where your Cloud SDK installation resides.

After you've installed pip, you can then run this command to install pyopenssl:

`python.exe -m pip install pyopenssl`

**Comment by iamianmiller** [comment]
Thanks @houglum.  That did work.  It still seems to me like pyopenssl should be installed by default though.

**Comment by thobrla** [comment]
Sorry for the confusion on Python 3 vs. bundled Python.  Glad you have a workaround for now.  I agree that pyopenssl should be installed with the bundled Python.

**Comment by mitulpanch** [comment]
Any Updates on this?
after installing 2.7.10 and 
python.exe -m pip install pyopenssl
i am not able to solve this problem

**Comment by thobrla** [comment]
gsutil doesn't control the bundle - could you open an issue on the [gcloud issue tracker](https://code.google.com/p/google-cloud-sdk/issues/list)?

**Comment by cherba** [comment]
If you originally installed cloud sdk with bundled python, but now have your own python 2.7 installation, you can set environment variable
  CLOUDSDK_PYTHON="PATH TO PYTHON executable"

running gcloud should now use your installed version.

**Comment by mitulpanch** [comment]
Thanks for Reply.
It is Solved now. I have installed Google SDK without Bundled Python. and Installed Python from Pyhton.org source with (Python.exe pip install pyopenssl).

**Comment by iamianmiller** [comment]
@thobrla , was the issue created in glcoud issue tracker?  If so can you add a link?

**Comment by thobrla** [comment]
Opened [this issue](https://code.google.com/p/google-cloud-sdk/issues/detail?id=1493) in gcloud issue tracker.
