### ISSUE TITLE
gsutil hash on Cloud files

### ISSUE THREAD

**Issue by tmfromer** [GoogleCloudPlatform/gsutil#369]
Hi,

Just for convenience, it would be nice if running:
gsutil hash gs://URL

would not error out with:
CommandException: "hash" command requires a file URL

Rather, it would be useful to redirect to the analogous output currently available from:
ls -L

**Comment by thobrla** [comment]
Good suggestion - would be happy to accept a pull request for this.  One detail that would need to be resolved is what to do when a certain hash type is not available for a cloud object (for example, a composite object that has no stored MD5).

**Comment by KosherBacon** [comment]
This feature has been added in 8ce30b9df7e4963013eaa3820805b434087d5a9b and will be included in gsutil v4.21.
