### ISSUE TITLE
very slow reading on "Computing MD5 for ..."

### ISSUE THREAD

**Issue by jdiercks** [GoogleCloudPlatform/gsutil#370]
On an rsync -r, I seem to be stuck at "Computing MD5 for ..."

The file in question is about 280GB. According to "pv", gsutil appears to be reading it at only about 2MiB/s, and it's on a local HDD that should be reading more like 150MiB/s.

I just updated to 4.20. Not sure if that's just correlation or causality, but I didn't think this was happening before.

What could be causing it to read so slowly? Thanks.

**Comment by jdiercks** [comment]
D'oh...

I just read the message:

WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".

Will follow up on that.

**Comment by thobrla** [comment]
As a note, after one slow sync, future syncs will be fast (because gsutil 4.20 will propagate the mtime).
