### ISSUE TITLE
apt-get upgrade gsutil throwing syntax error

### ISSUE THREAD

**Issue by jdsantiagojr** [GoogleCloudPlatform/gsutil#380]
Created new Debian 8 VM instance and ran apt-get upgrade. Google cloud SDK threw the following error.

Compiling platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py ...
  File "platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 347
    print('%s:' % h, end=' ', file=self._fp)
                        ^
SyntaxError: invalid syntax

**Comment by houglum** [comment]
Thanks for the report.  I can reproduce this consistently as well.  It looks like when gcloud is installed via package manager, it tries to compile all of the Python files in certain directories under the gcloud tree.  The file mentioned is a Python3 script (which we don't use, as gsutil doesn't currently support running under Python3) in one of our third-party submodules; attempting to compile it as Python2 code fails, of course :)

This should not affect the actual gcloud installation process, as it continues if an error is encountered when trying to compile the Python files.  The update process continues and finishes, and both gsutil and gcloud are updated to their new versions.

However, as the error message might still raise concerns, I'll let our gcloud team know and see what we can do.

**Comment by jdsantiagojr** [comment]
Very cool. Thank you.
