### ISSUE TITLE
gsutil ls doesn't list all objects in gs-bucket anymore (critical)...

### ISSUE THREAD

**Issue by dreispur** [GoogleCloudPlatform/gsutil#393]
**Note:** Originally filed [here](https://code.google.com/p/google-cloud-sdk/issues/detail?id=1380).

**What steps will reproduce the problem?**

1. List objects in gs-bucket via gsutil ls (or even via Cyberduck or API-based software)
2. Some files are missing from the list
3. Missing files are still visible in gs-webinterface and even accessible by objectname directly via gsutil

**What is the expected output? What do you see instead?**

All files in the bucket should be listed. We are running a production-system that relies on this fact, that is broken since a few days because of this... :-(

**Please provide any additional information below.**

This used to work perfectly for years. Files only started to be missing from listings for the last couple of days.

I could supply you with a project-id, bucket-name and object-name, where the object-name is missing from listings every time, but accessible by name directly. You should be able to easily reproduce it. I would prefer to keep project-id and bucket-name non-public though because customer-data is involved. Could someone able to see what might go wrong backstage contact me by pm for this? It's not an acl-issue, I'm doing the gsutil ls as the owner of the files.

**Comment by thobrla** [comment]
Did you recently change gsutil versions?  Listing of Google Cloud Storage buckets is eventually consistent (see [Eventually Consistent Operations](https://cloud.google.com/storage/docs/consistency#eventually_consistent_operations)), so basing your production system on consistent listing results is problematic.

Objects will always be accessible via direct name.  The web interface is also eventually consistent - in your case, it is likely hitting a different set of servers that happen have an up-to-date listing.

**Comment by thobrla** [comment]
Based on email follow-up, we discovered this was an issue with the Google Cloud Storage service that impacted buckets meeting very specific criteria (a subset of buckets created prior to 2015, in US location, with many pages of object listings results).  That issue is now fixed, so I'm closing this issue.

**Comment by thobrla** [comment]
Brief correction: the service issue only affected certain buckets created in 2013 or earlier (I erroneously claimed 2015 above).
