### ISSUE TITLE
[] characters in a name

### ISSUE THREAD

**Issue by Enelar** [GoogleCloudPlatform/gsutil#395]
Obviously many file systems allows wider character set than url notation do. And it may be impractical to support them all. Moreover some limitation cannot be workaround-ed. (Like total file path length - it may exceed W3C get request length).

I was unable to find GCS limitation either. **Issue:** Tool doesn't upload files with `[]` characters.

Proposed fix: add parameter that would translate *unwanted* unicode characters into url notation.

It may be just `gsutil` bug, then i can test set of common used characters.

1. [Filesystem comparison](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)
2. [GET request limitations](https://tools.ietf.org/html/rfc3986)

```
Linux 4.8.10-300.fc25.x86_64
Fedora 25 Cinnamon 3.2.2
btrfs 4.6.1
Google Cloud SDK 135.0.0
bq 2.0.24
bq-nix 2.0.24
core 2016.11.11
core-nix 2016.11.11
gcloud 
gsutil 4.22
gsutil-nix 4.22
```

**Comment by thobrla** [comment]
This was reported previously in https://github.com/GoogleCloudPlatform/gsutil/issues/290.  This is an issue with `gsutil` that we're unlikely to fix in the near future.

**Comment by thobrla** [comment]
Closing this since it is a duplicate report.

**Comment by Enelar** [comment]
Sounds like it wont be fixed at all. That issue reported more than year ago.
Any suggestions where to start?

**Comment by thobrla** [comment]
Yes, gsutil team doesn't plan on fixing this anytime soon.  Note that we strongly recommend against using these characters in object names in [Object Naming Requirements](https://cloud.google.com/storage/docs/naming#objectnames).

Is there a specific requirement for you to have filenames with bracket characters?  Possible approaches include:
- Change file/directory names not to include wildcard characters.
- Use a non-`gsutil` tool (such as curl) to work with all such files/objects.
- Contribute a "raw mode" option to gsutil that ignores wildcards and other special characters.  gsutil team can provide design and code guidance but even with that, this is a fairly substantial engineering effort.
