### ISSUE TITLE
Why is it required to has _usingExtension flag in crcmod library?

### ISSUE THREAD

**Issue by dimorinny** [GoogleCloudPlatform/gsutil#396]
In this [library](https://github.com/gsutil-mirrors/crcmod/blob/master/python2/crcmod/crcmod.py#L40-L42) described that this extension is not required for the correct functioning of the library.

**Comment by thobrla** [comment]
See `gsutil help crcmod`.  The comments that you linked also provide a hint - while it functions correctly, the performance suffers.  In our testing, performance suffered to the extent where it was a significant bottleneck.
