### ISSUE TITLE
Warning message: proxy configuration is different in boto and HTTP_PROXY

### ISSUE THREAD

**Issue by chemnic** [GoogleCloudPlatform/gsutil#398]
Hi

When I execute gsutil to work in a bucket I get this warning:

    root@server:~# /opt/gsutil/gsutil du -sh gs://somebukcket
    WARNING: Proxy configuration is present in both the http_proxy
    environment variable and boto configuration, but configuration
    differs. boto configuration proxy values will be used. Differences
    detected:
    Boto proxy user: "someuser@somedomain.lan" differs from http_proxy proxy user
    "somedomain%40somedomain.lan"
    Boto proxy password differs from http_proxy proxy password
    WARNING: Proxy configuration is present in both the https_proxy
    environment variable and boto configuration, but configuration
    differs. boto configuration proxy values will be used. Differences
    detected:
    Boto proxy user: "someuser@somedomain.lan" differs from https_proxy proxy user:
    "somedomain%40somedomain.lan"
    Boto proxy password differs from https_proxy proxy password
    WARNING: Proxy configuration is present in both the HTTPS_PROXY
    environment variable and boto configuration, but configuration
    differs. boto configuration proxy values will be used. Differences
    detected:
    Boto proxy user: "someuser@somedomain.lan" differs from HTTPS_PROXY proxy user:
    "somedomain%40somedomain.lan"
    Boto proxy password differs from HTTPS_PROXY proxy password
    440.19 GiB  gs://somebucket

The message is right. They are different.

My proxy server uses user names in the form "someuser@somedomain.lan", and some applications need to be configured with URL encoded, like this: "someuser%40somedomain.lan".

For that reason I have configured the file /etc/environment with the user as encoded URL, example:

HTTP_PROXY='http://somesuer%40somedomain.lan:somepassword@192.168.1.1:3128/'

That works well for WGET or CURL, but gsutil can't handle the proxy configuration that way. So I just configured the boto file with user "someuser@somedomain;lan" and it works. But I get that ugly message.

How can I get rid of the message? I tried with option -q, but it shows anyway.

Thank you.

**Comment by thobrla** [comment]
-q only eliminates informational output, not warnings or errors.

Could you wrap calls to gsutil to clear the environment variable?  Something like:
`HTTPS_PROXY='' gsutil du -sh gs://somebucket`

**Comment by chemnic** [comment]
That works. Thank you.

**Comment by mherbert** [comment]
For anyone landing on this page while searching for this error message, note it's also likely to appear just because gsutil doesn't support two different locations for http_proxy and https_proxy. More details at https://github.com/GoogleCloudPlatform/gsutil/commit/b1ece8cf0da1e9e4d05f12a58ff40f8f98548a7d#r24165452
