### ISSUE TITLE
Google Cloud SDK  Installation Failling in Windows

### ISSUE THREAD

**Issue by SyCode7** [GoogleCloudPlatform/gsutil#399]
Hi, I have tried for the last 24 hours to install the Google Cloud SDK with no success. i even tried installing on another laptop to be sure the issue is not from the first machine, but I encountered the same errors. Efforts to install gsutil as a standalone also failed with the error `ImportError: No module named apitools.base.py`.

**Comment by thobrla** [comment]
For Cloud SDK issues, consider posting an issue on the [Cloud SDK Issues tracker](https://code.google.com/p/google-cloud-sdk/issues/list).

For the gsutil standalone install, can you describe in more detail how you installed it as standalone, and provide a `gsutil -D <your-command>` log of the failure?

**Comment by houglum** [comment]
As there's been no response in months and I'm unable to reproduce this after trying on several Windows machines, I'm going to go ahead and close this.
