### ISSUE TITLE
gsutil cp and cat commands do not uncompress gzip compressed bucket file when sending to stdout

### ISSUE THREAD

**Issue by amplexus** [GoogleCloudPlatform/gsutil#400]
**What steps will reproduce the problem?**

Upload a text file with gzip compression to a bucket:

> gsutil -v
> gsutil version: 4.21
> 
> gsutil cp -Z some-file.txt gs://some-bucket/

Then use gsutil cat or gsutil cp to display that file to stdout.

> gsutil cat gs://some-bucket/some-file.txt
> gsutil cp  gs://some-bucket/some-file.txt -

**What is the expected output? What do you see instead?**

Expect the unzipped contents of the file to be displayed to stdout. Instead, the raw zip binary file is displayed to stdout.

**Comment by thobrla** [comment]
GzipFile in Python 2.7 doesn't support streaming (see [this excellent writeup](http://www.enricozini.org/blog/2011/cazzeggio/python-gzip/)), so gsutil would need to roll its own streaming gzip implementation to support this.  gsutil team is unlikely to implement that anytime soon, but would consider a code contribution of this functionality.

In the meantime, as a workaround, you can borrow gunzip's streaming functionality:
`gsutil cat gs://somebucket/somefile.txt | gunzip -c`

I realize this doesn't work well if you have a mixed-mode bucket where some files are zipped and others aren't.

**Comment by amplexus** [comment]
Yeah that was the workaround I used. Just seemed a bit odd that compression was handled transparently for files going in, but not for files coming out. 

No problem. I can live without this feature :dancer:

**Comment by in42** [comment]
According to this page: https://cloud.google.com/storage/docs/transcoding, shouldn't the decompression occur on the server side?
