### ISSUE TITLE
gsutil -m cp gcs to s3 - missed copying few files occasionally

### ISSUE THREAD

**Issue by krmettu** [GoogleCloudPlatform/gsutil#401]
We have been using the following in production for over a month. In 2 occasions it missed copying some files. gsutil command copied 19 files out of 24 files. Another occasion , it copied 23 files.

gsutil -m cp gs://folder_name/input/date/*.csv.gz  s3://folder/input/date/

I am running this cmd from AWS EC2 instances in US-west (Oregon)
Any tips on how to troubleshoot ? Are there any known bugs with gsutil cp -m  ?

**Comment by thobrla** [comment]
Copying with wildcards relies on listing in Google Cloud Storage which are eventually consistent.  Did you see specific errors during the copy, or did it appear that some objects were not attempted?

**Comment by thobrla** [comment]
In this past week there was a Google Cloud Storage issue that made eventual consistency [worse than usual](https://status.cloud.google.com/incident/storage/16036).  Even discounting that, though, eventual listing consistency means that gsutil may not be able to enumerate new files for the copy immediately after they're created.

**Comment by krmettu** [comment]
@thobrla  sorry i never got an email alert with this note (or overlooked , sorry).   To give a background - I am copying files to gcs from bigquery jobs and to S3. What is the time on eventual consistency ? is it few minutes or hours ?   I can send a private msg with our account information if that helps. Thanks.

**Comment by thobrla** [comment]
There's no guaranteed bound.  Typically it's on the order of seconds, but in rare cases it can be much longer.  Note that GCS regional buckets have [strongly consistent object listing](https://cloud.google.com/storage/docs/consistency#strongly_consistent_operations) now, so if your source GCS folder is in a regional bucket, this should not be an issue.

**Comment by krmettu** [comment]
thanks @thobrla

**Comment by ccjon** [comment]
For the record, in case anyone like me who runs across this now researching the same symptoms, there doesn't appear to be any difference in consistency between regional and global buckets in GCS anymore: the document at that link above above doesn't make any distinctions. I'm clearly assuming the omission is intended and an assertion here, which may not me correct, but I don't see any 'regional' scoping to the doc.
