### ISSUE TITLE
stuck on "catching up md5..."

### ISSUE THREAD

**Issue by jdiercks** [GoogleCloudPlatform/gsutil#404]
I *do* have compiled crcmod, so that's not it. Any other ideas why this is taking so long? Thanks.

debug log:
http://pastebin.com/D9cpnf9v

**Comment by mfschwartz** [comment]
How big is the file you're uploading? I've seen cases where it legitimately takes hours to catch up the MD5 computation (e.g., upload a 1 TB file, failing 2/3 the way through it, so gsutil has to read and compute MD5 over 667 GB before resuming the upload)

**Comment by jdiercks** [comment]
It's a little over 300GB. Not sure how far it had gotten before trying to catch up md5. Guess I'll just wait it out. I'd been hoping to avoid slicing backup files into chunks before uploading them, but this might it necessary.

**Comment by mfschwartz** [comment]
Does it look like the process is doing much (e.g., from the top and/or iostat commands)?

Also, if the gsutil command is running single-threaded in the foreground, you can type ^\ (to send SIGQUIT) and it will drop you into the Python debugger. From there you can type "where" to see a stacktrace of what gsutil is currently doing. If it's catching up the MD5 it should look something like the following (note the "_CalculateB64EncodedHashFromContents" function call). Once you're done with that you can type "c" to make gsutil continue:

(Pdb) w
  /usr/local/gsutil/gsutil(22)<module>()
-> gsutil.RunMain()
  /usr/local/gsutil4/gsutil.py(113)RunMain()
-> sys.exit(gslib.__main__.main())
  /usr/local/gsutil4/gslib/__main__.py(383)main()
-> perf_trace_token=perf_trace_token)
  /usr/local/gsutil4/gslib/__main__.py(577)_RunNamedCommandAndHandleExceptions()
-> collect_analytics=True)
  /usr/local/gsutil4/gslib/command_runner.py(299)RunNamedCommand()
-> return_code = command_inst.RunCommand()
  /usr/local/gsutil4/gslib/commands/cp.py(1067)RunCommand()
-> seek_ahead_iterator=seek_ahead_iterator)
  /usr/local/gsutil4/gslib/command.py(1362)Apply()
-> arg_checker, should_return_results, fail_on_error)
  /usr/local/gsutil4/gslib/command.py(1433)_SequentialApply()
-> worker_thread.PerformTask(task, self)
  /usr/local/gsutil4/gslib/command.py(2089)PerformTask()
-> results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  /usr/local/gsutil4/gslib/commands/cp.py(740)_CopyFuncWrapper()
-> preserve_posix=cls.preserve_posix_attrs)
  /usr/local/gsutil4/gslib/commands/cp.py(932)CopyFunc()
-> preserve_posix=preserve_posix))
  /usr/local/gsutil4/gslib/copy_helper.py(3286)PerformCopy()
-> allow_splitting=allow_splitting)
  /usr/local/gsutil4/gslib/copy_helper.py(1786)_UploadFileToObject()
-> gsutil_api, command_obj, copy_exception_handler, logger)
  /usr/local/gsutil4/gslib/copy_helper.py(1028)_DoParallelCompositeUpload()
-> gsutil_api))
  /usr/local/gsutil4/gslib/copy_helper.py(3574)FilterExistingComponents()
-> content_md5 = CalculateB64EncodedMd5FromContents(file_part)
  /usr/local/gsutil4/gslib/hashing_helper.py(236)CalculateB64EncodedMd5FromContents()
-> return _CalculateB64EncodedHashFromContents(fp, md5())
  /usr/local/gsutil4/gslib/hashing_helper.py(283)_CalculateB64EncodedHashFromContents()
-> return Base64EncodeHash(_CalculateHashFromContents(fp, hash_alg))
  /usr/local/gsutil4/gslib/hashing_helper.py(185)_CalculateHashFromContents()
-> CalculateHashesFromContents(fp, hash_dict)
  /usr/local/gsutil4/gslib/hashing_helper.py(201)CalculateHashesFromContents()
-> data = fp.read(DEFAULT_FILE_BUFFER_SIZE)
  /usr/local/gsutil4/gslib/file_part.py(61)read()
-> return self._fp.read(max(0, size))
  /usr/local/gsutil4/gslib/sig_handling.py(87)_SignalHandler()
-> handler(signal_num, cur_stack_frame)
> /usr/local/gsutil4/gslib/__main__.py(479)_HandleSigQuit()->None
-> pdb.set_trace()

**Comment by jdiercks** [comment]
It eventually did catch up, so I'm letting it run, but thanks very much for the debugging tip, I'll tuck that away for future reference, should come in handy!
