### ISSUE TITLE
gsutil support removed for filenames with wildcards

### ISSUE THREAD

**Issue by eatnumber1** [GoogleCloudPlatform/gsutil#405]
I see that in 46c09952d137e8704c1209bb8bdfbb2e73a2cd5d, cloud folders with wildcards in their names were outright banned.

By simply banning this, you've made nearly all of my files virtually inaccessible to me, since nearly all of them contain `[`, are in a directory that contains `[`, or are in a directory with another file that contains `[`. The only other way I've been able to access my files is through the cloud console, whose file management capabilities are rudimentary enough to not meet my needs.

Apparently I'm not the only one who's run into this, as there's at least one [stackoverflow](http://stackoverflow.com/questions/36780004/gsutil-cant-touch-a-file-with-brackets-in-the-name) question on the subject.

I'm unsure if I should call this a bug or a feature request, considering that the loss of this functionality is technically a regression; albeit an intentional one. That said, please implement support soon! 💯

**Comment by thobrla** [comment]
This is the same issue as https://github.com/GoogleCloudPlatform/gsutil/issues/290, so let's discuss there.
