### ISSUE TITLE
trickle + gsutil -m rsync -r hangs

### ISSUE THREAD

**Issue by wojtczyk** [GoogleCloudPlatform/gsutil#413]
Followed instructions found here:
https://cloud.google.com/storage/docs/gsutil/addlhelp/Throttlinggsutil
to limit the upload bandwidth of gsutil rsync after it jammed our uplink over the weekend.

However gsutil now just hangs after computing the remote MD5 sums. No progress on file upload, no bandwidth utilization.
The command was:
trickle -u 1024 gsutil -m rsync -r local_dir gs://remote_dir

**Comment by houglum** [comment]
I can also reproduce this, even when just rsyncing a few small objects.  From a bit of searching, it looks like trickle exhibits this behavior for several other programs, most notably those that run a lot of subprocesses and/or threads (e.g. see https://github.com/aws/aws-cli/issues/1215).

Logically, if you're limiting your bandwidth to such a low value anyway, you probably aren't going to get much use out of running several processes (via -m).  I was unable to reproduce this problem when running the same command without the -m flag, so I'd recommend giving that a shot. I'll also see about getting the -m removed from the sample command in our docs.

**Comment by wojtczyk** [comment]
Thank you for your reply! I have not tried trickle with a single-process gsutil, yet, but will give it a try.

What has been working for me for the last 2 days now (upload still in progress without anybody complaining):
- no trickle
- no option -m for gsutil rsync

This way gsutil seems to utilize the uplink up to the max, but gives way when other processes need bandwidth. 
- gsutil -m rsync without trickle would clog the line
- trickle -u 1024 gsutil -m rsync would have gsutil hang

**Comment by houglum** [comment]
Fixed docs with https://github.com/GoogleCloudPlatform/gsutil/commit/866b7164a0b50d0440de6de3a645ee1b69dd7079.

**Comment by wojtczyk** [comment]
Thank you!
