### ISSUE TITLE
Feature request: gsutil rsync option -d age parameter

### ISSUE THREAD

**Issue by wolfv6** [GoogleCloudPlatform/gsutil#416]
Please add an age parameter to gsutil rsync option -d.

Example: if extra file is not found under under src_url, flag extra file under dst_url for deletion in 90 days:

    $ gsutil rsync -d 90 src_url dst_url

Useful because we might want to restore a deleted file in a few weeks, but we don't want to backup old files forever.

**Comment by thobrla** [comment]
GCS doesn't support delayed deletion feature in the service, so this is probably not feasible.

Would [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) (which you can set with `gsutil lifecycle`) address your use case?

Note that rsync -d in Linux means "transfer directories without recursing", so if we did implement such a feature we should probably use a different name for the option.

**Comment by wolfv6** [comment]
Thanks thorbria.
I submitted a feature request at https://cloud.google.com/storage/docs/lifecycle > SEND FEEDBACK.
