### ISSUE TITLE
Wrong argument in gsutil help information 

### ISSUE THREAD

**Issue by nguyenvietyen** [GoogleCloudPlatform/gsutil#426]
Very minor documentation detail.

When doing `gsutil notification --help` it shows 

```
  gsutil notification create -f (json|none) [-p prefix] [-t topic] \
      [-m key:value]... [-t eventType]... bucket_url
```

the option -t eventType should be -e eventType instead.

**Comment by houglum** [comment]
Just recently fixed this in https://github.com/GoogleCloudPlatform/gsutil/commit/866b7164a0b50d0440de6de3a645ee1b69dd7079. This will go out with the next release (v4.26).
