### ISSUE TITLE
gsutil rsync suddenly returning AccessDeniedException: 403 Caller does not have storage.objects.list access to bucket

### ISSUE THREAD

**Issue by Catchwa** [GoogleCloudPlatform/gsutil#428]
I've been doing regular syncs to my nearline bucket like so:
gsutil rsync -r /mnt/backup gs://my-bucket-name

It's suddenly stopped working and the only thing I can see that's change is that I've updated from google-cloud-sdk 151.0.0-0 to 152.0.0-0 (running Ubuntu 16.04) (but gsutil wasn't updated according to the changelog..)

I'm logged in as myself (i.e. I'm the project creator and I have owner permissions to everything), have tried deleting all configuration and going back to scratch (i.e. apt-get purge, etc.) - same issue.

The error message I'm getting is:
AccessDeniedException: 403 Caller does not have storage.objects.list access to bucket my-bucket-name

...but this worked a few days ago and I can login to the storage console and still see everything, etc.
I've looked at the recent changes and can't see anything that would have caused this to stop working. How can I debug any further?

Have attached log of:
gsutil -D rsync -r /mnt/backup gs://my-bucket-name > log.txt 2>&1
[log.txt](https://github.com/GoogleCloudPlatform/gsutil/files/949578/log.txt)

**Comment by houglum** [comment]
Can you list the objects in this bucket via `gsutil ls gs://my-bucket-name`?  I'd expect you get the same error from that command.

From your output, you're using gsutil through gcloud, which passes credentials from `gcloud auth login` for whatever user is active.  Try checking the output of `gcloud config list` and see if the correct account and configuration are set.

If these appear correct, and you also get the same error from the ls command above, the permissions on the bucket may have changed such that you're not allowed to list the contents -- you can check the bucket's last modification time and existing ACLs via `gsutil ls -Lb gs://my-bucket-name`, which might help confirm or eliminate this possibility.

**Comment by Catchwa** [comment]
Thanks @houglum for your suggestions. In a very strange turn of events, I've logged back in this morning and everything is working ok. I'll close this for now and keep an eye on it.
