### ISSUE TITLE
Preserved ACLs Cannot be Restored

### ISSUE THREAD

**Issue by eatnumber1** [GoogleCloudPlatform/gsutil#440]
With files which have previously been copied into the cloud via `gsutil rsync -p -P`, copying those files back to the local machine using `gsutil rsync -p -P` fails with the following error: `No OWNER permission found for object [...]`. This is because the ACL is not fetched when [querying the object's metadata](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/copy_helper.py#L2981-L2992).

I'm able to fix this issue locally by adding the following code to [`GetSourceFieldsNeededForCopy`](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/copy_helper.py#L2928):
```diff
--- a/copy_helper.py  2017-06-30 14:00:46.000000000 -0700
+++ b/copy_helper.py    2017-06-30 14:11:30.000000000 -0700
@@ -2990,9 +2990,6 @@
                       'metadata/%s' % GID_ATTR, 'metadata/%s' % MODE_ATTR,
                       'metadata/%s' % UID_ATTR]
       src_obj_fields_set.update(posix_fields)
+    # We only need the ACL if we're going to preserve it.
+    if preserve_acl:
+      src_obj_fields_set.update(['acl'])
 
   if delete_source:
     src_obj_fields_set.update(['storageClass', 'timeCreated'])
```

**Comment by thobrla** [comment]
Since ACLs aren't written to local files, it doesn't seem to me like `gsutil` should bother trying to preserve them.  I think a better fix would be not to raise the `No OWNER permission ...` error when copying to a local file.

**Comment by eatnumber1** [comment]
Agreed, although I'd want other file attributes (e.g. mtime) to be preserved.

**Comment by thobrla** [comment]
Agreed - those should still be preserved due to the to `-P` flag.

**Comment by thobrla** [comment]
FYI - I have a fix out for internal review.
