### ISSUE TITLE
gsutil cors set complains about unicode / iteritems

### ISSUE THREAD

**Issue by danvk** [GoogleCloudPlatform/gsutil#441]
I'm trying to make my bucket serve with an open CORS header, but I'm getting an odd Python error:

```
$ gsutil cors set /tmp/public.cors.json gs://my-bucket
Setting CORS on gs://my-bucket/...
'unicode' object has no attribute 'iteritems'

$ cat /tmp/public.cors.json
{
  "origin": ["*"],
  "method": ["*"],
  "responseHeader": ["*"]
}

$ python --version
Python 2.7.13

$ gsutil --version
gsutil version: 4.25
```

I'm on Ubuntu.

**Comment by houglum** [comment]
Looks like your formatting is a bit off.  The docs at [1] suggest that you should have that JSON object nested in a list, e.g.:

```
[
  {
    "origin": ["*"],
    "method": ["*"],
    "responseHeader": ["*"]
  }
]
```

[1] https://cloud.google.com/storage/docs/gsutil/commands/cors

**Comment by danvk** [comment]
Thanks @houglum that did the trick. Perhaps `gsutil` could validate its inputs to generate a better error?
