### ISSUE TITLE
Allow more than 1000 objects to be listed with `gsutil ls`

### ISSUE THREAD

**Issue by greggdonovan** [GoogleCloudPlatform/gsutil#443]
`gsutil ls gs://my-bucket-with-many-objects` will not list more than 1000 objects, the default page size. 

It would be great to provide a way to page through results.

**Comment by mfschwartz** [comment]
gsutil handles paginating through buckets with more than 1000 objects. Can you post additional details about what you tried that didn't work?

**Comment by greggdonovan** [comment]
My apologies, @mfschwartz. Turns out I was running `gsutil` on a bucket with exactly 1000 objects. When I run `gsutil` on a bucket with 1500 objects, it handles the paging.

I'll close this issue.
