### ISSUE TITLE
always-on tmpfile

### ISSUE THREAD

**Issue by mrgleeco** [GoogleCloudPlatform/gsutil#445]
i recently was surprised to find millions of ~800 byte temp files  in tmp dir due to the `gsutil` always-on tmpfile as seen in [metrics.py](https://github.com/GoogleCloudPlatform/gsutil/blob/9843d8bdc7c167857545d6a52216bdf3c4f34bfb/gslib/metrics.py#L713)

while i appreciate y'all might be collecting metrics to improve this service, this has the potential to bomb out servers, and feels a rather invasive bit of data collection.  I'll speculate that it also has potential to slow down gs:// performance in the critical path.

hopefully a default of OFF will be considered

**Comment by thobrla** [comment]
That is surprising - the metrics reporter should be removing those files here: https://github.com/GoogleCloudPlatform/gsutil/blob/9843d8bdc7c167857545d6a52216bdf3c4f34bfb/gslib/metrics_reporter.py#L66

Perhaps the reporter itself is crashing?  Do you see any evidence of this on your system?
