### ISSUE TITLE
allow gsutil cp/mv to specify destination URIs with subdirectory-like paths

### ISSUE THREAD

**Issue by jterrace** [GoogleCloudPlatform/gsutil#45]
_Original author: mfschwa...@google.com (October 15, 2010 16:03:06)_

This enhancement was suggested by a question posted on gsutil-discuss@googlegroups.com, included below. This would be useful, for example allowing users to rename &quot;subdirectories&quot; on the cloud server.

---

from    Kevin Postal &lt;kevindpostal@gmail.com&gt;
reply-to    gsutil-discuss@googlegroups.com
to  gsutil-discuss &lt;gsutil-discuss@googlegroups.com&gt;
date    Thu, Oct 14, 2010 at 5:18 PM
subject Uploading files and directories to folders
mailing list    &lt;gsutil-discuss.googlegroups.com&gt;

I was wondering if there was a way to upload Full folders to folder
buckets?

For instance I know I can do:

   gsutil cp file/file.txt gs://my_bucket/file/file.txt
   gsutil cp file/file.txt gs://my_bucket/file/

Why can't I do?

   gsutil cp file/\* gs://my_bucket/file/*

   or

   gsutil cp file/ gs://my_bucket/file/

_Original issue: http://code.google.com/p/gsutil/issues/detail?id=45_

**Comment by kevinpostal** [comment]
Forgot about this.. all that way back in 2010 :) Glad to see the issue was resolved in gsutil 3.0
