### ISSUE TITLE
 ServiceException: 401 Anonymous users ...

### ISSUE THREAD

**Issue by tcourregesJC** [GoogleCloudPlatform/gsutil#457]
Hi! I'm getting this error when trying to download files from buckets:

 ServiceException: 401 Anonymous users does not have storage.objects.get access to object ...csv

I'm running the command in a remote server running CentOS. When i run the command via sh, it runs okay and it lets me downlaod the file.  But since i have to download multiple files daily i've made a Python script to download this files that then are processed into a data warehouse. That ServiceExpcetion is only triggered when i run it via the python script.

Any ideas? Thanks!

**Comment by houglum** [comment]
The user running the Python script is probably different than the one you're normally running gsutil as.  Regardless of whether you're using your ~/.boto file for auth or having gcloud pass in credentials (which happens if you're using gsutil as installed with the gcloud sdk and have run `gcloud auth login`), those methods look for auth configurations corresponding to the user running gsutil -- e.g. ~/.boto might expand to /home/matt/.boto, but if I were running as root, it would look for /root/.boto.  If you check the output of `gsutil -D version -l` for both ways of invoking gsutil (as your user and via the script), you'll likely see a difference in config files being loaded -- look for the "config path(s):" line in both sets of output.

**Comment by houglum** [comment]
Marking this as closed; feel free to reopen if you can provide additional evidence that this wasn't an issue with the points I mentioned above.

**Comment by tcourregesJC** [comment]
Hi @houglum, as you mentioned it was a different config file. I solved this by providing the full path to gsutil while executing.
Thanks!

**Comment by HarmeetSokhi** [comment]
Hi @houglum I have the similar issue.  when I execute gsutil on Jenkins installed on EC2 it works fine
but when it runs on Jenkins which is also installed on EC2 .it failes with anonymous user.I did follow setup steps by running python gsutil config and it created the file in /root/.boto.

My jenkins is in /var/lib/jenkins/google-cloud-sdk/platform/gsutil.

I am not able to resolve this .Please advise

**Comment by HarmeetSokhi** [comment]
It seems that the issue was due to multiple versions of gsutil .I deleted everything and every trace of gcloud and then reinstalled. It started working then. Thankyou.

**Comment by roman-cnd** [comment]
Why is this utility not using credentials from gcloud?!
Ugh, google style yet again :(

**Comment by houglum** [comment]
It **does** use credentials from gcloud, if you're launching gsutil through the gcloud wrapper script for gsutil:

    $ type gsutil
    gsutil is hashed (/Users/houglum/google-cloud-sdk/bin/gsutil)

In the normal case, this Just Works (tm).  There are some edge cases that complicate credential management, though:
-  As noted above, gcloud will pass credentials stored *for the user launching it* along to gsutil.  If you set up your gcloud credentials as the user "Matt", then you try to run gcloud/gsutil as "root", gcloud will look for root's credentials, not Matt's.
-  We also support installing gsutil through other means (via `pip`, or download from tarball/zip).  While this is convenient for some use cases, it also complicates credential management if you have multiple installation styles present on your host -- launching gsutil from one of those "standalone" installations will mean gcloud cannot pass its credentials (via the wrapper script mentioned above) to gsutil.

**Comment by roman-cnd** [comment]
Thanks, Matt. I still can't figure out why it doesn't work.

Is it possible to point this thing to a gce key file? So it would pick it up from there, without any wrapper scripts, shims, python env and so on and so forth...

**Comment by roman-cnd** [comment]
Ok, `gsutil config -e` can created config but man - 370 lines...

**Comment by samarth-math** [comment]
A simple solution that fixed this for me:
`pip uninstall gsutil`

simply removed the pip-installed gsutil, and trying which gsutil after that pointed to the gcloud installed version, which started picking up credentials correctly after that.
