### ISSUE TITLE
crcmod probe/fallback logic doesn't actually work

### ISSUE THREAD

**Issue by vapier** [GoogleCloudPlatform/gsutil#462]
the gsutil.py file has this bit of code:
```py
try:
  # pylint: disable=g-import-not-at-top
  import crcmod
except ImportError:
  crcmod = None

if not UsingCrcmodExtension(crcmod):
  local_crcmod_path = (CRCMOD_OSX_PATH
                       if 'darwin' in str(sys.platform).lower()
                       else CRCMOD_PATH)
  sys.path.insert(0, local_crcmod_path)
```

basically it tries to import the system copy of `crcmod` to probe it for compiled support.  if the system version is found lacking, it tries to update the sys.path to search the bundled copy of crcmod instead.  unfortunately, that doesn't actually work: the first `import crcmod` store the result in the global modules cache which means every subsequent `import crcmod` will use that cached version instead of reconsulting `sys.path`.

unfortunately, i can't seem to find a nice way of clearing the cache.  a simple `del sys.modules['crcmod']` isn't sufficient as crcmod itself imports a few more modules that stay resident (and then you get a desync with the diff versions expecting diff APIs).  deleting all modules that start with 'crcmod' seems to do the trick but it feels bad.

```py
if not UsingCrcmodExtension(crcmod):
  for mod in sys.modules.keys():
    if mod.startswith('crcmod'):
      del sys.modules[mod]
```

**Comment by houglum** [comment]
Thanks for the report - nice find.

Have you tried using [Python's reload method](https://docs.python.org/2.7/library/functions.html#reload) after the sys.path.insert line?  If that works, I'd be glad to submit a quick fix.  (If not, this will require a little more digging at some point in the future.)

**Comment by vapier** [comment]
yeah, that was the first thing i tried and it didn't seem to work for me :(.  i also tried various methods of loading/reloading with the `imp` and `importlib` modules to no avail.

**Comment by houglum** [comment]
Hm. Yeah, it seems once it's in the `sys.modules` cache, you're stuck with it (unless you modify `sys.modules` directly), especially if it imports other submodules.  While using the above heuristic of _starts with 'crcmod'_ is a bit hacky; the only way I can think of improving your workaround so that it feels a bit safer would be:

Create a `set` from `sys.modules.keys()`, import crcmod, and check if it's using the extension. If it's not, create another `set` from the new `sys.modules.keys()`, and remove the entries that were added as a result of the import (items making up the difference between _set_new_ and _set_old_)... then prepend the fallback path to `sys.path`.

**Comment by vapier** [comment]
that sounds like it should work

**Comment by houglum** [comment]
Looking at this again, adding the change I mentioned above wouldn't actually import a version of crcmod with the compiled extension.

The existing logic is there to import the bundled version of crcmod (from third_party, which _does not_ include the compiled extension under *crcmod/python2/crcmod/_crcfunext.\<system-dependent-extension-suffix\>*) if no crcmod package is already installed on the system.  The `if not UsingCrcmodExtension(crcmod):` block accounts for two cases -- either we imported crcmod from the system and it didn't have C extension support, or no crcmod package was found.  In both cases, the end result is that a crcmod module without C extension support gets imported.
