### ISSUE TITLE
Recursively deleting archived versions from bucket actually removes all objects and bucket itself

### ISSUE THREAD

**Issue by danemacmillan** [GoogleCloudPlatform/gsutil#468]
I ran `gsutil rm -r -a gs://[bucket]/` under the assumption that it would only remove all archived versions of objects in a bucket, but it actually deleted all objects in the specified bucket, and deleted the bucket itself.

I followed the advice at the bottom of https://cloud.google.com/storage/docs/using-object-versioning#delete, where it's suggests to pass the `-a` option without the version (generation) number to remove all archived versions of the specified object:

> ⭐️  **Note**: You can remove all versions of an object by using the -a flag and omitting the #[GENERATION_NUMBER].

 It's not an unreasonable leap to assume that combining the `-r` option would recursively delete all archived versions on all objects located under a bucket. That's what I did, then. Given that a bucket could contain hundreds, thousands, or millions of objects, each with archived versions, I assumed the combination of options would mean that the `gsutil` utility would recursively delete all archived versions under a bucket, and leave all live versions intact.

Is that a mistake in the docs? I definitely did not want to nuke everything.

The gsutil clearly showed that just archived versions were deleted (all of the `#[GENERATION_NUMBER]` files were shown as just deleted), but upon attempting to list the contents of the bucket, I was informed that the bucket did not exist.

```
danemacmillan@macmillanator.local ~ $ gsutil ls -r -a gs://[bucket]/
BucketNotFoundException: 404 gs://[bucket] bucket does not exist.
```

After reviewing the [`rm` docs](https://cloud.google.com/storage/docs/gsutil/commands/rm) multiple times, the best I can surmise is that `-r -a` cannot be used together, and that the combination of the two does not in fact mean that the options will recursively remove all archived versions.

The docs can definitely benefit from clarity on this point, as the operation is very nuclear. It would also be very useful if the `gsutil` utility would loudly complain when the combination of options described above is provided, and ensure the user knows what is about to happen.

In my case, the data wasn't critical, but it still permanently removed six months of backups: `Operation completed over 552 objects.`

**Comment by houglum** [comment]
The docs don't say that `-a` will removed just archived versions; they say `-a` will remove **all** versions, i.e. "Remove all the objects you normally would, *and also* archived objects."  Is it possible you made the mental jump from "a" to "archived"? Or is there somewhere in the docs that actually states this?  (If so, we should fix it.)

**Comment by danemacmillan** [comment]
You are absolutely correct. I misunderstood the meaning of the `-a` option. Given that it was a suggestion for deleting **all** versions in the immediate context of deleting archived versions, I assumed it would remove **all** archived versions and keep the live one intact.

While I definitely misunderstood, I do think it's an easy mental jump to make, given the context that it's suggested within. I'd still like to recommend an update to the message, so that it explicitly spells out what that option *will* and *will not* do, given the information that immediately precedes it.

https://cloud.google.com/storage/docs/using-object-versioning#delete

**Comment by houglum** [comment]
Sure, couldn't hurt.  I'll send a change in wording over to the docs team for review :)
