### ISSUE TITLE
Use `gsutil acl ch -d user@example.com` remove a user has no real effect.

### ISSUE THREAD

**Issue by go101** [GoogleCloudPlatform/gsutil#477]
I tried to remove a user from the acl of objects.
The command responses `Updated ACL on gs://...`.
But the user is still listed in the acl list from the gcs web console.

**Comment by go101** [comment]
BTW, I just tried to delete the user from the web console.
The web console also responses the deletion succeeded.
But when I refresh the page and check the acl list again, the user expected to be removed is still listed there.
So I think this may be an issue in the code lib the gsutil tool and the web console both depend on.

**Comment by go101** [comment]
BTW2, in the process of using `gutil rsync`, I encountered a weird thing.
After the first time I run  `gsutil -m rsync -r   gs://my-bucket-1 gs://my-bucket-2`,
I run again immediately, it returns 
```
WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".

Building synchronization state...
Starting synchronization
```

Nothing else is returned, so it looks all files are synced.

But after one hour, I run the command again, it is strange that one more file is synced.
The file is finally confirmed as a very very old file saved years ago.
And it is expected to be deleted already a long time ago.

The issue is hard to reproduce. Just for your information.

**Comment by houglum** [comment]
The user you're trying to remove is probably the owner (original creator) of the object.  GCS doesn't let you delete the original owner from the ACL list -- we want to avoid the scenario where **nobody** has any permission on the object (e.g. if you deleted every ACL entry), effectively orphaning it.

**Comment by go101** [comment]
Yes, the user I want to delete from ACL is the creator.
Thanks for your reply.
