### ISSUE TITLE
 TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by rnunziata** [GoogleCloudPlatform/gsutil#478]
I thought this was fixed and merged?

installed and updated via pip 

sudo pip install -U gsutil

--------------------------------

still getting error

 TypeError: Error when calling the metaclass bases

I thought this was fixed and merged?

**Comment by houglum** [comment]
I'm *assuming* you're referring to #470 ? If so, the fix for that was to pin to an old version of `six` -- gsutil didn't release any new versions until today.  That being said, v4.28 includes an updated version of `apitools` (v0.5.16) that works with v1.11.0 of `six`.

**Comment by rnunziata** [comment]
thanks
