### ISSUE TITLE
Parallel operations for copying objects in python API

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/gsutil#492]
It would be great if there were a way to do the equivalent of the following command from the python API:

`gsutil -m cp -r myfolder gs://mybucket/`

You can currently upload each file individually, but this is slow for folders with many files.

I've also submitted a bug to google-cloud-python: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4684

**Comment by houglum** [comment]
I propose we close this issue, as you've already filed the bug against google-cloud-python and there's not much to be done from gsutil's perspective :)
