### ISSUE TITLE
gsutil cp problems after update

### ISSUE THREAD

**Issue by 1tron1** [GoogleCloudPlatform/gsutil#501]
I had gsutil working then I ran components updates and it all went downhill from there:

I have gsutil installed on two separate systems and I made two identical test folders, and both systems have full permissions to the bucket and I get this issue:

```sh

gsutil cp -r empty_folder gs://test-bucket

returns: CommandException: no URLs matched
```

and yet on another installation both with 4.28, it works.

Any ideas?

Full reinstall ineffective at fixing the problem on the affected computer.

I deleted every trace of google-cloud-sdk and the ~./config directory and still am getting this error after a seemingly clean install.

Normally I would put a clean virt system in place but I cannot do that because the SDK that is the problem is on a box that has licensed enterprise software, so wiping the system would be a pain. As this is part of a hybrid app, this unit is now essentially bricked, which is unfortunate and expensive.

**Comment by houglum** [comment]
When you say "it works" on another installation, do you mean that it returns 0 as its exit code and emits no error message?  Or something different (if so, please explain and note any differences between the two setups)?  The _expected_ behavior would be having an exit status of 1 and emitting the "no URLs matched" error message... as to whether or not this is the _correct_ behavior, that's up for debate (and tracked separately in #417)

**Comment by 1tron1** [comment]
Yes I mean that on the "working" system (System A) the software has exit code 0 emits no error message and successfully uploads the files. On System B, on which it does not "work", exit status is non-zero and files fail to upload. So as far as failure modes, the behavior is correct, a Failure results in failed message and a non-zero exit code, and successful command is silent and 0 exit.

My problem is with why these two systems behave differently, fail versus not fail. I know this will be a bit difficult to debug, so I appreciate your patience.

On System A (Working) and System B, I went about the install in the same way using the bash script on the installation instruction page.

I had system A and B working for some time but then I updated gsutils and the system broke (B). I do not have access to it (B) at the moment, I glanced through the gsutil source and will look in more detail as it seems like something is being left behind after install, I understand that Python packages are but this seems strange to be a source of the error.

Essentially after B broke down I removed the google-cloud-sdk folder, and the config folder and did a fresh install on System B but to no avail. On Tuesday I'll be back with the system and be able to check on the Python libraries, but still that seems a bit far fetched to me.

**Comment by 1tron1** [comment]
@houglum  OS update fixed the issue, still not sure of the cause but I am going to close the issue.

**Comment by yaseenkhanmohmand** [comment]
I have the same issue

**Comment by 1tron1** [comment]
@yaseenkhaor mnmohmand , the only thing that fixed it for me at the time was doing a full system update and upgrade, including gsutil.
