### ISSUE TITLE
gsutil notification create throws NotfoundException

### ISSUE THREAD

**Issue by samhalpa** [GoogleCloudPlatform/gsutil#520]
gcloud version:

> Google Cloud SDK 198.0.0
> alpha 2017.09.15
> beta 2017.09.15
> bq 2.0.32
> core 2018.04.13
> docker-credential-gcr 
> gcloud 
> gsutil 4.30

Try to create notification for storage bucket:
`gsutil notification create -t something -f json gs://<bucket-name>`

Expected behaviour: A notification (topic) to be created
Actual behavior: 

> NotFoundException: 404 

However, i can list and/or delete existing notifications.

**Comment by houglum** [comment]
If you're not even getting the "Created Pub/Sub topic" output message, it's likely this is coming from the CreateTopic() call.  The only way I can get a 404 NotFoundException from CreateTopic() is if the default project ID you have specified in your boto file is invalid (misspelled or doesn't exist).

To confirm this, you can run with the top-level -D option, e.g. `gsutil -D notification <...>`, to see which request is getting the 404 response.

**Comment by samhalpa** [comment]
@houglum Thanks, It was my fault, my project id was wrong. But i wonder how it allowed me to delete an existing topic. Anyway Thanks.

**Comment by houglum** [comment]
`gsutil notification delete` doesn't delete Pub/Sub topics; it deletes notification configs that have been set on the specified bucket.
