### ISSUE TITLE
"[Errno 2] No such file or directory" running gsutil

### ISSUE THREAD

**Issue by DanTup** [GoogleCloudPlatform/gsutil#522]
I'm trying to get the dart-sdk checked out and working on my MacBook, but when I run `gclient sync` I'm greeted with the error:

> [Errno 2] No such file or directory

Full details are [here](https://github.com/dart-lang/sdk/issues/32702) but I've managed to get as far as discovering that even `gsutil.py version -l` from inside the `depot_tools` folder doesn't work:

```text
dantup-macbookpro:depot_tools dantup$ gsutil.py version -l
Traceback (most recent call last):
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 183, in <module>
    sys.exit(main())
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 180, in main
    clean=args.clean)
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 152, in run_gsutil
    return subprocess.call(cmd, shell=IS_WINDOWS)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

If I open up line 152 of `gsutil.py` and add `print cmd` just before it tries to run the command, I get this output:

> ['vpython', '-vpython-spec', '/Users/dantup/Dev/Google/depot_tools/gsutil.vpython', '--', '/Users/dantup/Dev/Google/depot_tools/external_bin/gsutil/gsutil_4.30/gsutil/gsutil', '-o', 'GSUtil:software_update_check_period=0', 'version', '-l']

If I try to run that command manually from the terminal, it works fine:

```text
dantup-macbookpro:depot_tools dantup$ vpython -vpython-spec /Users/dantup/Dev/Google/depot_tools/gsutil.vpython -- /Users/dantup/Dev/Google/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/gsutil -o GSUtil:software_update_check_period=0 version
gsutil version: 4.28
```

I've hit this on three machines - previously on my Windows PC and my personal MacBook - I kinda gave up since the checkout had worked well enough for what I needed, but now I'm hitting the same issue on my Google corp MacBook and I'm really hoping to fix it this time!

Any ideas on how to troubleshoot further?

**Comment by houglum** [comment]
Maybe the environment from which you're running the command isn't able to run vpython -- try editing cmd to use the full path to vpython, maybe?  Regardless, this isn't related to gsutil itself; it's a problem with the tool that attempts to bundle and run it.  I'd recommend continuing investigation on the other issue you linked.

**Comment by DanTup** [comment]
@houglum The environment is coming from gsutil. I can repro this from the command line without any of the Dart stuff:

```
dantup-macbookpro:dart-sdk dantup$ vpython /Users/dantup/Dev/Google/depot_tools/gsutil.py --force-version 4.28 version
Traceback (most recent call last):
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 182, in <module>
    sys.exit(main())
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 179, in main
    clean=args.clean)
  File "/Users/dantup/Dev/Google/depot_tools/gsutil.py", line 152, in run_gsutil
    return subprocess.call(cmd, shell=IS_WINDOWS)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The command `vpython /Users/dantup/Dev/Google/depot_tools/gsutil.py --force-version 4.28 version` is internally calling `vpython -vpython-spec /Users/dantup/Dev/Google/depot_tools/gsutil.vpython -- /Users/dantup/Dev/Google/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/gsutil -o GSUtil:software_update_check_period=0 version` which is failing. Both of these parts are in gsutil, so I don't know where else I can get help.

**Comment by houglum** [comment]
The `depot_tools/gsutil.py` script you're running is the sdk's wrapper script that launches the __real__ gsutil.  Gsutil doesn't have a `--force-version` flag, which is what clued me in initially :)

Look at the third item in your stack trace -- it calls `run_gsutil()`, which is supposed to launch the __real__ gsutil start script at `[...]/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/gsutil`.  However, it never actually invokes the real gsutil (which, from the look of it, is because it can't find vpython).

**Comment by DanTup** [comment]
Aha, I see now. I thought that `gsutil.py` script was from this repo, but I guess not. I'll do some more digging in there and see if I can figure out what's going on. Seems weird that some invocations of `vypthon` in the scripts are working but others are not. I guess the "broken" script is owned by `depot_tools` so I'll see if I can get help there once I've dig further (I don't think it's a Dart SDK issue).

Thanks for the info!

**Comment by DanTup** [comment]
In case anyone else finds this post with a similar issue, it turned out to be fairly simple - I'd used tildes `~` in my PATH, and they resolved fine in the terminal but not inside Python, which is why it culdn't find `vpython`. Doh.
