### ISSUE TITLE
gsutil-related messages in `gcloud init` output should be more specific

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/gsutil#525]
I'm not sure if this is the right place for the issue, but the search for "gcloud" in the repositories list didn't match easily, so here it goes.

When I run `gcloud init`, a passage in the output says,

> Created a default .boto configuration file at [/Users/peacefullybound/.boto]. See this file and
> [https://cloud.google.com/storage/docs/gsutil/commands/config] for more
> information about configuring Google Cloud Storage.

I think this message should be more clear about when such an action is necessary.

At first, I thought, "Oh, I should check this out.", however, that was a beginning of a long-time journey without achievement. Since the default boto file is nothing but a commented documentation and the link is literally a command reference, there was none saying "You don't have to do anything." Thank god I came across [this comment](https://github.com/GoogleCloudPlatform/gsutil/issues/386#issuecomment-250538149), saying,

> The original message is working as intended; gcloud based installs configure credentials via gcloud auth login and you should only run gsutil config if you want to configure HMAC credentials (-a flag) or generate a generic .boto configuration file (-n flag).

I think the *you should only run if* part should be more explicitly expressed at the first place. I don't think careful reading of such an output is something to blame.

My versions.

- Google Cloud SDK 200.0.0
- core 2018.04.30
- gsutil 4.31

BTW, the overall experience of getting started GCP is quite impressive. I couldn't help raising this issue :)

**Comment by houglum** [comment]
Commit 131e371 added some clarification around `gcloud auth <foo>` vs `gsutil config` to the docs at https://cloud.google.com/storage/docs/gsutil/commands/config.  If the Cloud SDK docs are still not clear, feel free to file a bug against their component in our public issue tracker:

https://issuetracker.google.com/issues/new?component=187143&template=800102
