### ISSUE TITLE
google computer engine: lost exported env after closing ssh

### ISSUE THREAD

**Issue by astrung** [GoogleCloudPlatform/gsutil#528]
I have an instance on Google computer engine, and i have exported environment variable by this command : `export my_token=my_token`. Everything is fine, it prints `my_token` when i echo it : `echo $my_token`. 

But after closing ssh connection and reconnect to my instance, by `echo $my_token`, it prints nothing , so i lost exported environment variable after closing ssh. How can i keep my environment variable even after closing ssh ?

**Comment by houglum** [comment]
As your question is unrelated to gsutil, I'll go ahead and mark this as closed. A more appropriate place for your question would be StackOverflow.
