### ISSUE TITLE
Documentation - confusing return status on error with parallel option

### ISSUE THREAD

**Issue by glefait** [GoogleCloudPlatform/gsutil#538]
I was dealing with potential errors on a parallel rsync and was not being sure of what is really happening when errors occur. 
https://github.com/GoogleCloudPlatform/gsutil/blob/e8154bab37ad896b1e1ab01f452ac3284c7051d4/gslib/addlhelp/command_opts.py#L106-L110

I wanted to be sure that the exception will be propagated, captured and a code different of 0 will be returned, but I found the documentation confusing.

> although most commands will normally fail when the -m flag is disabled, [...] when -m is enabled [...]  the number of failed operations (if any) will be reported at the end of the command's execution.

Because `reported` can be understood as just "displaying", I would like to rephrase that sentence to: 
> the failed operations (if any) will be reported as an exception at the end of the command's execution.

**Comment by houglum** [comment]
Thanks for the PR.  Marking this as closed since it's been merged.
