### ISSUE TITLE
'gsutil cp' requires storage.objects.list permission

### ISSUE THREAD

**Issue by rhashimoto** [GoogleCloudPlatform/gsutil#546]
When I use gsutil cp (version 4.33) with an IAM account that does not have `storage.objects.list`, I get this:
```
$ gsutil cp foo gs://my-bucket-name/foo
AccessDeniedException: 403 my-service-account@my-project.iam.gserviceaccount.com does not have storage.objects.list access to my-bucket-name.
```
The [gsutil documentation for IAM permissions](https://cloud.google.com/storage/docs/access-control/iam-gsutil) does not list `storage.objects.list` as required, so either the code or the documentation appears to be wrong.

**Comment by houglum** [comment]
Ah, this may have slipped through the permissions testing when writing that docs page -- I imagine we only tested with something like `gsutil cp file gs://bucket`, rather than `gsutil cp file gs://bucket/prefix/path/component`, which first checks to see if `prefix/path/component` is a prefix of any other object names in the bucket to avoid a situation where you have objects named like:

    gs://bucket/foo
    gs://bucket/foo/bar

(which could cause confusion around semantics of running something like `gsutil ls gs://bucket/foo`)

We should indeed add "storage.objects.list" to the permissions list for `cp` at https://cloud.google.com/storage/docs/access-control/iam-gsutil.  Thanks for the report!

**Comment by starsandskies** [comment]
Documentation has been updated. I believe this can be closed now.

**Comment by careylamothe** [comment]
I was able to access by reports from the Google Play Console by gsutil until I created a service account.  Now  I get ```iam.gserviceaccount.com does not have storage.objects.list access to pubsite_prod_rev``` Permissions management isn't available in the console for these buckets. 
I enabled this specific permission on the service account and project, but I get the same error when requesting a download by HTTP and also by the Google Client Library. Please help.

**Comment by pbaqui** [comment]
The issue persists. `iam.gserviceaccount.com does not have storage.objects.list access to xx.`. I am storage object admin.

**Comment by 6peterlu** [comment]
I'm getting the same issue as @pbaqui, has anyone found a workaround for that?

**Comment by ShantzPantz** [comment]
> I was able to access by reports from the Google Play Console by gsutil until I created a service account. Now I get `iam.gserviceaccount.com does not have storage.objects.list access to pubsite_prod_rev` Permissions management isn't available in the console for these buckets.
> I enabled this specific permission on the service account and project, but I get the same error when requesting a download by HTTP and also by the Google Client Library. Please help.

I am running into the same issue trying to pull data with gsutil using a service account. I can download them fine using my Google credentials. 

@careylamothe Did you find a way to make this work?

**Comment by quai20** [comment]
@ShantzPantz Same here, I'm interested if you found a way to make it work.

**Comment by ckchow** [comment]
I think either the documentation went out of date again or there was a regression in gsutil. this command
```
gsutil cp gs://hadoop-lib/bigquery/bigquery-connector-hadoop3-0.19.1.jar .
```
fails with
```
AccessDeniedException: 403 <me>@<company>.com does not have storage.objects.list access to the Google Cloud Storage bucket.
```

I think only google employees should have ls permissions on `gs://hadoop-lib`. the documentation says that `storage.objects.list` is only required on the destination bucket, and that does not appear to be the case - anymore, at least.
