### ISSUE TITLE
gsutil does not allow for custom roles to be added to bucket permissions

### ISSUE THREAD

**Issue by jmeekins** [GoogleCloudPlatform/gsutil#550]
<h2>When trying to add custom role to bucket permissions you get errors. </h2>

<h3>What i am doing:</h3>

gsustil iam ch group:group_name:projects/test/roles/custom gs://my_bucket

<h3>The error:</h3>

BadRequestException: BadRequestException: 400 Invalid argument
BadRequestException: 400 Invalid argument

What I am seeing happening is the role is being prepended with roles/storage. So in this case it would try to add the role "roles/storage.projects/test/roles/custom" obviously this roles does not exist. What I have found is that line 228 in iam_helper.py is prepending to every role specified. Is there a way we can add support for custom roles?

<h4>line 228</h4>
roles = ['roles/storage.%s' % r if r else DROP_ALL for r in roles.split(',')]

**Comment by jduplessis** [comment]
@jmeekins it seems this was fixed? At the end of last year, when trying to assign custom roles, I got the same error message you described. This morning I uncommented that part of my script and... it does what it's supposed to with no error.

**Comment by houglum** [comment]
Yep, fixed in https://github.com/GoogleCloudPlatform/gsutil/commit/b87bc159f6b057baab4b595ace868dd8b32cbd60.  Marking this as closed.
