### ISSUE TITLE
`gsutil rm -r gs://bucket/` should NOT remove the bucket

### ISSUE THREAD

**Issue by dmsolow** [GoogleCloudPlatform/gsutil#567]
It should remove every item in the bucket and halt, leaving an empty bucket. The short doc string for `rm` says "Remove objects" and there's a separate command (`rb`) for removing buckets. This is a bad design choice that's going to screw people over.

**Comment by houglum** [comment]
I agree that it's probably worth calling out in the short doc string for `rm`.  Looking over the rest of the documentation, it does call out that doing this will remove the bucket as well, and provides a workaround:

> Running gsutil rm -r on a bucket will delete all versions of all objects in
>   the bucket, and then delete the bucket:
> 
>     gsutil rm -r gs://bucket
> 
>   If you want to delete all objects in the bucket, but not the bucket itself,
>   this command will work:
> 
>     gsutil rm gs://bucket/**
> 

but it's thrown in the middle of the other examples, so I can see it being easy to miss if you're just skimming over it.  We could probably add a more noticeable warning around that section in addition to supplementing the short doc string's wording.
