### ISSUE TITLE
`gsutil cp myFile gs:/myBucket` [sic]

### ISSUE THREAD

**Issue by leehart** [GoogleCloudPlatform/gsutil#572]
Notice the missing slash:
```
gsutil cp myFile gs:/myBucket
```

That gives the seemingly successful progress report:
```
Copying file:///home/foo/myFile...
- [1 files][ 20.1 MiB/ 20.1 MiB]                                                
Operation completed over 1 objects/20.1 MiB.
```
Where did `myFile` go?!
The file does not show up in `myBucket`, presumably because of the typo.

Compare with this operation, which results in `myFile` showing up in `myBucket`, as expected.
```
gsutil cp myFile gs://myBucket
```

That gives an identical progress report, but with a successful outcome:
```
Copying file:///home/foobar/myFile...
- [1 files][ 20.1 MiB/ 20.1 MiB]                                                
Operation completed over 1 objects/20.1 MiB.
```

**Comment by houglum** [comment]
On Linux, the `:` character is a valid for use in a filename.  Given this, gsutil determines that because the destination arg doesn't start with the pattern `<provider>://`, that `gs:/abc` must be referring to the file `abc` under the directory `gs:` (in the current working directory).  We can confirm this via these commands:

```
$ mkdir /tmp/gs-repro && cd /tmp/gs-repro

$ echo "a" > a.txt

$ gsutil cp a.txt gs:/notactuallyabucket
[...output...]

$ ls -l
total 8
-rw-r--r-- 1 username usergroup    2 Oct 12 14:50 a.txt
drwxr-xr-x 2 username usergroup 4096 Oct 12 14:50 gs:

$ ls -l 'gs:/'
total 4
-rw-r--r-- 1 username usergroup 2 Oct 12 14:50 notactuallyabucket
```

**Comment by leehart** [comment]
Documented feature https://cloud.google.com/storage/docs/gsutil/commands/cp
