### ISSUE TITLE
rsync: support --ignore-existing

### ISSUE THREAD

**Issue by hundeboll** [GoogleCloudPlatform/gsutil#573]
Image the the following workflow:

- A cloudbuild step downloads a bunch of (but not all) files from a public bucket using HTTP
- The same step creates som additional files and places them among the downloaded files
- The next cloudbuild step runs `gsutil rsync -r -d ./download-dir gs://bucket-name`

Since the files are downloaded using HTTP, the mtime doen't match, and so all files are re-uploaded to the bucket.

I know I could force checksum matching, but since the files have checksum digests included in their filenames, it would be enough to simply ignore existing files.

I have also seen suggestions to use `rsync cp` to avoid replacing existing files, but that doesn't support deleting destination files not present in the source tree.

The non-gsutil version of rsync has --ignore-existing option to support my request. Would it be possible to implement the same in `gsutil` ?

**Comment by zardoz-bzar** [comment]
workaround for a single directory

I pulled my bucket, then touched a file called foo.

eval BUCKET="bzar-inf-1" grep -vf <( gsutil ls gs://$BUCKET/ | sed -e s,gs://$BUCKET/,,  ) <( ls -1 ) | xargs -l -i{} gsutil cp {} gs://$BUCKET/

Copying file://foo [Content-Type=application/octet-stream]...
/ [1 files][    0.0 B/    0.0 B]
Operation completed over 1 objects.

Just replace the bucket value, subdirectories? just a more fun problem to solve

**Comment by catleeball** [comment]
Note to internal folks, I mirrored this FR to b/135626681

**Comment by sergeylanzman** [comment]
added support https://github.com/GoogleCloudPlatform/gsutil/pull/1183

**Comment by dilipped** [comment]
Thanks for the PR. Resolving this.
