### ISSUE TITLE
gsutil requires a real linux user

### ISSUE THREAD

**Issue by gracenoah** [GoogleCloudPlatform/gsutil#575]
Related to https://github.com/GoogleCloudPlatform/gsutil/issues/422

This issue doesn't seem to have been fixed permanently. Until version 216.0.0 of google cloud sdk I was actually able to use gsutil in a docker container where the user didn't exist, but since then, I haven't been able to upgrade gsutil because it started failing when the user doesn't exist.

The issue is that we run gsutil in a docker container with `-u` that changes the uid to the host user. This user has no /etc/passwd entry inside the container. This user only has a uid/gid that matches the host.

The failing command for us is cp. stat seems to work correctly without a real user.

```
$ export GOOGLE_APPLICATION_CREDENTIALS=<path to json>
$ gsutil -m cp -r "gs://<bucket name>/<path>/." "<local path>"
'getpwuid(): uid not found: 500'
...
'getpwuid(): uid not found: 500'
CommandException: 103 files/objects could not be transferred.
```

I don't think this failure is due to any kind of fundamental need for the user to exist and be a full user because it was working just fine before. By the way, we set the environment variable `$USER` and we set `$HOME` so if a username or home directory is needed, that would be a good fallback mechanism to determine what to use. Ideally, it would be good if gsutil doesn't require a user to work.

**Comment by houglum** [comment]
Thanks for filing an issue!  Could you run this with `-Dm` as the top-level options?  That should spit out a stack trace and tell us exactly what we're doing to call getpwuid().

Off the top of my head, I suspect that if we're not trying to preserve posix attributes, we should be able to avoid actually making this call (probably by wrapping it in a `LazyWrapper` lambda and invoking it when we need it).

**Comment by gracenoah** [comment]
I didn't know about this debug flag. This is great. You can see exactly where the error is coming from:
```
Encountered exception while copying:
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2122, in PerformTask
    results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 788, in _CopyFuncWrapper
    preserve_posix=cls.preserve_posix_attrs)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 968, in CopyFunc
    mode=mode)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/utils/posix_util.py", line 306, in ValidateFilePermissionAccess
    if getpass.getuser() == 'root':
  File "/usr/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 393928913'
```

**Comment by houglum** [comment]
Apparently, the `if getpass.getuser() == 'root':` line [isn't guaranteed to always do what we want](https://superuser.com/questions/626843/does-the-root-account-always-have-uid-gid-0).  TIL.

Before I change the code, is there any way you can change that line (in the copy of gsutil running in your container) to:

`if os.geteuid() == 0:`

and verify that it works?  Since you're not attempting to preserve Posix attributes in your command options, this should just return `True` at the next check anyway, but I'd like verification that it works before pushing the change :)

**Comment by gracenoah** [comment]
I tested replacing `if getpass.getuser() == 'root':` with `if os.geteuid() == 0:` in my container and it does fix the issue.

**Comment by nyurik** [comment]
@houglum thanks for fixing it, but the `google/cloud-sdk:slim` docker image doesn't appear to have it yet...  Do you know when it will get updated?

**Comment by houglum** [comment]
I'd imagine a release will go out either this week or next. Most teams didn't do releases over the holiday break, for sanity reasons :)
