### ISSUE TITLE
rsync should support -z and -Z

### ISSUE THREAD

**Issue by greggdonovan** [GoogleCloudPlatform/gsutil#579]
We would like to use gzip Content-Encoding for all files that are uploaded via `gsutil rsync`, as we do with `gsutil cp`.

**Comment by FlorianBurgevin** [comment]
+1

**Comment by thiagopnts** [comment]
+1

**Comment by thobrla** [comment]
Does -J help for your use case?  I think the main reason -z/-Z are not supported is that they are asymmetric, which causes challenges in reasoning for all future executions of rsync.

**Comment by stanhu** [comment]
I looked into doing this. It seems the `cp` command sets the `gzip_local` flag: https://github.com/GoogleCloudPlatform/gsutil/blob/d53d1fc5c27da067c22e1dc61a27491b56e232ce/gslib/commands/cp.py#L1184

However, I can't see where this is actually used.

**Comment by kosich** [comment]
@stanhu , afau, `gzip_local` flag is there only to understand if both it and `gzip_encoded` have been set to true to raise an error:

https://github.com/GoogleCloudPlatform/gsutil/blob/d53d1fc5c27da067c22e1dc61a27491b56e232ce/gslib/commands/cp.py#L1262-L1264

When using actual copying helper, both `cp` and `rsync` use only `gzip_encoded` flag and one of the `gzip_arg_exts`|`gzip_arg_all` params:

- setting gzip options in `cp` https://github.com/GoogleCloudPlatform/gsutil/blob/d53d1fc5c27da067c22e1dc61a27491b56e232ce/gslib/commands/cp.py#L1272-L1273
- setting gzip options in `rsync` 
https://github.com/GoogleCloudPlatform/gsutil/blob/d53d1fc5c27da067c22e1dc61a27491b56e232ce/gslib/commands/rsync.py#L1789-L1790

So, we could copy this behaviour in `rsync` and only set the `gzip_arg_exts` or `gzip_arg_all`  params, while keeping the `gzip_encoded` falsy:

https://github.com/GoogleCloudPlatform/gsutil/blob/d53d1fc5c27da067c22e1dc61a27491b56e232ce/gslib/commands/cp.py#L1244-L1249

——

NOTE: I'm guessing here, haven't debugged the code.

**Comment by stanhu** [comment]
We might want to close this issue because of https://github.com/GoogleCloudPlatform/gsutil/pull/1430#issuecomment-1010234090.

**Comment by dilipped** [comment]
As mentioned in the comment pointed out by @stanhu, the -z behavior for rsync will mess up with the diff as the destination file will be compressed and the size and hash will not match. I would recommend using `gsutil cp` for this behavior.
