### ISSUE TITLE
gsutil cp -n clobbers local files with differing size

### ISSUE THREAD

**Issue by kevinoid** [GoogleCloudPlatform/gsutil#591]
I expected `gsutil cp -n` not to overwrite existing files when copying from the cloud to the local machine.  That expectation is based on the `--help` output, which describes `-n` as "No-clobber. When specified, existing files or objects at the destination will not be overwritten. [...]"  In practice, if the existing local file does not have the same size as the file in the cloud it will be overwritten.  For example:

```sh
echo 'Original content.' > test.txt
gsutil cp test.txt "gs://$BUCKET_NAME"
echo 'Modified content with differing size.' >| test.txt
gsutil cp -n "gs://$BUCKET_NAME/test.txt" test.txt
cat test.txt
```

Which prints `Original content.` instead of `Modified content with differing size.`, demonstrating that the file has been overwritten by `gsutil cp -n`.

The code responsible is at [copy_helper.py:3438](https://github.com/GoogleCloudPlatform/gsutil/blob/v4.35/gslib/utils/copy_helper.py#L3438) which was first introduced in a768a58 to support resuming partial downloads.  However, I don't think that has worked since 3e3d6dc, which started using temporary files (named with `_.gstmp`) for all downloads.

Would it be possible to either make `gsutil cp -n` behave as documented (my preference) or update the documentation to match the behavior?

Thanks,
Kevin

**Comment by houglum** [comment]
Thanks for the report!  Yeah, that doesn't seem right at all.  This should behave the same regardless of whether you're copying to a cloud object or a local file, and should have behavior analogous to the *nix `cp`.

**Comment by kevinoid** [comment]
@houglum I totally agree.  Should I submit a PR to remove `if src_obj_size == os.path.getsize(dst_url.object_name):` at [copy_helper.py:3438](https://github.com/GoogleCloudPlatform/gsutil/blob/v4.35/gslib/utils/copy_helper.py#L3438), or is that unnecessary/counter-productive?

**Comment by houglum** [comment]
That sounds reasonable to me, since all downloads write to a temporary file -- the comment there mentions that this is only in place in case the file was partially copied from before.

+ @thobrla who originally wrote the comment, AFAICT after tracing back in commit history a bit.  Any other reason this check is there, or is it fine to remove this now?

**Comment by thobrla** [comment]
I'm fairly certain when this code was written that we did not write to a temporary file (except in the gzip case), so I agree it should be safe to remove.
