### ISSUE TITLE
FR: flag for last file stored

### ISSUE THREAD

**Issue by Dannyzen** [GoogleCloudPlatform/gsutil#593]
We often have the need to identify the last file stored, this request is for a flag that would return results for `ls` sorted by stored `dt` descending.

**Comment by houglum** [comment]
We generally don't support client-side filtering or ordering for object listings.  This leads to pretty crazy scope creep, and becomes quite difficult when you consider how listing works under the hood (paginated results in batches of 1000) and how sorting would be painful to implement when the collection doesn't fit in memory, e.g. for buckets with 1B+ objects.

That being said, the proper solution here is to write a quick script to do this that uses one of our GCS client libraries; list all the objects, keeping track of the newest one as you iterate over them, and then print out the newest one at the end.

If you're fine with a more fragile, quick-and-dirty solution, you can probably make use of `gsutil -l`, which prints output in this format.

```shell
$ gsutil ls -l gs://BUCKET/**
         6  2019-01-12T00:35:30Z  gs://BUCKET/anobject
         4  2019-01-12T00:00:58Z  gs://BUCKET/obj1
         6  2019-01-12T00:36:23Z  gs://BUCKET/obj11
         4  2019-01-12T00:01:01Z  gs://BUCKET/obj2
TOTAL: 4 objects, 20 bytes (20 B)
```

...using some Bash-foo as written below:

```shell
latest=""; gsutil ls -l gs://BUCKET/** | while read line; do
  # Match only the lines that look like "4  2019-01-12T00:01:01Z  gs://blah/blah",
  # and chop off everything before the date string.
  date_and_obj="$(echo $line | sed -En 's/\s*[^[:space:]]+\s+([0-9][0-9][0-9][0-9]-.*)/\1/p')" 
  if [[ "$date_and_obj" > "${latest:-}" ]]; then
  	latest="$date_and_obj"
        # Every time we discover a newer object, save and print that line.
  	echo $latest
  fi
done | tail -n 1  # We only care about the last printed (newest) object.
```

This works if your object names don't have any characters in them that translate in linebreaks when printed to your terminal (nudge: you should really use a client library instead).  For the objects listed above, the output would be:

```
2019-01-12T00:36:23Z gs://BUCKET/obj11
```
