### ISSUE TITLE
How to update gsutil latest version

### ISSUE THREAD

**Issue by dungna** [GoogleCloudPlatform/gsutil#595]
Hello.
At the moment, I am using gsutil version 4.34 (installed via Google SDK). Now I want upgrade gsutil to latest version (4.35). How do I?
Thanks.

**Comment by houglum** [comment]
The Cloud SDK release of gsutil always lags behind the standalone release by a week or two -- we do the standalone release, then package the new version up for the Cloud SDK to include in their next (weekly) release.

That being said, there were no Cloud SDK releases during the holiday break.  Their weekly releases should have resumed this week, so 4.35 should be out in gcloud now.
