### ISSUE TITLE
On Python installs built against OpenSSL 1.1.1, Boto fails with SNI errors

### ISSUE THREAD

**Issue by houglum** [GoogleCloudPlatform/gsutil#606]
As mentioned in #605 and https://github.com/boto/boto/pull/3843, Boto will fail to connect to Google servers if the version of OpenSSL that Python is compiled against is 1.1.1:

```
Traceback (most recent call last):
  File "./gsbototest.py", line 6, in <module>
    boto.storage_uri('bucket-name', 'gs').create_bucket()
  File "/tmp/boto/boto/storage_uri.py", line 574, in create_bucket
    storage_class)
  File "/tmp/boto/boto/gs/connection.py", line 95, in create_bucket
    data=get_utf8_value(data))
  File "/tmp/boto/boto/s3/connection.py", line 682, in make_request
    retry_handler=retry_handler
  File "/tmp/boto/boto/connection.py", line 1074, in make_request
    retry_handler=retry_handler)
  File "/tmp/boto/boto/connection.py", line 1033, in _mexe
    raise ex
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

Until that Boto pull request gets merge, a new version gets released (this is the part we don't have control over :( ), and we can start pinning to the new version of Boto in our setup.py code, we should probably add this patch to the Boto monkeypatches we run at startup.

Thanks again to @kevinoid for pointing this out.

**Comment by xnox** [comment]
Available PRs:

https://github.com/boto/boto/pull/3843

https://github.com/boto/boto/pull/3836

Also this will kind of become critical as Ubuntu 18.04 is about to receive OpenSSL 1.1.1 as an update.
python-boto in the archive will be fixed for this, but manually installed things from pip will not.

**Comment by houglum** [comment]
Verified that lack of SNI is also causing intermittent failures on SSL 1.1.0.<X>.  gsutil appears to hang, but when running with `gsutil -D ...`, I see this error text multiple times:

```
DEBUG 0225 16:33:33.703160 connection.py] encountered SSLError exception, reconnecting
DEBUG 0225 16:33:33.703591 connection.py] establishing HTTPS connection: host=storage.googleapis.com, kwargs={'port': 443, 'timeout': 70}
```

Will patch in https://github.com/boto/boto/pull/3843 into gsutil shortly.
