### ISSUE TITLE
du summary is badly formatted on sizes with 6 digits

### ISSUE THREAD

**Issue by bfontaine** [GoogleCloudPlatform/gsutil#613]
Minor issue, but when you have a path prefix that weight between 1000 and 1023.99 {…,G,k}iB, it uses all the available space _plus one character_:

```
872.78 KiB  gs://my-bucket/dir1
41.06 GiB   gs://my-bucket/dir2
1011.74 GiB  gs://my-bucket/dir3  # <-- here
203.22 MiB  gs://my-bucket/dir4
3.26 GiB    gs://my-bucket/dir5
```

It should probably use 11 chars rather than 10 for the size. I can make a PR ([following the guide](https://cloud.google.com/storage/docs/gsutil/addlhelp/ContributingCodetogsutil)) if you want.

**Comment by houglum** [comment]
Thanks for filing an issue!

We've been discussing the contribution guide recently, and we will probably change this in the near future to suggest using GitHub PRs instead.  That being said, please feel free to just submit a PR instead :)
