### ISSUE TITLE
Consider forking/vendoring Boto code

### ISSUE THREAD

**Issue by houglum** [GoogleCloudPlatform/gsutil#622]
With boto3 ([boto/boto3](https://github.com/boto/boto3)) being preferred over boto ([boto/boto](https://github.com/boto/boto)), the release cadence for boto is becoming less frequent, and more functionality is being added to boto3 instead of boto.  In addition to this, boto3 does not support GCS in its defined services, so we cannot use it as-is (if my understanding of the boto3 code base is correct, anyway).  This means that any changes we propagate to boto may not be available in a newly-released version for quite some time, causing a lot of toil by needing to create runtime monkeypatches for the time being (e.g. we may need to perform a gsutil release in order to launch a new GCS feature, in which case we can't sit around and wait for someone from the boto maintainers list to release a new version whenever it's convenient, so we often [add monkeypatches - see this permalink](https://github.com/GoogleCloudPlatform/gsutil/blob/8dad3077d5d34a2aa2921a0f6a5919292ba9fdea/gslib/utils/boto_util.py#L348)).  To avoid this, I'd propose the following:

- We include a local copy/fork of the boto code in gsutil. As we need to add functionality to the XML API, we add the necessary changes in this fork.
- In the spirit of open source, we also propagate changes to the upstream boto/boto library, so non-gsutil users can also use the new functionality via boto.

<hr>

I'd also considered a different approach, which would take substantially more work: 

Today, we use the `boto_translation.py` module to handle all XML requests, which end up being handled by the boto library.  If we wanted to get all the up-to-date functionality for operating on S3 resources, we could create a new API client module, e.g. `s3_xml_api` or `boto3_translation`, that would use boto3 under the hood to send requests to S3.  Concerning cons, this has several, including managing potential differences in configuration (e.g. maybe boto3 supports some boto config sections/keys that boto does not, maybe some existing configurations behave differently in boto3 than in boto, etc.), along with additional maintenance complexity (needing to write and maintain *another* set of code paths, for the new API client).  That being said, I actually think this is the most future-proof solution, in terms of ensuring we get new S3 functionality as it's put out (into boto3)... but we just won't have the time to do this in the near future, at least until our migration to Python 2-and-3 (and eventually dropping support for Python 2) is completed.

**Comment by catleeball** [comment]
Some updates:

Matt made [gsutil-mirrors/boto](https://github.com/gsutil-mirrors/boto) that will track the official [boto lib](https://github.com/boto/boto)'s develop branch. We'll stage our changes there. Gsutil will consume gsutil-mirrors/boto as a submodule in gsutil/third_party/vendored/boto.

:rocket:

**Comment by houglum** [comment]
I've moved boto into gslib/vendored/boto with #666, just to make sure we can get things working with our own vendored copy of the code.  Next step is to replace the contents of that directory with a git submodule, and ensure that the code there gets packaged up with the gslib portion of gsutil when we build releases for PyPI (while also not including the unnecessary stuff like `.git` files, the `bin/` and `scripts/` directories, etc.

**Comment by catleeball** [comment]
Closing this issue since it seems like you got it all smoothed out. Thank you for doing this!!
