### ISSUE TITLE
cloudshell/devshell usage quota query

### ISSUE THREAD

**Issue by Zibri** [GoogleCloudPlatform/gsutil#763]
In cloudshell (not compute) it seems is possible to know the usage quota only from the web interface at https://console.cloud.google.com/cloudshell/editor?shellonly=true

I have noticed that the page makes a request to https://ssh.cloud.google.com/devshell/quota?authuser=0&token=****

How can we get that token so we can be able to know the usage quota from inside the shell itself or from an external authenticated client?

I tried with the access token but it does not work obviously.

**Comment by houglum** [comment]
It looks like your question doesn't necessarily have to do with gsutil, but with the Cloud Shell in general, so I'm going to mark this gsutil issue as closed.  To check for existing Cloud Shell issues or open a new one, check out the appropriate link under the [GCP Issue Tracker reference page](https://cloud.google.com/support/docs/issue-trackers).
