### ISSUE TITLE
When bucket name starts with a number: CommandException: Incorrect public member type for binding 

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/gsutil#770]
I had a rough few hours trying to figure this out, but I think I finally understand what is going on.

I used deployment manager to create a bucket with a random UUID prefix. Unfortunately for me the UUID started with a number!

I tried running this command:

```
gsutil iam ch allUsers:objectViewer gs://058612a7-ee32-41fe-9f9a-e57cae02b2c3-thing
```

Which resulted in this error

> CommandException: Incorrect public member type for binding gs://058612a7-ee32-41fe-9f9a-e57cae02b2c3-thing

When I deleted that bucket and created a new one that started with a letter, it worked.

So I have to assume that this is a bug in `gsutil iam ch` relating to buckets starting with a number.

**Comment by catleeball** [comment]
Hi @bbzg !

Thanks for reporting this! I was able to reproduce this error and it looks like the command parsing in `gsutil/gslib/utils.py` in the `BindingStringToTuple` function is a little too sensitive. I'll poke around and see if I can fix the logic there to behave a little more nicely when buckets start with a number, and I'll keep this bug updated as we deploy a fix. :slightly_smiling_face: 

Thanks,
Lee

**Comment by catleeball** [comment]
Digging around with the debugger, it looks like this is actually an issue with `gslib/commands/iam.py` https://github.com/GoogleCloudPlatform/gsutil/blob/cca0c5e9b4a576e1712f0178625426fb982bb7b1/gslib/commands/iam.py#L483

The regex here doesn't properly recognize the bucket URL as a bucket if it starts with a number.

**Comment by catleeball** [comment]
There is a fix in the repository's `master` branch now and it should be included in our next release of gsutil. Thank you very much for flagging this issue to us!

**Comment by bbzg** [comment]
No, thank you!
