### ISSUE TITLE
gsutil mv skips the trailing slashes but delete the file

### ISSUE THREAD

**Issue by AnkitSwarnkar** [GoogleCloudPlatform/gsutil#800]
I was trying to move one file from a gs location to another gs location on executing gsutil mv commands However I missed "gs://" in the destination. 
It attempted the file move but the attempt was skipped. However, once skipped it deleted the original file.
Copying gs://<bucket>/2019-05-19_2019-05-25/data_20190519-20190525.csv.gz...
Skipping attempt to download to filename ending with slash (target/sub/dir). This
typically happens when using gsutil to download from a subdirectory
created by the Cloud Console (https://cloud.google.com/console)
Removing  gs://<bucket>/2019-05-19_2019-05-25/data_20190519-20190525.csv.gz...

Ideally, remove should not happen if the previous action got skipped

**Comment by lopezvit** [comment]
After all this time, this issue haven't been solved? It just happened to me and totally lost the original file.

**Comment by YannisPap** [comment]
Happened to us also. In our case, it was a mistyped `gs:/bucketname` instead of `gs://bucketname`
