### ISSUE TITLE
gsutil don't send cors file

### ISSUE THREAD

**Issue by Ihernandezpi** [GoogleCloudPlatform/gsutil#882]
Hello! I'm trying update cors from firebase project, but I got an error: 
```
C:\Program Files (x86)\Google\Cloud SDK>gsutil cors set 'C:\Program Files (x86)\Google\Cloud SDK\cors.json' gs://horas-io-canvas.appspot.com

CommandException: "cors" command does not support "file://" URLs. Did you mean to use a gs:// URL?
```
cors.json :
```
[
  {
    "origin": [
      "*"
    ],
    "method": [
      "GET"
    ],
    "maxAgeSeconds": 3600
  }
] 
```

I  don't know what is happening. Please help me. 

** Note. I have already login with my account and select a default project with gcloud  

Thankyou in advance!

**Comment by stianly** [comment]
I know this is a late reply, but if anyone else has this problem:

I had the same problem, but discovered eventually that my json file was actually saved as a .txt file, so make sure you double check that first.

Also, when you're standing on the folder that contains your json file, you don't need the full path. cors.json is sufficient. In your case, you'd write:
C:\Program Files (x86)\Google\Cloud SDK>gsutil cors set cors.json gs://horas-io-canvas.appspot.com
