### ISSUE TITLE
gsutil cp fails to copy file if path is new.

### ISSUE THREAD

**Issue by CeMora** [GoogleCloudPlatform/gsutil#910]
I suspect a regression was introduced. When trying to copy a file to storage if the path does not exist then the file is not copied but the path structure is created (as seen in the ui/ls). Repeating the exact same command a second time will result in actually copying the file to the desired location.

Worked as expected in gsutil version: 4.36

Behavior in current gsutil version: 4.43 shown below.

`$ gsutil cp <my_file> gs://<my_bucket>/<my_path>/`
Copying file://<my_file> [Content-Type=application/octet-stream]...
/ [1 files][   15.0 B/   15.0 B]
Operation completed over 1 objects/15.0 B.

`$ gsutil ls gs://<my_bucket>/<my_path>/`
gs://<my_bucket>/<my_path>/

`$ gsutil cp <my_file> gs://<my_bucket>/<my_path>/`
Copying file://<my_file> [Content-Type=application/octet-stream]...
/ [1 files][   15.0 B/   15.0 B]
Operation completed over 1 objects/15.0 B.

`$ gsutil ls gs://<my_bucket>/<my_path>/`
gs://<my_bucket>/<my_path>/
gs://<my_bucket>/<my_path>/<my_file>

**Comment by mkalmanson** [comment]
Thank you for reporting this.  This is a bug that was introduced in 4.43.  It's been fixed by #905, which was just released in 4.44.  Please reopen this issue if you still experience the bug after upgrading.
