### ISSUE TITLE
Uploading and moving multiple files to a bucket subdirectory don't work as intended

### ISSUE THREAD

**Issue by jterrace** [GoogleCloudPlatform/gsutil#92]
_Original author: mfschwa...@google.com (April 25, 2012 15:19:59)_

From messages posted by a gsutil user on gs-discussion and gsutil-discuss:

I have a set of files such that:
python gsutil ls gs://mybucket/x*.gz
gs:// mybucket /xaa.gz
gs:// mybucket /xas.gz
gs:// mybucket /xat.gz
gs:// mybucket /xau.gz
gs:// mybucket /xav.gz
gs:// mybucket /xaw.gz

And I want to move those files to:
gs://mybucket/mysubfolder/

I would have thought the gsutil mv command would work, but I get the error:
&quot;CommandException: Destination URI must name a directory, bucket, or bucket subdirectory for the multiple source form of the cp command.&quot; 

The command I'm running is:
C:\gsutil&gt;python gsutil mv gs://mybucket/x*.gz gs://mybucket/mysubfolder/

No amount of playing around with the command line seems to be helping unfortunately. I'm using gsutil 3.1 if that helps.

---

And in another message:

While I can upload files individually, I can't seem to specify uploading all the *.gz files.

Here are the commands I'm running (I'm running gsutil from Windows btw):

This is the command to upload 1 file (works fine, and resumable)
python gsutil -d -h &quot;Content-Type: text/plain&quot; cp file://F:\data\data_split\xaa.gz gs://mybucket/mysubdirectory/

I would have therefore thought the following would be the multiple file equivalent:
python gsutil -d -h &quot;Content-Type: text/plain&quot; cp file://F:\data\data_split*.gz gs://mybucket/mysubdirectory/

However, I get:
CommandException: Destination URI must name a directory, bucket, or bucket subdirectory for the multiple source form of the cp command.

The only way I can get it work as intend is by uploading into the bucket itself. This works correctly:
python gsutil -d -h &quot;Content-Type: text/plain&quot; cp file://F:\data\data_split*.gz gs://mybucket/

_Original issue: http://code.google.com/p/gsutil/issues/detail?id=93_

**Comment by jingpengw** [comment]
I am still getting 
```
CommandException: Destination URI must name a directory, bucket, or bucket subdirectory for the multiple source form of the cp command.
```
while uploading.

```
gsutil -v
gsutil version: 4.28
```

**Comment by sukiakiumo** [comment]
@jterrace I am also getting the same error on gsutil v 4.26

**Comment by sukiakiumo** [comment]
Must be an internal network connectivity issue, as I literally did nothing differently, reissued the command, and it worked.

**Comment by EvgeniiProkofev** [comment]
gsutil wont accept variable in path. I am getting error for this:
`gsutil cp *.jar gs://cloud.bucket/$VAR/`
VAR=1.42
> CommandException: Destination URL must name a directory, bucket, or bucket
> subdirectory for the multiple source form of the cp command.
