### ISSUE TITLE
gsutil cp -Z on windows doesn't delete temporary files

### ISSUE THREAD

**Issue by qwertycopter** [GoogleCloudPlatform/gsutil#950]
When copying and compressing files with the -Z flag on windows temporary files are created but not deleted. An error message about the file being locked is displayed.

https://github.com/GoogleCloudPlatform/gsutil/blob/e1d9a0aad5878edffa9f61f53cb6e03ffd713091/gslib/utils/copy_helper.py#L2047-L2059

Moving upload_stream.close() above os.unlink(upload_url.object_name) closes the file before unlinking and fixes this.

**Comment by NickGoog** [comment]
Can you still reproduce this issue?
```
gsutil cp -Z \Users\me\Desktop\200M gs://bucket
gsutil cp -Z gs://bucket/200M \Users\me\Desktop
```

Both commands were successful on Windows 10 for me.
