### ISSUE TITLE
OAuth2 access token stored in world-readable file

### ISSUE THREAD

**Issue by mohamedhafez** [GoogleCloudPlatform/gsutil#994]
When I do the command `gcloud auth activate-service-account --key-file <KEYFILE>`, and then do a gsutil command like `gsutil ls gs://mybucket/`, it generates the `~/.gsutil/credstore2` file with the OAuth2 access token in it, but the file is world-readable:

```
sabu@myhost:~$ ls -l .gsutil/
total 8
-rw-rw-r-- 1 sabu sabu 4442 Apr 28 11:07 credstore2
-rw-rw-r-- 1 sabu sabu    0 Apr 28 11:07 credstore2.lock
```

**Comment by mohamedhafez** [comment]
I believe the line causing the issue is [this one](https://github.com/googleapis/oauth2client/blob/50d20532a748f18e53f7d24ccbe6647132c979a9/oauth2client/contrib/multiprocess_file_storage.py#L110) in the oauth2client library creating the credential file with default permissions. 

I'd make an issue report there or even try to take a stab at fixing it (I don't know any python though), but the repo is now read only, and says its now deprecated and unmaintained...

**Comment by mohamedhafez** [comment]
It looks like the code sets up a `MultiprocessFileStorage` instance [here](https://github.com/GoogleCloudPlatform/gsutil/blob/9af326229303d8636dcb6743b7d8c49f59f50d16/gslib/gcs_json_credentials.py#L152), and taking a look at the source for that in [the oauth2client library](https://github.com/googleapis/oauth2client), it looks like in the `acquire_lock` method it ends up calling `_create_file_if_needed`, which creates the credstore2 file with the default permissions [on this line](https://github.com/googleapis/oauth2client/blob/50d20532a748f18e53f7d24ccbe6647132c979a9/oauth2client/contrib/multiprocess_file_storage.py#L110). 

So I'd say this is actually a bug in the oauth2client library, and I would submit an issue there, but it says the project is read-only and is deprecated and no longer maintained...

**Comment by mohamedhafez** [comment]
The tracker files that get generated for large uploads in `~/.gsutil/tracker-files` are world readable as well. I'm not sure if they contain sensitive info, it looks like there's an `upload_id` token in there though which might be

**Comment by thomasmaclean** [comment]
I think umask would be a good straightforward solution.

**Comment by mohamedhafez** [comment]
@dilipped are the tracker files in `~/.gsutil/tracker-files` and specifically the `upload_id` token in those files not sensitive? They are world-readable as well, just wanted to make sure you knew about that.

Thanks so much for the quick fix btw!

**Comment by dilipped** [comment]
@mohamedhafez You're welcome and thanks for raising the issue. I haven't looked into upload_id yet but my guess would be that the upload_id is some unique identifier and does not contain anything sensitive. BTW, I wasn't able to see `upload_id` in the tracker files, can you provide steps to generate a file which has `upload_id`?

**Comment by mohamedhafez** [comment]
@dilipped just from the name of the variable you're probably correct, but figured it would be worth double checking. If you upload a large file (1.5 GB for example), a world readable file in the `~/.gsutil/tracker-files` directory will be created with a name like `upload_TRACKER_484e007e8647cd5c328a927e768d38a8a404a07f.sql.gz__JSON.url` (the file is deleted once the upload is complete). Inside that file, you'll see contents like this:

```
{"encryption_key_sha256": null, "serialization_data": "{\"auto_transfer\": false, \"mime_type\": \"application/x-sql\", \"total_size\": 1492101725, \"url\": \"https://storage.googleapis.com/resumable/upload/storage/v1/b/dbbu/o?alt=json&fields=generation%2Cetag%2Cmd5Hash%2Ccrc32c%2Csize%2CcustomerEncryption&uploadType=resumable&upload_id=AAA3WmIwt1wuCnutvJUXL_O5VziH2TrzStYQVSSD-AXKlIpdbCS8xrJQIAy6-t7q7MiqHpprN8jVypz0ZewNgjbNB1U\"}"} 
```

The only thing that looks like it could possibly be sensitive in there is the `upload_id` url parameter of the `url` variable. I'm guessing you'd need an OAuth2 access token to access that url, in which case the world-readability of this url wouldn't be an issue, but like I said just figured it'd be worth making certain.

**Comment by dilipped** [comment]
@mohamedhafez Thanks, will take a look
